### ISSUE TITLE
[question] Why opcache.enable = Off ?

### ISSUE THREAD

**Issue by ceefour** [bitnami/bitnami-docker-moodle#100]
**Description**

In `/opt/bitnami/php/conf/php.ini`, Bitnami sets `opcache.enable = Off`

I wonder why this is the case, since having opcode caching enabled seems a good idea for performance reasons. It should be default unless the user wants to turn it off (by extending the Dockerfile).

**Steps to reproduce the issue:**

Run `bitnami/moodle:latest`

**Comment by ceefour** [comment]
I tried to extend by:

```docker
FROM bitnami/moodle:latest

# Enable opcache
RUN sed -i 's/opcache.enable = Off/opcache.enable = 1/I' /opt/bitnami/php/conf/php.ini
```

but it seems bitnami adds the `opcache.enable = Off` **after** my `RUN`  commands.

How do I enable opcache ?

**Comment by ceefour** [comment]
Now trying this:

```
RUN echo "opcache.enable = 1" > /opt/bitnami/php/etc/conf.d/opcache.ini
```

**Comment by marcosbc** [comment]
Hi @ceefour, we were disabling Opcache due to it causing segfaults to Apache when installing a plugin.

However, that was with older releases with PHP, we'll check if the current release is still affected by this.

**Comment by marcosbc** [comment]
Hi @ceefour, we checked the latest release and we didn't find any issues with opcache enabled, so we released it! Closing this case, but feel free to add any comments.
