### ISSUE TITLE
How to install SSL certificates on Moodle since 3.7.0-debian-9-r12 and 3.7.0-ol-7-r13

### ISSUE THREAD

**Issue by zimcke** [bitnami/bitnami-docker-moodle#102]
I have a question regarding how to install custom SSL certificates on my running Moodle instance. It is not clear to me how I should mount the certificate, since placing them at `/opt/bitnami/apache/certs` became deprecated. I generated my certificate using Zerossl and place them in a seperate folder `/home/apache-certs`. The documentation only explains how to deploy a new Apache container and add the certificates with a `-v` flag. Could you share a concrete code example to show how to do this for a running Moodle container?

My Moodle container was created like this:
`docker volume create --name moodle_data`
`docker run -d --name moodle -p 80:80 -p 443 \`
`-e MOODLE_DATABASE_USER=bn_moodle \`
`-e MOODLE_DATABASE_NAME=bitnami_moodle \`
`--net moodle-tier --volume moodle_data:/bitnami bitnami/moodle:latest`

 Thank you for any help! I have been using Bitnami Moodle for the past two years and it has been great!

**Comment by javsalgar** [comment]
Hi,

Did mounting the certificates in `/certs` work for you? This is for Apache but it should work for Moodle as well

https://github.com/helm/charts/issues/17244

**Comment by danieldiazastudillo** [comment]
@zimcke did you get this to work with @javsalgar solution? Any news on this?

**Comment by javsalgar** [comment]
Hi @danieldiazastudillo did you find any issues with the solution above?
