### ISSUE TITLE
Can´t Modify The PHP File Upload Limit

### ISSUE THREAD

**Issue by felixdiez** [bitnami/bitnami-docker-moodle#104]
Hi there,

I have installed this container and I can not increase the PHP file upload limit since:

* It seems that there is not any text editor in this container image.
* When I stop/start Apache inside the container, the whole container is stopped.

Is there any way to change the php.ini for increase the PHP file upload limit and 
restart the service with a persistant configuration?

Thanks in advanced.

 **Info required:**
 
**:~$ docker version**
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

**:~$ docker info**
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-9:3-655312-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.221GB
 Data Space Total: 107.4GB
 Data Space Available: 17.72GB
 Metadata Space Used: 19.68MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.128GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.19.0-ovh-xxxx-std-ipv6-64
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.25GiB
Name: ns3159677
ID: 7WJZ:SLLF:OBSF:F3ML:SCXY:EIRG:7QYD:6XSW:PWUS:BZQ5:SGJZ:JX7O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

root@769f1f15f1c7:/# echo **$BITNAMI_IMAGE_VERSION**
3.7.2-debian-9-r33

**Comment by gongomgra** [comment]
Hi @felixdiez, by default our images do not include any editor to restrict the image size as much as possible. You can install the editor of your preference using apt-get or the `install_packages` command:

```
install_packages vim
```

Regarding the `php.ini` question, you can modify the file and restart the container with no issues. These changes will persist as long as you don't modify the Bitnami Moodle image you are using. In case you want to update the image without losing the changes in the PHP configuration, you can define your own `php.ini` file and mount it as a volume into the Moodle container at `/opt/bitnami/php/conf/php.ini` in the `docker-compose.yml` file.
