### ISSUE TITLE
I lost all my production data

### ISSUE THREAD

**Issue by tmedeiros** [bitnami/bitnami-docker-moodle#108]
I thought I understood how to make my bitnami moodle persistent, but I was wrong. I lost all my production data. I updated my docker-compose file with nginx-proxy and that rebuilt my container and the whole data was gone

This is a snippet of my docker-compose file

 volumes:
      - 'moodle_data:/prod_data'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local

Is this the correct way to make /prod_data persistent?

**Comment by miguelaeh** [comment]
Hi @tmedeiros ,
It seems you mounted the wrong directory. To persistent the container data you should mount the volume into `/bitnami` as it is described here https://github.com/bitnami/bitnami-docker-moodle#how-to-use-this-image
Also, you can check the following `docker-compose.yml`: https://github.com/bitnami/bitnami-docker-moodle/blob/master/docker-compose.yml

This:
```
- 'moodle_data:/prod_data'
```
Should be changed by
```
- 'moodle_data:/bitnami'
```
Also, the MariaDB container should mount its own volume in `/bitnami` too.

**Comment by tmedeiros** [comment]
Thank you Miguel for the prompt response.

I want to mount my volume to an attached disk on Azure. So, I have this updated docker-compose file

mariadb:
   volumes:
      - '/prod_data/mariadb:/bitnami/mariadb'

Moodle:
   volumes:
      - '/prod_data/moodle:/bitnami/moodle'


Then, I have this at the end just the way it is in the sample docker-compose file

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local

I ran docker-compose up -d and I have permission denied

mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied

**Comment by tmedeiros** [comment]
Hi Miguel,

I think I solved the problem by running this in the directory. And the site is up now.

sudo chown -R 1001:1001

Is there a way to get the data back from the container that was recreated?  I never knew that docker would recreate the container when the docker-compose file changed and overwrite the data

**Comment by miguelaeh** [comment]
Hi @tmedeiros ,
You can probably get the volume with the data executing:
```console
docker volume ls
```
Then you should find you old volume and you should be able to get your data from there.

**Comment by tmedeiros** [comment]
I did that already and nothing was there. It was just surprising how the data was wiped away without removing or deleting the container.

Respectfully,
Theo Medeiros
________________________________

**Comment by miguelaeh** [comment]
Hi @tmedeiros ,
I am afraid if you didn't have the volume and you didn't mount a local directory the data was lost.
What I don't understand is why you volume is not there. Did you execute `docker-compose down -v` ? That command deletes the volumes so if you executed it, probably that is why you lost the data.
