### ISSUE TITLE
Locale Your server does not seem to fully support the following languages 

### ISSUE THREAD

**Issue by fodrice** [bitnami/bitnami-docker-moodle#112]
Just installed docker container on fresh debian 10.3
```
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-moodle/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d
```

Then in 
Dashboard ->   Site administration ->  Language  ->  Language packs
I got warning:
Your server does not seem to fully support the following languages:
    English ‎(en)‎
    Русский ‎(ru)‎
    Українська ‎(uk)‎
Instead, the global locale (en_AU.UTF-8) will be used to format certain strings such as dates or numbers.
Moddle forum saying that I should add locales.

**Comment by fodrice** [comment]
Fixed this by instaling locales-all package
```
sudo docker-compose up -d
sudo docker-compose exec moodle /bin/bash
apt-get update
apt-get install locale-all
```
Think I've done it wrong.

**Comment by juan131** [comment]
Hi @fodrice 

Thanks for reporting it! We released a new version of Moodle that includes the `locales` packages (version `3.8.2-debian-10-r28`).

By default `en_US.UTF-8 UTF-8` locales are configured. You should be able to add any locale you want using the same commands used in the Dockerfile. See:

- https://github.com/bitnami/bitnami-docker-moodle/blob/master/3/debian-10/Dockerfile#L23
