### ISSUE TITLE
Cannot send emails using external smtp

### ISSUE THREAD

**Issue by hugokoopmans** [bitnami/bitnami-docker-moodle#113]
**Description**
I try to send email

**Steps to reproduce the issue:**

1. setup sendgrid | gmail | any other smtp
2. setup email in moodle
3. send test email

**Describe the results you received:**

Your site couldn't communicate with your mail server. Please check your outgoing mail configuration. 

**Describe the results you expected:**

email send correctly

**Additional information you deem important (e.g. issue happens only occasionally):**

I installed the test email plugin, nu luck

I increased debugging level

**Version**

- Output of `docker version`:

```
docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-96-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.789GiB
 Name: 149-210-174-128
 ID: IUXW:FKWB:BHNZ:RDLO:FXT6:SYBW:PVD2:EC6G:4MOJ:WQ27:IGQN:ZB4U
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

run on ubuntu 18.04 host 

log:

172.18.0.5 - - [10/Apr/2020:17:33:23 +0000] "GET /login/index.php HTTP/1.1" 200 6588
172.18.0.5 - - [10/Apr/2020:17:33:23 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:33:26 +0000] "GET / HTTP/1.1" 303 425
172.18.0.5 - - [10/Apr/2020:17:33:26 +0000] "GET /my/ HTTP/1.1" 200 22129
172.18.0.5 - - [10/Apr/2020:17:33:27 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_calendar_get_calendar_monthly_view HTTP/1.1" 200 35510
172.18.0.5 - - [10/Apr/2020:17:33:27 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_course_get_recent_courses HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:33:27 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:33:27 +0000] "GET /lib/ajax/service-nologin.php?info=core_get_string&cachekey=1586457559&args=%5B%7B%22index%22%3A0%2C%22methodname%22%3A%22core_get_string%22%2C%22args%22%3A%7B%22stringparams%22%3A%5B%5D%2C%22lang%22%3A%22en%22%7D%7D%5D HTTP/1.1" 200 225
172.18.0.5 - - [10/Apr/2020:17:33:27 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_course_get_enrolled_courses_by_timeline_classification HTTP/1.1" 200 54
172.18.0.5 - - [10/Apr/2020:17:33:28 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_calendar_get_action_events_by_timesort HTTP/1.1" 200 67
172.18.0.5 - - [10/Apr/2020:17:33:29 +0000] "GET /admin/search.php HTTP/1.1" 200 22696
172.18.0.5 - - [10/Apr/2020:17:33:31 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:33:36 +0000] "GET /admin/settings.php?section=outgoingmailconfig HTTP/1.1" 200 18993
172.18.0.5 - - [10/Apr/2020:17:33:37 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:34:34 +0000] "POST /admin/settings.php?section=outgoingmailconfig HTTP/1.1" 303 467
172.18.0.5 - - [10/Apr/2020:17:34:35 +0000] "GET /admin/settings.php?section=outgoingmailconfig HTTP/1.1" 200 19163
172.18.0.5 - - [10/Apr/2020:17:34:36 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:34:42 +0000] "GET /admin/testoutgoingmailconf.php HTTP/1.1" 200 16882
172.18.0.5 - - [10/Apr/2020:17:34:43 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:34:51 +0000] "POST /admin/testoutgoingmailconf.php HTTP/1.1" 200 16996
172.18.0.5 - - [10/Apr/2020:17:34:53 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:36:37 +0000] "GET /admin/search.php HTTP/1.1" 200 22692
172.18.0.5 - - [10/Apr/2020:17:36:38 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:36:52 +0000] "GET /admin/settings.php?section=debugging HTTP/1.1" 200 17335
172.18.0.5 - - [10/Apr/2020:17:36:54 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:44:51 +0000] "GET /admin/index.php?installaddonrequest=eyJuYW1lIjoiTW9vZGxlIGVNYWlsIFRlc3QiLCJjb21wb25lbnQiOiJsb2NhbF9tYWlsdGVzdCIsInZlcnNpb24iOiIyMDE5MTExNzAwIn0%3D HTTP/1.1" 303 600
172.18.0.5 - - [10/Apr/2020:17:44:52 +0000] "GET /admin/tool/installaddon/index.php?installaddonrequest=eyJuYW1lIjoiTW9vZGxlIGVNYWlsIFRlc3QiLCJjb21wb25lbnQiOiJsb2NhbF9tYWlsdGVzdCIsInZlcnNpb24iOiIyMDE5MTExNzAwIn0%3D&confirm=0 HTTP/1.1" 200 16372
172.18.0.5 - - [10/Apr/2020:17:44:54 +0000] "GET /theme/font.php/moove/core/1586531212/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77160
172.18.0.5 - - [10/Apr/2020:17:44:54 +0000] "GET /theme/image.php/moove/theme/1586531212/footer-bg HTTP/1.1" 200 130547
172.18.0.5 - - [10/Apr/2020:17:44:54 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:44:56 +0000] "POST /admin/tool/installaddon/index.php HTTP/1.1" 200 6469
172.18.0.5 - - [10/Apr/2020:17:44:57 +0000] "GET /theme/image.php/moove/theme/1586531212/favicon HTTP/1.1" 200 1150
172.18.0.5 - - [10/Apr/2020:17:44:58 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:45:01 +0000] "POST /admin/tool/installaddon/index.php HTTP/1.1" 303 470
172.18.0.5 - - [10/Apr/2020:17:45:01 +0000] "GET /admin/index.php?cache=0&confirmplugincheck=0 HTTP/1.1" 200 7235
172.18.0.5 - - [10/Apr/2020:17:45:03 +0000] "GET /theme/image.php/moove/local_mailtest/1586531212/icon HTTP/1.1" 200 719
172.18.0.5 - - [10/Apr/2020:17:45:04 +0000] "GET /theme/image.php/moove/theme/1586531212/favicon HTTP/1.1" 200 1150
172.18.0.5 - - [10/Apr/2020:17:45:04 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:45:09 +0000] "GET /admin/index.php?cache=0&confirmplugincheck=1 HTTP/1.1" 200 6400
172.18.0.5 - - [10/Apr/2020:17:45:10 +0000] "GET /lib/javascript.php/1586540710/lib/mdn-polyfills/polyfill.js HTTP/1.1" 200 3416
172.18.0.5 - - [10/Apr/2020:17:45:10 +0000] "GET /lib/javascript.php/1586540710/lib/javascript-static.js HTTP/1.1" 200 6777
172.18.0.5 - - [10/Apr/2020:17:45:10 +0000] "GET /lib/javascript.php/1586540710/lib/babel-polyfill/polyfill.min.js HTTP/1.1" 200 32862
172.18.0.5 - - [10/Apr/2020:17:45:11 +0000] "GET /lib/javascript.php/1586540711/lib/requirejs/require.min.js HTTP/1.1" 200 6662
172.18.0.5 - - [10/Apr/2020:17:45:13 +0000] "GET /theme/image.php/moove/theme/1586540710/favicon HTTP/1.1" 200 1150
172.18.0.5 - - [10/Apr/2020:17:45:10 +0000] "GET /theme/styles.php/moove/1586540710_1/all HTTP/1.1" 200 136448
172.18.0.5 - - [10/Apr/2020:17:45:30 +0000] "GET /lib/requirejs.php/1586540711/core/first.js HTTP/1.1" 200 265018
172.18.0.5 - - [10/Apr/2020:17:45:31 +0000] "GET /lib/javascript.php/1586540711/lib/jquery/jquery-3.4.1.min.js HTTP/1.1" 200 30681
172.18.0.5 - - [10/Apr/2020:17:45:31 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:45:33 +0000] "GET /admin/upgradesettings.php HTTP/1.1" 200 9898
172.18.0.5 - - [10/Apr/2020:17:45:35 +0000] "GET /theme/styles.php/moove/1586540711_1/all HTTP/1.1" 200 136454
172.18.0.5 - - [10/Apr/2020:17:45:35 +0000] "GET /lib/javascript.php/1586540711/lib/mdn-polyfills/polyfill.js HTTP/1.1" 200 3416
172.18.0.5 - - [10/Apr/2020:17:45:35 +0000] "GET /lib/javascript.php/1586540711/lib/javascript-static.js HTTP/1.1" 200 6777
172.18.0.5 - - [10/Apr/2020:17:45:35 +0000] "GET /lib/javascript.php/1586540711/lib/babel-polyfill/polyfill.min.js HTTP/1.1" 200 32862
172.18.0.5 - - [10/Apr/2020:17:45:35 +0000] "GET /theme/yui_combo.php?m/1586540711/core/event/event-min.js&m/1586540711/filter_mathjaxloader/loader/loader-min.js HTTP/1.1" 200 868
172.18.0.5 - - [10/Apr/2020:17:45:35 +0000] "GET /theme/image.php/moove/theme/1586540711/favicon HTTP/1.1" 200 1150
172.18.0.5 - - [10/Apr/2020:17:45:36 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:46:05 +0000] "POST /admin/upgradesettings.php HTTP/1.1" 303 437
172.18.0.5 - - [10/Apr/2020:17:46:06 +0000] "GET /admin/index.php HTTP/1.1" 303 445
[Fri Apr 10 17:46:07.291957 2020] [core:alert] [pid 188] [client 172.18.0.5:39150] /opt/bitnami/moodle/moodledata/.htaccess: AllowOverride not allowed here
172.18.0.5 - - [10/Apr/2020:17:46:07 +0000] "GET /moodledata//diag/public.txt HTTP/1.1" 500 528
[Fri Apr 10 17:46:07.304927 2020] [core:alert] [pid 91] [client 172.18.0.5:39156] /opt/bitnami/moodle/moodledata/.htaccess: AllowOverride not allowed here
172.18.0.5 - - [10/Apr/2020:17:46:07 +0000] "GET /moodledata//diag/public.txt HTTP/1.1" 500 528
172.18.0.5 - - [10/Apr/2020:17:46:06 +0000] "GET /admin/index.php?cache=1 HTTP/1.1" 200 16484
172.18.0.5 - - [10/Apr/2020:17:46:09 +0000] "GET /pluginfile.php/1/theme_moove/logo/1586540711/dikw-academy-logo.png HTTP/1.1" 200 24946
172.18.0.5 - - [10/Apr/2020:17:46:09 +0000] "GET /theme/image.php/moove/core/1586540711/i/sendmessage HTTP/1.1" 200 643
172.18.0.5 - - [10/Apr/2020:17:46:09 +0000] "GET /theme/font.php/moove/theme/1586540711/Simple-Line-Icons.woff2?v=2.4.0 HTTP/1.1" 200 30064
172.18.0.5 - - [10/Apr/2020:17:46:09 +0000] "GET /theme/font.php/moove/core/1586540711/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77160
172.18.0.5 - - [10/Apr/2020:17:46:09 +0000] "GET /theme/image.php/moove/theme/1586540711/footer-bg HTTP/1.1" 200 130547
172.18.0.5 - - [10/Apr/2020:17:46:09 +0000] "GET /pluginfile.php/1/theme_moove/favicon/1586540711/favicon.ico HTTP/1.1" 200 1150
172.18.0.5 - - [10/Apr/2020:17:46:10 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:46:33 +0000] "GET /admin/search.php HTTP/1.1" 200 22810
172.18.0.5 - - [10/Apr/2020:17:46:34 +0000] "GET /theme/yui_combo.php?m/1586540711/core/formchangechecker/formchangechecker-min.js HTTP/1.1" 200 911
172.18.0.5 - - [10/Apr/2020:17:46:34 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:47:31 +0000] "GET /admin/settings.php?section=debugging HTTP/1.1" 200 17431
172.18.0.5 - - [10/Apr/2020:17:47:33 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:48:00 +0000] "POST /admin/settings.php?section=debugging HTTP/1.1" 303 458
172.18.0.5 - - [10/Apr/2020:17:48:01 +0000] "GET /admin/settings.php?section=debugging HTTP/1.1" 200 17501
172.18.0.5 - - [10/Apr/2020:17:48:02 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:48:04 +0000] "GET /admin/search.php HTTP/1.1" 200 22808
172.18.0.5 - - [10/Apr/2020:17:48:06 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:48:13 +0000] "GET /local/mailtest/ HTTP/1.1" 200 17695
172.18.0.5 - - [10/Apr/2020:17:48:14 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:49:03 +0000] "POST /local/mailtest/ HTTP/1.1" 200 16449
172.18.0.5 - - [10/Apr/2020:17:49:04 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:49:44 +0000] "GET /admin/settings.php?section=outgoingmailconfig HTTP/1.1" 200 19183
172.18.0.5 - - [10/Apr/2020:17:49:45 +0000] "GET /lib/ajax/service-nologin.php?info=core_output_load_fontawesome_icon_map&cachekey=1586540711&args=%5B%7B%22index%22%3A0%2C%22methodname%22%3A%22core_output_load_fontawesome_icon_map%22%2C%22args%22%3A%5B%5D%7D%5D HTTP/1.1" 200 28073
172.18.0.5 - - [10/Apr/2020:17:49:46 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:49:46 +0000] "GET /lib/ajax/service-nologin.php?info=core_output_load_template_with_dependencies&cachekey=1586540711&args=%5B%7B%22index%22%3A0%2C%22methodname%22%3A%22core_output_load_template_with_dependencies%22%2C%22args%22%3A%7B%22component%22%3A%22core_form%22%2C%22template%22%3A%22element-passwordunmask-fill%22%2C%22themename%22%3A%22moove%22%2C%22lang%22%3A%22en%22%7D%7D%5D HTTP/1.1" 200 580
172.18.0.5 - - [10/Apr/2020:17:49:46 +0000] "GET /lib/ajax/service-nologin.php?info=core_output_load_template_with_dependencies&cachekey=1586540711&args=%5B%7B%22index%22%3A0%2C%22methodname%22%3A%22core_output_load_template_with_dependencies%22%2C%22args%22%3A%7B%22component%22%3A%22core%22%2C%22template%22%3A%22pix_icon_fontawesome%22%2C%22themename%22%3A%22moove%22%2C%22lang%22%3A%22en%22%7D%7D%5D HTTP/1.1" 200 489
172.18.0.5 - - [10/Apr/2020:17:52:51 +0000] "GET /admin/testoutgoingmailconf.php HTTP/1.1" 200 16986
172.18.0.5 - - [10/Apr/2020:17:52:52 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:17:52:59 +0000] "POST /admin/testoutgoingmailconf.php HTTP/1.1" 200 17096
172.18.0.5 - - [10/Apr/2020:17:53:01 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:18:02:49 +0000] "GET /admin/testoutgoingmailconf.php HTTP/1.1" 200 16982
172.18.0.5 - - [10/Apr/2020:18:02:50 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:18:02:52 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:18:10:15 +0000] "GET /admin/testoutgoingmailconf.php HTTP/1.1" 200 16979
172.18.0.5 - - [10/Apr/2020:18:10:16 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27
172.18.0.5 - - [10/Apr/2020:18:10:27 +0000] "POST /admin/testoutgoingmailconf.php HTTP/1.1" 200 17098
172.18.0.5 - - [10/Apr/2020:18:10:29 +0000] "POST /lib/ajax/service.php?sesskey=RKeeaTS0bV&info=core_fetch_notifications HTTP/1.1" 200 27

**Comment by hugokoopmans** [comment]
My docker-compose file

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=dikw_moodle
      - MARIADB_DATABASE=moodle_db
      - MARIADB_ROOT_PASSWORD=xxxxxxx
      - MARIADB_PASSWORD=xxxxxxxx
      - ALLOW_EMPTY_PASSWORD=no
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_PORT=465
      - SMTP_USER=apikey
      - SMTP_PASSWORD=yyyyyyyyyy
      - SMTP_PROTOCOL=tls
    volumes:
      - '/data/docker/moodle/mariadb_data:/bitnami'
  moodle:
    image: 'bitnami/moodle:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=dikw_moodle
      - MOODLE_DATABASE_NAME=moodle_db
      - MOODLE_DATABASE_PASSWORD=zzzzzzz
      - ALLOW_EMPTY_PASSWORD=no
# letsencrypt
      - VIRTUAL_HOST=xxx
      - LETSENCRYPT_HOST=xxx
      - LETSENCRYPT_EMAIL=xxx

    ports:
      - '8080:80'
      - '8443:443'
      - '25:25'
      - '465:465'
      - '587:587'
    volumes:
      - '/data/docker/moodle/moodle_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
```

**Comment by hugokoopmans** [comment]
so do i need an MTA on the docker host?

**Comment by andresbono** [comment]
Hi @hugokoopmans, did you try other protocol/ports configuration? Can you check if port `587` or protocol `ssl` make it work?

Please note that on each change of the docker-compose, you need to restart the containers from scratch without persisting volumes.

**Comment by hugokoopmans** [comment]
@andresbono yes I tried all configs, no luck but...

**Comment by hugokoopmans** [comment]
@andresbono "Please note that on each change of the docker-compose, you need to restart the containers from scratch without persisting volumes."

It should be possible to set the SMTP parameters manually if I would know where to find them ... any hint on this? It seems a bit cumbersome to rebuild the whole container when the only thing I need is a proper environment setting ...

**Comment by hugokoopmans** [comment]
ok now I get

**Comment by hugokoopmans** [comment]
so the container cannot resolve any DNS

**Comment by hugokoopmans** [comment]
ok it turned out to be a local firewall issue for port 465

so for the record , i use sendgrid SSL on port 465 which worked!

**Comment by andresbono** [comment]
Great, thanks for confirming @hugokoopmans!! :tada:

**Comment by hariresume** [comment]
Hi @hugokoopmans. I have the same problem and am unable to resolve it. I am using traefik as a reverse proxy to my docker container. Can you please let me know what solved the issue? Also, the logs seem to be piped out to /dev/stdout and /dev/stderr, how do I access them. Thank you

**Comment by marcosbc** [comment]
@hariresume To access your logs, just do `docker logs CONTAINER_ID` where CONTAINER_ID is the name or id of the container (you can check it with `docker ps`).

Also, note that a network issue with SMTP happens when the container is not properly able to make the requests to the web services (i.e. from the container to the Internet). It has nothing to do with how you as a user are accessing your Moodle container via HTTP.

**Comment by hariresume** [comment]
Thanks for the reply @marcosbc. I am quite new to docker and Google led me here to this issue. 

>Also, note that a network issue with SMTP happens when the container is not properly able to make the requests to the web services

I was of the opinion that my traefik configuration might be preventing smtp access.

This is my docker-compose file

`version: '2'

networks:
  web:
    external: true
  internal:
    external: false

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=xxx
      - MARIADB_USER=xxx
      - MARIADB_DATABASE=xxx
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    labels:
      - traefik.enable=false
    networks:
      - internal
  
  moodle:
    image: 'docker.io/bitnami/moodle:3-debian-10'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=xxx
      - MOODLE_DATABASE_NAME=xxx
      - ALLOW_EMPTY_PASSWORD=xxx
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=120M
      - PHP_MAX_EXECUTION_TIME=360
      - MOODLE_USERNAME=xxx
      - MOODLE_PASSWORD=xxx
      - MOODLE_SITE_NAME=xxx
    labels:
      - traefik.backend=moodle
      - traefik.frontend.rule=Host:xxx
      - traefik.docker.network=web
      - traefik.port=8080
    networks:
      - internal
      - web
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
`

and this is my traefik toml file

`defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["xxx"]

[api]
entrypoint="dashboard"
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[acme]
email = "xxx"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
domain = "xxx"
watch = true
network = "web"
`
Should I modify something in order to allow SMTP access to docker (port 2525)?
I am able to telnet into 2525 port of my SMTP server from my host machine, so it is not a host firewall problem. This is probably not the right place to ask this, but thanks for your reply anyways.

**Comment by javsalgar** [comment]
Hi,

Are able to access the SMTP server when entering  the Moodle container? (docker exec) That would help us to know if there's a firewall issue.
