### ISSUE TITLE
Cannot install SSL certs

### ISSUE THREAD

**Issue by jpstokes** [bitnami/bitnami-docker-moodle#115]
I'm currently running this install on a Debian 10 server. I'm working on securing the server but got stuck on adding the SSL certs. The documentation mentioned using Lego to install Let's Encrypt and the certs. The instructions instruct you to stop the bitnami services prior to running Lego, however, the command given does not work since the `/opt/bitnami/ctlscript.sh` file does not exist. I looked for numerous ways to stop the service to no avail. I also tried installing Let's Encrypt without using Lego and did several other solutions that I found on the web with no success. I think due to not being able to stop the services and the file not being available, it is impossible to install SSL on the current version of this install. 

**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by dani8art** [comment]
Hi @jpstokes , are you using containers, right? yes, you can use [1] but it is a bit different, when it say `ctlscripts.sh` to manage the service status `start|stop` you must use docker or docker-compose and also you must have volumes with the certs files like [2], [3]

In addition, there are other ways of generating certs for containers like [4]
1. https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/ 
2. https://github.com/bitnami/bitnami-docker-moodle#extend-this-image
3. https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates
4. https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion

**Comment by jpstokes** [comment]
Thanks Dani, that got me going!
