### ISSUE TITLE
Problem with redirecting traffic from HTTP to HTTPS

### ISSUE THREAD

**Issue by jpstokes** [bitnami/bitnami-docker-moodle#116]
**Description**

I am using docker-compose to run moodle in a container. I have installed SSL and I followed a guide to force the https redirect at: https://docs.bitnami.com/aws/apps/moodle/administration/force-https-apache/. 

My issue is that my configuration changes have not taken effect and users can still hit the site in an unsecured manner until I get this fixed.

My /opt/bitnami/apache2/conf/bitnami/bitnami.conf file looks like:

```
# Default Virtual Host configuration.

# Let apache know we're behind a SSL reverse proxy
SetEnvIf X-Forwarded-Proto https HTTPS=on

<VirtualHost _default_:80>
  DocumentRoot "/opt/bitnami/apache/htdocs"
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
  RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]
  <Directory "/opt/bitnami/apache/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

  # Error Documents
  ErrorDocument 503 /503.html

</VirtualHost>

Include "/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf"
```

**Describe the results you received:**

After making the changes above, backed out of the moodle container and restarted moodle using docker-compose. When that did not work, I created a bash session back into the moodle container and restarted the apache server from inside the container which did not work either.

In either case, was still able to access the site using port 80.

**Describe the results you expected:**

When users hit the site at port 80 the server should automatically redirect them to port 443 (SSL)

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:58 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:32 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-8-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.948GiB
 Name: localhost
 ID: R5YI:MUUK:U3AB:SREL:5T3O:JIFL:6TWB:HVPL:IQHI:BS2B:Q6RY:CMAT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Using a Debian 10 box on linode.com

**Comment by dani8art** [comment]
Hi @jpstokes could you try the solution I've attached.
[auto-redirect-ssl.tar.gz](https://github.com/bitnami/bitnami-docker-moodle/files/4493979/auto-redirect-ssl.tar.gz)

**Comment by jpstokes** [comment]
I got the following error when starting Moodle after making changes:

root@localhost:~# docker-compose up
root_mariadb_1 is up-to-date
Recreating root_moodle_1 ... error

ERROR: for root_moodle_1  Cannot start service moodle: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/root/app-entrypoint.sh\\\" to rootfs \\\"/var/lib/docker/overlay2/27128b72cd05840984dac82f09141c954ba397757006dfc9819410ee303a528b/merged\\\" at \\\"/var/lib/docker/overlay2/27128b72cd05840984dac82f09141c954ba397757006dfc9819410ee303a528b/merged/app-entrypoint.sh\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for moodle  Cannot start service moodle: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/root/app-entrypoint.sh\\\" to rootfs \\\"/var/lib/docker/overlay2/27128b72cd05840984dac82f09141c954ba397757006dfc9819410ee303a528b/merged\\\" at \\\"/var/lib/docker/overlay2/27128b72cd05840984dac82f09141c954ba397757006dfc9819410ee303a528b/merged/app-entrypoint.sh\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by jpstokes** [comment]
That fixed it!

**Comment by machimocho** [comment]
> Hi @jpstokes could you try the solution I've attached.
> [auto-redirect-ssl.tar.gz](https://github.com/bitnami/bitnami-docker-moodle/files/4493979/auto-redirect-ssl.tar.gz)

@dani8art  thanks a lot man!!! I was cracking my brain because of this one. Equal thanks to @jpstokes for bringing up this issue.
