### ISSUE TITLE
Mariadb using lagacy innodb_empty_free_list_algorithm  

### ISSUE THREAD

**Issue by fodrice** [bitnami/bitnami-docker-moodle#117]
docker-compose up 
gives me this in log
InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.

dived into container 
```
docker exec -it moodle_mariadb_1 /bin/bash
I have no name!@c6f0ed9eb7b6:/$ mysq
SMariaDB [(none)]> SHOW VARIABLES LIKE 'innodb_empty_free_list_algorithm';
+----------------------------------+--------+
| Variable_name                    | Value  |
+----------------------------------+--------+
| innodb_empty_free_list_algorithm | LEGACY |
+----------------------------------+--------+
1 row in set (0.00 sec)

MariaDB [(none)]> SHOW VARIABLES LIKE 'innodb_buffer_pool_size';
+-------------------------+-----------+
| Variable_name           | Value     |
+-------------------------+-----------+
| innodb_buffer_pool_size | 134217728 |
+-------------------------+-----------+
1 row in set (0.00 sec)

```

Adding in my_custom.cnf innodb_buffer_pool_size does nothing (obliviously)
```
[mysqld]
innodb_buffer_pool_size=128m
```
Perhaps something wrong with db creation. 

Using latest images

```
root@debian:# docker image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
bitnami/moodle      3                   399f9fe235ab        16 hours ago        624MB
bitnami/mariadb     10.1                a8d49557488a        4 weeks ago         271MB
```
```
root@debian:# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.0-8-amd64
Operating System: Debian GNU/Linux 10 (buster)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.948GiB
Name: debian
ID: ISKU:RFKJ:7KRH:6K7L:5RB4:QZ7R:AVTY:BPMS:WAO2:OV6V:P24E:TNPX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by andresbono** [comment]
Hi @fodrice, thanks for opening this issue.

> gives me this in log
> InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.

This is just a note, it is not warning about anything wrong, is that correct?
>```
> MariaDB [(none)]> SHOW VARIABLES LIKE 'innodb_buffer_pool_size';
> +-------------------------+-----------+
> | Variable_name           | Value     |
> +-------------------------+-----------+
> | innodb_buffer_pool_size | 134217728 |
> +-------------------------+-----------+
> 1 row in set (0.00 sec)
> ```
> 
> Adding in my_custom.cnf innodb_buffer_pool_size does nothing (obliviously)
> 
> ```
> [mysqld]
> innodb_buffer_pool_size=128m
> ```

Have you tried a different value? For instance my mounting this file in `/opt/bitnami/mariadb/conf/bitnami/my_custom.cnf`:

```
[mysqld]
innodb_buffer_pool_size=40m
```

I get:

```
MariaDB [(none)]> SELECT @@innodb_buffer_pool_size/1024/1024;
+-------------------------------------+
| @@innodb_buffer_pool_size/1024/1024 |
+-------------------------------------+
|                         40.00000000 |
+-------------------------------------+
1 row in set (0.00 sec)
```

Let us know if you think there is something wrong with the configuration of MariaDB.

**Comment by fodrice** [comment]
> This is just a note, it is not warning about anything wrong, is that correct?
no
This is saying that mariadb using legacy algorithm for innodb_empty_free_list_algorithm instead of BACKOFF
Saying that buffer pool is to small for using BACKOFF algorithm when it's not. 
don't know why... maridb bug ? 
https://mariadb.com/kb/en/innodb-system-variables/#innodb_empty_free_list_algorithm

Updated to 10.2 and this gone.

**Comment by andresbono** [comment]
Thanks for letting us know, @fodrice!
