### ISSUE TITLE
error/An error occurred whilst communicating with the server

### ISSUE THREAD

**Issue by nanab4u** [bitnami/bitnami-docker-moodle#118]
Hi, 

Here is the docker-compose.yml which i have used to start moodle and mariadb containers. 

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data_latest:/bitnami'
  moodle:
    image: 'bitnami/moodle:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
    volumes:
      - './moodle_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data_latest:
    driver: local
```

After running docker-compose up -d and after sometime while trying to access the application via browser i'm stuck with following error:

```
Warning: session_start(): Session data file is not created by your uid in /bitnami/moodle/lib/classes/session/handler.php on line 42

Warning: session_start(): Failed to read session data: files (path: /bitnami/moodle/moodledata/sessions) in /bitnami/moodle/lib/classes/session/handler.php on line 42

error/An error occurred whilst communicating with the server
```

Do i miss anything here ?

**Comment by miguelaeh** [comment]
Hi @nanab4u ,
It seems that for some reason your volume permissions are not correct. 
As you are mounting a local volume be sure it is owned by the `root` user, which is the user that will be used inside the container.
```
chown -R root <your volume>
```
Also, I don't recommend you to mount the current folder into the container, I would mount another directory, maybe `./data`.

**Comment by raghumuppa** [comment]
Hello,

@nanab4u Did you find any solution, i'm also facing the same issue here is my docker-compose.yaml file and i have deployed this in docker-swarm

version: '3.6'
services:
  mariadb:
    image: 'bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'sql_data:/bitnami'
  moodle:
    image: 'bitnami/moodle:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin@123
    ports:
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'm_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  sql_data:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=10.10.10.11,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/root/moodle"
  m_data:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=10.10.10.11,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/root/moodle"

here the thing is, moodle is working fine with single instances(container) but when i'm scaling up the moodle containers issue raises.

**Comment by miguelaeh** [comment]
Hi @raghumuppa ,
Could you share your logs? Also, if you are getting the `Session data file is not created by your uid`, could you share the output of:
```
ls -l /bitnami/moodle/lib/classes/session
```

**Comment by raghumuppa** [comment]
Hi

I found the solution, the issue due to readiness fail so i have enabled health check after that i don't see any issues.

<pre>healthcheck:
   test: "curl -f http://localhost:80/ || false"
   interval: 2m
   timeout: 10s
   retries: 3
   start_period: 40s </pre>

**Comment by miguelaeh** [comment]
Hi @raghumuppa ,
I am glad you solved the issue, thank you for sharing the solution.
Please, don't hesitate in contact us again if you find any issues.
