### ISSUE TITLE
Add support to build with more locales

### ISSUE THREAD

**Issue by soriyath** [bitnami/bitnami-docker-moodle#122]
**Description**

This relates to this issue https://github.com/bitnami/charts/issues/2493 on the Moodle Helm Chart maintained by bitnami (link: https://github.com/bitnami/charts/tree/master/bitnami/moodle)

Given a working moodle installation,
When I try to add moodle language packs,
Then I should not be warned with this message:

```
Your server does not seem to fully support the following languages:
- Deutsch - Schweiz (de_ch)
- Deutsch (de)
- English (en)
- Français (fr)
- Italiano (it)
- 日本語 (ja)
```

Executing a shell in the moodle container and running dpkg-reconfigure locales, adding all locales, running locale-gen and setting a sensible default locale (probably en_US.UTF-8 should be good for general purpose, albeit making it configurable would be the best solution IMHO) solves the problem.

We should probably add a flag and configure the Dockerfile accordingly, to add all locales if needed on build time, or use another Docker base image.

**Steps to reproduce the issue:**

1. Run the moodle docker container
2. Add a another language (e.g. `fr_CH.UTF-8`)

**Describe the results you received:**

```
Your server does not seem to fully support the following languages:
- Français (fr)
```

**Describe the results you expected:**

No message shown, the new language is fully supported.

**Additional information you deem important (e.g. issue happens only occasionally):**

I've made some change already and will join a PR asap.
I want to have an issue so we can reference an issue number if necessarry.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 93
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: MK56:KT7H:DYSF:ABHR:AY42:BBW3:Z2XZ:MG2I:MIJD:V2E6:ZQA3:KPN7
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 48
  Goroutines: 66
  System Time: 2020-05-26T11:09:52.4501086Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Originally, I had this issue on my Rancher cluster.

**Comment by soriyath** [comment]
https://github.com/bitnami/bitnami-docker-moodle/issues/123 solves this issue

**Comment by andresbono** [comment]
Thanks for moving the issue to this repository. We will evaluate the suggested approach and will review the PR shortly.

**Comment by soriyath** [comment]
I can try and do the work needed on the Helm side of things, if needed.

**Comment by andresbono** [comment]
Thanks for offering you help, @soriyath. Let's first agree on the approach on the container.

**Comment by andresbono** [comment]
Removing the stale tag, #123 is under review.
