### ISSUE TITLE
moodle not working

### ISSUE THREAD

**Issue by michelcameroon** [bitnami/bitnami-docker-moodle#126]
michel@ubu200401:~/dockermi/docker-compose/project/moodles$ docker-compose up -d
Creating network "moodles_default" with the default driver

**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi @michelcameroon ,
  Could you give more info about this issue ? 
  I would be useful if you can send the error, steps to reproduce the issue, container logs, etc.

**Comment by marcosbc** [comment]
Closing in favor of #128
