### ISSUE TITLE
mistake in the image bitnami-docker-moodle 

### ISSUE THREAD

**Issue by michelcameroon** [bitnami/bitnami-docker-moodle#128]
michel@ubu200401:~/dockermi/docker-compose/project/moodles$ docker-compose up -d
Creating network "moodles_default" with the default driver
... 
no problem until 
...

Creating moodles_moodle_1  ... 

ERROR: for moodles_moodle_1  a bytes-like object is required, not 'str'

ERROR: for moodle  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/0835d7205ee60ae3fab101814a5a8545ac5fecb884232388085fead7e4aeb599/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wra

work with ubuntu 20.04 docker version
michel@ubu200401:~/dockermi/docker-compose/project$ docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        

michel@ubu200401:~/dockermi/docker-compose/project$ docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-moodle/master/docker-compose.yml > docker-compose.yml

docker-compose up -d

**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:
Client:
 Debug Mode: false

Server:
 Containers: 37
  Running: 1
  Paused: 0
  Stopped: 36
 Images: 65
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-39-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.66GiB
 Name: ubu200401
 ID: QMAK:E42Q:6V3A:6POF:5V4Z:GLA5:5AAC:P7JN:Y7VX:EBG3:PYRS:FMAW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  localhost:32000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi, 

I was unable to reproduce the issue

```
❯ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
❯ docker-compose version
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

```
❯ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-moodle/master/docker-compose.yml > docker-compose.yml
❯ docker-compose  up -d
Creating network "dcom_default" with the default driver
Creating volume "dcom_mariadb_data" with local driver
Creating volume "dcom_moodle_data" with local driver
Creating dcom_mariadb_1 ... done
Creating dcom_moodle_1  ... done
```

Does the same issue happen with other docker-compose files?

**Comment by michelcameroon** [comment]
Thank you for the answers, it was going. We are in Cameroon and we are
doing docker and we will like you to help us since we do not really know
much about it so that we can be able to do bigger projects using docker.
The problem we have is that it can not work in two instances
We are a school in limbe Cameroon called the association of Linux friends.
Hoping to hear from you again

**Comment by javsalgar** [comment]
Hi,

Thank you for using our images to start learning Docker :) We will try to help with any issues you find when using our images. Make sure you post the exact steps to reproduce the issue so it is easier for us to spot the problem. Enjoy Docker! :)

**Comment by michelcameroon** [comment]
Hello,
We have continued with docker-compose and the bitnami/moodle is functioning
very good. We have done a docker with hypriot, because it is for lowpower
machine like raspberry and it has already docker installed. So we have done
a little project for administration of table in a mysql database. It works
very good so today we try to install bitnami/moodle and bitnami/dokuwiki, 2
software which we real use in our school. But it was not successful, the
image are there but when we
docker-compose up - d
It gives no mistake but it we type docker ps no container appear. May the
raspberry pi 0 is to weak? I try to find the log but i don't find where is
the log of docker? In /var/log i found nothing. We will try with raspberry
pi 3.

Buf now we are already happy to have a moodle machine with docker-compose
which works on a laptop, buf now we want that the whole class can use and
enjoy it and we work in the subnet 192.168.1.0 and our docker machine has
an 172.24.0.3 ip. I try and succed to put an ip (192.168.1.191) on the
bitnami moodle machine and i can work on it, it is on the same physical
machine, BUT when i try from another machine in the subnet 192.168. 1.0, i
cannot reach 192.168.1.191, i cannot ping and and browse on this address

here my docker-compose.yml file in attach

so what wrong, i have seen when i go with exec on this moodle machine, i
dont find any /etc/network/interfaces, i found only my 192.168.1.219 in the
hosts file.

what we must do to reach our moodle in school subnet 192,168.1.0?

hoping to rad you soon

michel

**Comment by javsalgar** [comment]
Hi,

What I would do in your case is to do some port-forwarding so port 80 of the physical machine maps to the port 80 of the container. Did you try that?

**Comment by michelcameroon** [comment]
Hello, yes we have try it and it works. So thanks a lot, now will install
it in our school intranet.


But we want to go forward and would like to understand,


We work with rapberry and we have install hypriot (docker is already
installed) on raspberry pi 0 install docker-compose and we have done a
projekt, similar to moodle (php machine and MySQL machine) and it works.
But when i do with the same docker-compose.yml as on my labtop, it do it
without mistake, but when i control if my machinrs are working nothing no
container, may the raspberry pi 0 is to weak to do it.

We will test it in pi 3 and if you are interested we send the result.

Why raspberyy? We want to introduce computer technology not only in us
europe but in africa and inside africa is a digital gap between town and
villages and we want that the villages have the possibility to use computer
especially in schools, but it exist no electricity, with 1 solar  panel we
can install 5 computers, raspberry pi 3 and lowvpower monitor (less than 20
watts per working places) and now we had to stop all projects in villages
because of the war. War destroy many things but not our dreams.




Anyway we want to go forward and our next goal is to use in kubernetes.

We have tried with microk8s
But we could not install bitnami/moodle
But
We could install with helm bitnami/dokuwiki. (we use dokuwiki in our
school)

But we have the same problem as with docker - compose, how to get an ip for
dokuwiki, so that all student have access in our 192.168.1.0 subnet?

As it was working so well with docker-compose and ports so i build a new
image with set ports=8000:80

We can install and it does not show us mistakes,  but

microk8s kubectl get pods

...

dokuwikiwithip3-f8f5479dc-mhmp8                                   0/1
Pending            0          18h

...

ok, as you see we are still trying, but it is hard

linux friends limbe
michel

**Comment by javsalgar** [comment]
Hi,

It seems to me that the raspberry pi you are using does not have the sufficient power for a Moodle installation. Let's see if with a RPi 3 it becomes better. About the K8s installation, if you are using one locally, the process becomes a bit more complex in terms of networking because of what you are experiencing. You could try taking a look at MetalLB, which could partially solve the networking issue.

**Comment by dani8art** [comment]
Hi @michelcameroon, any updates on this? did you try on top of `RPi 3`?

**Comment by michelcameroon** [comment]
Sorry, i am in hospital malaria

**Comment by javsalgar** [comment]
Hi,

Sorry to hear that, we sincerely hope that you recover soon. We will leave the ticket open.
