### ISSUE TITLE
Moodle Not working

### ISSUE THREAD

**Issue by EzyBakeOven** [bitnami/bitnami-docker-moodle#129]
**Description**

Tried a docker-compose on the docker-compose file in the project. Everything starts up. But when I try 0.0.0.0:80/ Firefox cannot connect, it says "The connection to the server was reset while the page was loading.". Checked the logs.

[ssl:warn] [pid 72] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
AH00163: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.3.19 configured -- resuming normal operations
AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'

**Steps to reproduce the issue:**

1.$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-moodle/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by EzyBakeOven** [comment]
I figured out what you need to change in your compose file. Happy to submit a PR

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the input! Could you provide more details about what needed to be changed?

**Comment by sennewood** [comment]
We have the same error. What did you change?
