### ISSUE TITLE
Container fails to restart: bash: /bin/rm: Argument list too long

### ISSUE THREAD

**Issue by yelhouti** [bitnami/bitnami-docker-moodle#136]
**Description**

**Steps to reproduce the issue:**

1. helm install
2. kubectl delete pod moodle-...
3. kubectl logs -f moodle-...

**Describe the results you received:**

logs contains the following error:
```
bash: /bin/rm: Argument list too long
```

**Describe the results you expected:**

pod should restart without a problem

**Additional information you deem important (e.g. issue happens only occasionally):**

After checking the code the culprit is the `*` at the end of line:
https://github.com/bitnami/bitnami-docker-moodle/blob/7f264055c7f16637ba9e439ca385c54a02eb5483/3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh#L170

I really don't understand how I am the first noticing this quiet old bug...

**Comment by carrodher** [comment]
Hi, thanks for reporting this issue. I was not able to reproduce it because the `sessions` folders need to contain a very huge number of subitems to reach the limit (and the error). 
I just created the following PR using a different way to remove the items inside that folder
