### ISSUE TITLE
Can't custom image

### ISSUE THREAD

**Issue by lyhovseab** [bitnami/bitnami-docker-moodle#144]
Hi all, I need your help. After I customized the image I got the message below:

moodle 01:23:47.07 Welcome to the Bitnami moodle container
moodle 01:23:47.08 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle 01:23:47.09 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle 01:23:47.09 
moodle 01:23:47.10 INFO  ==> ** Starting Moodle setup **
moodle 01:23:47.18 INFO  ==> Configuring PHP options
moodle 01:23:47.21 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle 01:23:47.54 INFO  ==> Restoring persisted Moodle installation
moodle 01:23:56.66 INFO  ==> Trying to connect to the database server
grep: /opt/bitnami/moodle/config.php: No such file or directory
Terminal will be reused by tasks, press any key to close it.

I have tested many time by just added a plugin or just a new file. It always show that, but in version 3.8 it's fine.
Thanks!

**Comment by andresbono** [comment]
Hi @lyhovseab, thanks for opening this issue. Can you share with us the Dockerfile that you are using to customize this image? That will help us to understand and reproduce the issue.

**Comment by lyhovseab** [comment]
Thanks @andresbono  for your responding. This is my Dockerfile.


FROM bitnami/moodle:3.8.3
#Modify contents
COPY moodle/ /bitnami/moodle/
COPY config/plugins/ /bitnami/moodle/auth/
RUN apt-get update \
 && apt-get install vim -y \
 && apt-get install nano -y

**Comment by andresbono** [comment]
Thanks, @lyhovseab. Does the directory that you are copying (`COPY moodle/ /bitnami/moodle`) contain the `config.php` file? Are you using the docker-compose to run the containers? The directory `/bitnami/moodle` is supposed to be used as a volume:

https://github.com/bitnami/bitnami-docker-moodle/blob/8968bb13373029fa2814f3c89dabd355674246fb/3/debian-10/docker-compose.yml#L22-L24

You might be facing some issues due to that.

**Comment by lyhovseab** [comment]
@andresbono No, but I have tested by copy config.php from the old version but it still error.

**Comment by andresbono** [comment]
Hi @lyhovseab, we tried to reproduce the issue but we couldn't. If the config.php exists, we don't get the error message `grep: /opt/bitnami/moodle/config.php: No such file or directory`. These are the steps we followed to force the error:

- Run docker-compose with `bitnami/moodle:3.8.3` and mounting the volume in a local directory `./moodle`.
- Stop docker-compose (`docker-compose down`).
- Move the `config.php` file so it can't be found. `sudo mv moodle/config.php moodle/config.php.bak`
- Run docker-compose again with latest container image: 

```diff
@@ -9,7 +9,7 @@ services:
     volumes:
       - 'mariadb_data:/bitnami/mariadb'
   moodle:
-    image: 'docker.io/bitnami/moodle:3-debian-10'
+    image: 'docker.io/bitnami/moodle:3.9.2-debian-10-r31'
     ports:
       - '80:8080'
       - '443:8443'
@@ -20,7 +20,7 @@ services:
       - MOODLE_DATABASE_NAME=bitnami_moodle
       - ALLOW_EMPTY_PASSWORD=yes
     volumes:
-      - 'moodle_data:/bitnami/moodle'
+      - './moodle:/bitnami/moodle'
       - 'moodledata_data:/bitnami/moodledata'
     depends_on:
       - mariadb
```

```console
$ docker-compose up -d
$ docker-compose logs -f moodle
Attaching to bitnami-docker-moodle_moodle_1
moodle_1   | moodle 10:35:51.68
moodle_1   | moodle 10:35:51.69 Welcome to the Bitnami moodle container
moodle_1   | moodle 10:35:51.69 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle_1   | moodle 10:35:51.69 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle_1   | moodle 10:35:51.69
moodle_1   | moodle 10:35:51.69 INFO  ==> ** Starting Moodle setup **
moodle_1   | moodle 10:35:51.80 INFO  ==> Configuring PHP options
moodle_1   | moodle 10:35:51.81 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle_1   | moodle 10:35:51.84 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
moodle_1   | moodle 10:35:51.91 INFO  ==> Restoring persisted Moodle installation
moodle_1   | moodle 10:35:56.38 INFO  ==> Trying to connect to the database server
moodle_1   | grep: /opt/bitnami/moodle/config.php: No such file or directory
bitnami-docker-moodle_moodle_1 exited with code 2
```

Please make sure your `config.php` file exists. Also note that the customizations you are doing in `/bitnami/moodle` are not expected. The directory `/bitnami/moodle` is supposed to be used as a volume.

**Comment by lyhovseab** [comment]
Thanks @andresbono for your work. I got this information from the official moodle website (_The name for Moodle's configuration file is config.php. The file is located in the moodle directory. It is not included in the Moodle download packages and is created by the installation process from the template file config-dist.php (which is included in Moodle packages)._)

**Comment by lyhovseab** [comment]
Hi @andresbono Or you can just add a new test file and start it from scratch, you will get the error as me.

This is my Dockerfile:

_FROM bitnami/moodle:3.9.2-debian-10-r31
COPY test.txt /bitnami/moodle/test.txt_

This is my compose file:

version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    container_name: moodle-db-bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - 'mariadb_data-bi:/bitnami/mariadb'
  moodle:
    image: 'bitnami/moodle:3.9.2-debian-10-r31-5-20201016'
    container_name: moodle-bitnami
    ports:
      - '880:8080'
      - '843:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data-bi:/bitnami/moodle'
      - 'moodledata_data-bi:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data-bi:
    driver: local
  moodle_data-bi:
    driver: local
  moodledata_data-bi:
    driver: local

**Comment by andresbono** [comment]
Hi @lyhovseab, I think I understood the issue now.

If you want to customize the image, you should place your files in `/opt/bitnami/moodle` instead of `/bitnami/moodle`. See the following commands:

```console
$ docker run --rm -it --entrypoint ls bitnami/moodle:3.9.2-debian-10-r31 /bitnami/moodle
$ docker run --rm -it --entrypoint ls bitnami/moodle:3.9.2-debian-10-r31 /opt/bitnami/moodle
admin				      index.php
analytics			      install
auth				      install.php
...
```

Before you run the container, the `/bitnami/moodle` is empty. The files are moved from `/opt/bitnami/moodle` to there after initializing the container to persist the data of the application.

I would also recommend you that you let the Moodle installer create the configuration file for you. You can use many environment-variables to specify different values:

https://github.com/bitnami/bitnami-docker-moodle/blob/d97d52183603e6d465abb6a6d9de0f4d10c7ce65/3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh#L110-L113

---

Another topic is that you also want to upgrade Moodle (from 3.8 to latest) using existing database form the old version. Is that correct? Moodle is very particular and automatic upgrades are not allowed, see the note in [Upgrade this image](https://github.com/bitnami/bitnami-docker-moodle#user-content-upgrade-this-image).

You may want to use the `MOODLE_SKIP_BOOTSTRAP` environment-variable so that the database is not re-initialized and you can do the manual steps that you consider to perform the upgrade.

**Comment by lyhovseab** [comment]
@andresbono Thanks you so much! For your help. Now I can add my custom to it, but I got the new issue is can not change it to run as root user instead of daemon user. I've added "USER root" in Dockerfile and also added "user : root" in docker-compose file.
Could you please help me again? Thanks!

**Comment by andresbono** [comment]
Can you share the error message that you are getting? Note that the Moodle container is already running as root:

https://github.com/bitnami/bitnami-docker-moodle/blob/8720dead68ef929c00150b03d3eac687a0271114/3/debian-10/Dockerfile#L61
