### ISSUE TITLE
Docker command line not working

### ISSUE THREAD

**Issue by xziten** [bitnami/bitnami-docker-moodle#151]
**Description**

The docker command line tutorial proposed in the README is not working. Container is closed with this message 

**ERROR ==> Could not connect to the database**

**Steps to reproduce the issue:**

1. Copy/Paste the command lines from the README.MD part : Using the Docker Command Line
2. That's it

**Describe the results you received:**

> moodle 17:02:27.53 
> moodle 17:02:27.53 Welcome to the Bitnami moodle container
> moodle 17:02:27.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
> moodle 17:02:27.53 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
> moodle 17:02:27.53 
> moodle 17:02:27.54 INFO  ==> ** Starting Moodle setup **
> moodle 17:02:27.59 INFO  ==> Configuring PHP options
> moodle 17:02:27.59 INFO  ==> Setting PHP expose_php option
> moodle 17:02:27.70 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
> moodle 17:02:27.72 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
> moodle 17:02:27.76 INFO  ==> Ensuring Moodle directories exist
> moodle 17:02:27.77 INFO  ==> Trying to connect to the database server
> moodle 17:03:27.96 ERROR ==> Could not connect to the database

**Describe the results you expected:**

Expected to work

**Additional information you deem important (e.g. issue happens only occasionally):**
No 

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
```

**Comment by andresbono** [comment]
Hi @xziten, did you execute all the 3 steps listed in the section? https://github.com/bitnami/bitnami-docker-moodle#using-the-docker-command-line

Can you check if the `mariadb` container is up and running?
