### ISSUE TITLE
Migration: volume confusion

### ISSUE THREAD

**Issue by stefangweichinger** [bitnami/bitnami-docker-moodle#158]
I am trying to migrate a moodle instance to a docker stack and I am confused by the volumes in 

https://github.com/bitnami/bitnami-docker-moodle/blob/master/docker-compose.yml

There are *two* volumes mounted:

```
volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
```

What for? Do I need both?

In the old installation I have this in `config.php`:

```
$CFG->dataroot  = '/var/www/moodledata';
```

And I try to rsync that over into the correct place and fail with permission issues, although I chowned to "www-data:www-data", etc

I am confused and ask for advice, thanks!

**Comment by stefangweichinger** [comment]
Had to `chown -R daemon:daemon` on the host.
And the 2 volumes seem to be app-code, and content like files, afai understand.
Looks good already, but thanks for any additional information or feedback.

**Comment by andresbono** [comment]
> And the 2 volumes seem to be app-code, and content like files, afai understand.

That's correct, @stefangweichinger.

We are going to close the issue, but please let us know if you need other clarifications

**Comment by 7thred** [comment]
i dont understand how to migrate volume moodle in docker?

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution).

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
