### ISSUE TITLE
Not working after last update r43

### ISSUE THREAD

**Issue by sudanking** [bitnami/bitnami-docker-moodle#162]
I get an error message after update to r43. 

`Invalid permissions detected when trying to create a directory. Turn debugging on for further details.`

I revert back to r42 and it is working fine.

**Comment by sudanking** [comment]
I think it is some other reason for that error... I will try to figure it out.

**Comment by rafariossaa** [comment]
Hi,
  I am happy you were able to figure it out. In any case don't hesitate to come back and share your finding or your issues.
