### ISSUE TITLE
Using Nginx instead of Apache

### ISSUE THREAD

**Issue by CartierPierre** [bitnami/bitnami-docker-moodle#165]
Hi,
I'm just questioning myself about using Nginx instead of Apache serving https moodle php app. Is it possible to change the web service using this image or I have to fork this to create my own image ?
Thanks

**Comment by miguelaeh** [comment]
Hi @CartierPierre ,
I am afraid you will need to create your own image to change it. If you plan to do it I recommend you to check our `libwebserver.sh` library.

**Comment by CartierPierre** [comment]
By the way, this is no sense to use Nginx instead of Apache now, because Apache can be switched to event oriented architecture et there is tons of documentation of moodle using Apache. I'm closing this one
