### ISSUE TITLE
Install MoodleLMS in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/bitnami-docker-moodle#167]
## Pre-requisites

You must have an account created in IBM Cloud. The account needs to either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/105726477-20324d80-5ef8-11eb-8624-08efb6cd94db.PNG)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/105726509-27595b80-5ef8-11eb-9b9c-997669567928.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short in resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/105726540-2de7d300-5ef8-11eb-940b-2405129ba92e.PNG)

* Select the number of workers in Worker Pool.
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/105726568-3213f080-5ef8-11eb-8aef-cc9386e54ba9.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/105726590-37713b00-5ef8-11eb-8a9f-46058539347e.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/105726608-3c35ef00-5ef8-11eb-8b5b-450a6acb5701.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/105726625-422bd000-5ef8-11eb-90f6-3fefac6d704e.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![Storage1](https://user-images.githubusercontent.com/70336951/105726656-4bb53800-5ef8-11eb-9865-d8afa510c4c5.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _storage-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/105726685-5243af80-5ef8-11eb-8d26-cb7cdc5f08ec.PNG)

## Step 3: Install Moodle(TM) LMS

* Click on the search section at the top of the main page, type Moodle(TM) LMS, and click on it.

![moodle1](https://user-images.githubusercontent.com/70336951/105726731-5f609e80-5ef8-11eb-986d-e50839519b2f.PNG)

*  A new window opens, select the cluster and put the name you want to the workspace, in this case it will be called _moodle-example_; then, go to the bottom to find the workspace parameters.
  You can modify the different installation parameters at the bottom. We will leave them by default except for the credentials Moodle uses for its database and its application. You will need the first to access your database console and the second one to access your new Moodle application. You can read more about setting up the parameters [here](https://cloud.ibm.com/catalog/content/moodle#about "here").

Make sure you set up correctly the email and password for the application in the _moodleEmail_ and _moodlePassword_ variables.

![parameters2](https://user-images.githubusercontent.com/70336951/105726786-71dad800-5ef8-11eb-8c57-9788738de951.PNG)

![parameters1](https://user-images.githubusercontent.com/70336951/105726755-67204300-5ef8-11eb-807c-5117899f4c86.PNG)

  You can also set up a new database user in the mariadb.auth.username variable. Don't forget to set the password for that user in the mariadb.auth.password variable. The admin user will be root by default, and you can change its password in the mariadb.auth.rootPassword.
  
![parameters3](https://user-images.githubusercontent.com/70336951/105726829-7a331300-5ef8-11eb-8cc0-f8024094b220.PNG)

![parameters4](https://user-images.githubusercontent.com/70336951/105726845-7d2e0380-5ef8-11eb-928d-29169d6d4750.PNG)

![parameters5](https://user-images.githubusercontent.com/70336951/105726880-83bc7b00-5ef8-11eb-91ac-4160743f3a87.PNG)

When you're done, accept the terms, and click on Install.

![moodle2](https://user-images.githubusercontent.com/70336951/105726971-98007800-5ef8-11eb-990a-67d7938d2f7e.PNG)

## Step 4: Verify Installation

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test1](https://user-images.githubusercontent.com/70336951/105727000-9e8eef80-5ef8-11eb-82c5-008c7a0d7912.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/105727026-a5b5fd80-5ef8-11eb-835a-3091337abee5.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/105727037-ab134800-5ef8-11eb-8412-c25822fe04a2.PNG)

![test7](https://user-images.githubusercontent.com/70336951/105727055-ae0e3880-5ef8-11eb-951b-c178f71e532a.PNG)

* Once you have installed the terminal, click on the action button again, select web terminal, and type the following command. It will show you the workspaces of your cluster. You can see *moodle_example* is now active.

`$ kubectl get ns`

![testmoodle1](https://user-images.githubusercontent.com/70336951/105727074-b49cb000-5ef8-11eb-95ec-728921260191.PNG)

* Check the namespace _moodle-example_ or the namespace you have specific in namespace, and make sure the pods are running.

`$ kubectl get pod -n NAMESERVICE -o wide`

![testmoodle2](https://user-images.githubusercontent.com/70336951/105727095-b8c8cd80-5ef8-11eb-9780-c2fbefe2a1ba.PNG)

`$ kubectl get service -n NAME SERVICE`

![testmoodle3](https://user-images.githubusercontent.com/70336951/105727115-bd8d8180-5ef8-11eb-9a28-d64e4e9d1747.PNG)

`$ kubectl exec --stdin --tty PODNAME -n NAMESPACE -- /bin/bash`

![testmoodle4](https://user-images.githubusercontent.com/70336951/105727127-c1210880-5ef8-11eb-8261-676ff0110823.PNG)

You have finished the installation and enjoy your new Moodle site by accessing the load balancer's public IP. It is important to note that the VPC selected in the Kubernetes Cluster created should have an Internet Gateway to correctly access the IP. You can also assign a custom domain by modifying the corresponding variable in the Moodle installation parameters.

**Comment by carrodher** [comment]
Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as “Closed” so it can be used by other users looking for information as if it were documentation
