### ISSUE TITLE
Changing of base url path

### ISSUE THREAD

**Issue by skyfox675** [bitnami/bitnami-docker-moodle#169]
**Description**

Suggested way of changing the base url path from "/" to "/moodle" while not introducing breaking changes if possible.
Example: `https://example.com/` -> `https://example.com/moodle/`

**Additional information you deem important (e.g. issue happens only occasionally):**

Curious if this can be done via sed in the Dockerfile, or if one of the vhost templates should be modified. 

**Version**
```
Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Thanks!
-Skyfox675

**Comment by rafariossaa** [comment]
Hi,
  Could you provide more information in the use case for this ?.

**Comment by skyfox675** [comment]
> Hi,
> Could you provide more information in the use case for this ?.

In my case Moodle will be residing behind a server with other applications where the "/" path is already in use.

**Comment by rafariossaa** [comment]
I think you can try by updating the apache configuration and also the moodle config file and set the path you need.
You can execute your own scripts by mounting `/docker-entrypoint-init.d` and putting there the shell scripts you need.
This will be executed right after the setup and before the start as you can see [here](https://github.com/bitnami/bitnami-docker-moodle/blob/bb2cd6c412b3d9c13c3841cd04b3d44aed888b16/3/debian-10/rootfs/opt/bitnami/scripts/moodle/entrypoint.sh#L26)

**Comment by skyfox675** [comment]
Awesome thank you! I was able to script in adding an httpd Alias to the vhost configs and Apache is routing to moodle's base htdocs directory correctly. Here's my below code for any others looking to do the same:
libmoodle.sh:
```
moodle_configure_wwwroot() {
    local -r http_port="${WEB_SERVER_HTTP_PORT_NUMBER:-"$WEB_SERVER_DEFAULT_HTTP_PORT_NUMBER"}"
    local -r url_path="'${MOODLE_WEBSERVER_PATH}'"
    # sed replacement notes:
    # - The ampersand ('&') is escaped due to sed replacing any non-escaped ampersand characters with the matched string
    # - For the replacement text to be multi-line, an \ needs to be specified to escape the newline character
    local -r conf_to_replace="if (empty(\$_SERVER['HTTP_HOST'])) {\\
  \$_SERVER['HTTP_HOST'] = '127.0.0.1:${http_port}' . ${url_path};\\
}\\
if (isset(\$_SERVER['HTTPS']) \&\& \$_SERVER['HTTPS'] == 'on') {\\
  \$CFG->wwwroot   = 'https://' . \$_SERVER['HTTP_HOST'] . ${url_path};\\
} else {\\
  \$CFG->wwwroot   = 'http://' . \$_SERVER['HTTP_HOST'] . ${url_path};\\
}"
    replace_in_file "$MOODLE_CONF_FILE" "\\\$CFG->wwwroot\s*=.*" "$conf_to_replace"
}
```
deployment.yaml:
```
            - name: MOODLE_WEBSERVER_PATH
              value: "/learn"
```
moodle-env.sh:
```
export MOODLE_WEBSERVER_PATH="${MOODLE_WEBSERVER_PATH:-}" # Custom to add support for changing of Moodle URL path, setting externally via Dockerfile
```

add-httpd-alias.sh (new file):
```
#!/bin/bash
if [[ $MOODLE_WEBSERVER_PATH != "" ]]; then
    if [[ $(cat '/opt/bitnami/apache/conf/vhosts/moodle-vhost.conf' | grep '  Alias' | wc -l) == 0 ]]; then
        echo "Creating filesystem path '$MOODLE_WEBSERVER_PATH'"
        mkdir -p "/opt/bitnami/moodle$MOODLE_WEBSERVER_PATH"
        echo "Setting permissions for '$MOODLE_WEBSERVER_PATH'"
        chmod 777 "/opt/bitnami/moodle$MOODLE_WEBSERVER_PATH"
        echo "Adding alias to moodle-vhost.conf"
        line=$(cat '/opt/bitnami/apache/conf/vhosts/moodle-vhost.conf' | grep -n 'DocumentRoot' | grep -o '^[0-9]*')
        line=$((line + 1))
        sed -i ${line}"i\  Alias ${MOODLE_WEBSERVER_PATH} /opt/bitnami/moodle" '/opt/bitnami/apache/conf/vhosts/moodle-vhost.conf'
    else
        echo "HTTP Alias already exists, skipping"
    fi
    if [[ $(cat '/opt/bitnami/apache/conf/vhosts/moodle-https-vhost.conf' | grep '  Alias' | wc -l) == 0 ]]; then
        echo "Adding alias to moodle-https-vhost.conf"
        line=$(cat '/opt/bitnami/apache/conf/vhosts/moodle-https-vhost.conf' | grep -n 'DocumentRoot' | grep -o '^[0-9]*')
        line=$((line + 1))
        sed -i ${line}"i\  Alias ${MOODLE_WEBSERVER_PATH} /opt/bitnami/moodle" '/opt/bitnami/apache/conf/vhosts/moodle-https-vhost.conf'
        echo "Finished adding alias"
    else
        echo "HTTPS Alias already exists, skipping"
    fi
fi
```
entrypoint.sh:
```
if [[ "$1" = "/opt/bitnami/scripts/moodle/run.sh" || "$1" = "/opt/bitnami/scripts/$(web_server_type)/run.sh" || "$1" = "/opt/bitnami/scripts/nginx-php-fpm/run.sh" ]]; then
    info "** Starting Moodle setup **"
    /opt/bitnami/scripts/"$(web_server_type)"/setup.sh
    /opt/bitnami/scripts/php/setup.sh
    /opt/bitnami/scripts/mysql-client/setup.sh
    /opt/bitnami/scripts/moodle/setup.sh
    /opt/bitnami/scripts/add-httpd-alias.sh # Custom and added to change URL path
    /post-init.sh
    info "** Moodle setup finished! **"
fi
```

**Comment by voggun** [comment]
@skyfox675: thank you for your solution, unfortunately this solution does not work properly (on my side) . In which folder was the "cratefile.sh" placed?

**Comment by rafariossaa** [comment]
Hi,
  Thanks for sharing.

**Comment by MaxiMii05** [comment]
I can confirm these modifications works.

By using the MOODLE_HOST environment variable that is available by now, you only need the modifications for:
moodle-env.sh
add-httpd-alias.sh
entrypoint.sh
My Dockerfile then looks like this:
``` 
FROM bitnami/moodle:3

COPY add-httpd-alias.sh /opt/bitnami/scripts/add-httpd-alias.sh
COPY entrypoint.sh /opt/bitnami/scripts/moodle/entrypoint.sh
RUN echo "export MOODLE_WEBSERVER_PATH="/moodle"" | tee -a /opt/bitnami/scripts/moodle-env.sh
```

It is really frustrating that this is not the default behaviour when a custom MOODLE_HOST is set that includes a subdirectory.
I would love for the devs to include this in the standard docker image so that using Moodle in a subdirectory behind a reverse proxy (or not) is as easy as defining a single environment variable. Should I open a new issue for this?

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution).

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
