### ISSUE TITLE
Moodle - AWS - Technical issue - Secure Connections (SSL/HTTPS)

### ISSUE THREAD

**Issue by giliomeejg** [bitnami/bitnami-docker-moodle#171]
I'm experiencing an issue where LTI does not authenticate properly (oath), due to what seems to be the host receiving a request on port 443 and sending it to the docker container on port 8443.

The error one receives, when connecting from a consumer to a provider is: "An error occurred when launching the external tool:Sorry, there was an error connecting you to the application."

This was a relatively easy fix, by just changing the ports to 443:443, instead of the default 443:8443.

Thought I'd share incase anyone else is experiencing the same issue.

**Comment by marcosbc** [comment]
Hi @giliomeejg, thanks for sharing. I understand you're referring to configuration for LTI, right? Not Moodle configuration.

If this happens to be an actual bug in the Docker image or the compose file, please let us know to investigate further.

**Comment by giliomeejg** [comment]
Partly, here's how to recreate it:

Setup consumer.yourdomain.com and provider.yourdomain.com, both using a bitnami docker image, and both with SSL.

Setup and publish a course in the provider.

Setup a course in the consumer and pull in content from the provider.

It appears that the user isn't properly authenticated.  Changing the docker setup to run 443:443, as apposed to 443:8443 appears to solve the issue.

**Comment by marcosbc** [comment]
> It appears that the user isn't properly authenticated. Changing the docker setup to run 443:443, as apposed to 443:8443 appears to solve the issue.

But do you mean changing the below line in `docker-compose.yml`?

```yaml
    ports:
      - '80:8080'
      - '443:8443'
```

To this:

```
    ports:
      - '80:8080'
      - '443:443'
```

(which should not be needed since the Apache server is suposed to run on ports 8080/8443)

Or do you mean in another configuration file?

**Comment by giliomeejg** [comment]
Correct @marcosbc - I stand under correction, but think that the oath signature might somehow be tied to the port for which the request is intended.  

So the Moodle server side logic validates expecting port 443, but the request arrives on port 8443 within the container.

The site loads fine, and this particular issue is seen only when making an LTI request from the consumer to the provider.

**Comment by marcosbc** [comment]
We have seen issues with the Apache server not properly detecting the port before, and making a redirection that it shouldn't.

If you continue finding issues in that aspect, you could always try and change the HTTP and HTTPS ports to 80/443 respectively (via environment variables), run the Moodle container as a root user (via `user: root` in `docker-compose.yml`) and fix the mapping for both HTTP and HTTPS ports.
