### ISSUE TITLE
Tweaking the frequency that cron.php runs at

### ISSUE THREAD

**Issue by giliomeejg** [bitnami/bitnami-docker-moodle#173]
Is it possible to tweak the frequency at which cron.php runs to change it from say running every minute, to running every 5 minutes?

In lower end servers, this could save valuable resources, and would be super useful to tweak as an environment variable.

**Comment by andresbono** [comment]
Hi @giliomeejg, right now, that's not possible, see the following code where the schedule is hardcoded:

https://github.com/bitnami/bitnami-docker-moodle/blob/c0b5684ddbb55ff573d653e5ed63244b5ebd62ac/3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh#L197

Would you like to open a PR making the schedule customizable through an environment variable? Contributions are more than welcome! 😄

**Comment by netdreamer** [comment]
I think it's more than a feature request: I'm observing serious issue when cron process takes more than 1 minute to complete. 
In one of our setup it takes a lot of time (more than 1 minute) in the Moodle adhoc task: core\task\build_installed_themes_task.
So, all the cron executions stack up in the waiting queue, bringing down the server resources...

**Comment by giliomeejg** [comment]
> Hi @giliomeejg, right now, that's not possible, see the following code where the schedule is hardcoded:
> 
> https://github.com/bitnami/bitnami-docker-moodle/blob/c0b5684ddbb55ff573d653e5ed63244b5ebd62ac/3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh#L197
> 
> Would you like to open a PR making the schedule customizable through an environment variable? Contributions are more than welcome! 😄

PR available here:  [](https://github.com/bitnami/bitnami-docker-moodle/pull/174)

**Comment by andresbono** [comment]
Thanks so much for your contribution!! The PR is now merged and the new image shipping the changes will be available soon.

**Comment by netdreamer** [comment]
Thanks @giliomeejg for your work on #174 , but... I found a different use case: multiple moodle instances load balanced. 
It works perfectly, but Cron is run concurrently on all the instances, again creating run conditions (or multiple unuseful executions).

So, what do you think about making it more configurable like this:

`if [ ${MOODLE_CRON_MINUTES} -gt 0 ]; then generate_cron_conf "moodle" "${cron_cmd[*]} > /dev/null 2>> ${MOODLE_DATA_DIR}/moodle-cron.log" --run-as "$WEB_SERVER_DAEMON_USER" --schedule "*/${MOODLE_CRON_MINUTES} * * * *"`

You then have the ability to set MOODLE_CRON_MINUTES to 0, disabling completely the CRON inside the Moodle container (crontab line is not created at all). Now we are able to use an standalone cron container that mounts the same codebase (or an external cron webservice, if enabled in your moodle setup) that manages the executions from a single, manageable point.

(Sorry, I'm not able to provide a PR by myself...)

**Comment by netdreamer** [comment]
I made the changes in PR #175, documenting also the parameter in the README

**Comment by andresbono** [comment]
Thank you for your contribution, @netdreamer!! I think what you are proposing makes sense. A colleague will review #175 soon.
