### ISSUE TITLE
JS Bug Fading away menu on 3.9.2 latest Image

### ISSUE THREAD

**Issue by manfredsteger** [bitnami/bitnami-docker-moodle#176]
Hi there, we encounter a problem since Moodle / Snap Version 3.8.3 / 3.8.6 and 3.9.2 with according snap theme (latest) installed. We use Bitnami Moodle Images to deploy Moodle on our Kubernetes Cluster on Ubuntu 2020 (https://github.com/bitnami/bitnami-docker-moodle/search?q=3.9.2-debian-10-r47&type=commits).

We have a couple of free/open courses with auto guest login enabled on moodle backend. If you click on a free course and after that action you want to login with the login button on the top menu, the dropdown menu appears and fades out immediately.

There is only one way to login if you go to the native moodle login page.

You can try it on our production setting in our OER Bookshelf: https://www.kurse.zmf.bayern/course/view.php?id=12

![snap-theme-guest-login-bug](https://user-images.githubusercontent.com/8418059/106850486-e1995180-66b4-11eb-94df-2670eded67de.gif)

The Snap Theme developer checked the running instance and said: " ... think it's a Bitnami Moodle Image bug". You can read the full post [here](https://github.com/open-lms-open-source/moodle-theme_snap/issues/195)

Dev Network Tab on Firefox said 303 with policy.php and first.js.

<img width="1423" alt="firefox-netword-tab-dev" src="https://user-images.githubusercontent.com/8418059/113244641-b480ae00-92b5-11eb-8072-a0262e52e301.png">

Is there a way to fix this problem in 3.9.2 Image? We hoped that the upgrade from 3.8.6 to 3.9.2 version fixed the bug but it's still there. Furthermore we can't upgrade to 3.10 because Snap Theme is approximately 3/4 year behind Moodle latest.

Many thanks for all great Bitnami Images, we use it a lot and recommend them in many ways.

**Comment by javsalgar** [comment]
Hi,

I've been checking and I don't see anything that may be causing a 303 return code. This is the Apache configuration

```
<VirtualHost 127.0.0.1:8080 _default_:8080>
  ServerAlias *
  DocumentRoot /opt/bitnami/moodle
  <Directory "/opt/bitnami/moodle">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
```

Are you using Ingress with the Moodle chart? Not sure if there could be an issue with any intermediate proxy.
