### ISSUE TITLE
Startup fails after upgrading database character set

### ISSUE THREAD

**Issue by Yann-J** [bitnami/bitnami-docker-moodle#177]
**Description**

After an initial installation using default settings from the [Moodle Chart](https://artifacthub.io/packages/helm/bitnami/moodle), which uses the ([pretty useless](https://mathiasbynens.be/notes/mysql-utf8mb4)...) `UTF8` characterset, I have upgraded my MariaDB database to `utf8mb4` by following the [Moodle guide](https://docs.moodle.org/310/en/MySQL_full_unicode_support).

The upgrade seems to proceed correctly, and I can see the updated character set and collation settings in the database and tables:

```
MariaDB [(none)]> show create database bitnami_moodle;
+----------------+-------------------------------------------------------------------------------------------------------+
| Database       | Create Database                                                                                       |
+----------------+-------------------------------------------------------------------------------------------------------+
| bitnami_moodle | CREATE DATABASE `bitnami_moodle` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */ |
+----------------+-------------------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)
```

However, after a restart of the Moodle container, the startup script crashes (exit code 1) after these lines:

```
moodle 07:36:00.23 Welcome to the Bitnami moodle container
moodle 07:36:00.23 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle 07:36:00.23 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle 07:36:00.24
moodle 07:36:00.24 INFO ==> ** Starting Moodle setup **
moodle 07:36:00.35 INFO ==> Configuring the HTTP port
moodle 07:36:00.43 INFO ==> Configuring the HTTPS port
moodle 07:36:00.54 INFO ==> Configuring PHP options
moodle 07:36:00.63 INFO ==> Validating settings in MYSQL_CLIENT_* env vars
moodle 07:36:00.93 INFO ==> Restoring persisted Moodle installation
moodle 07:36:05.18 INFO ==> Trying to connect to the database server
moodle 07:36:05.39 INFO ==> Running database upgrade
```

I have tried a number of things, including:

* Setting `MYSQL_CLIENT_CREATE_DATABASE_CHARACTER_SET=utf8mb4` and `MYSQL_CLIENT_CREATE_DATABASE_COLLATE=utf8mb4_unicode_ci`
* `set -x`
* Manually running the database upgrade script at container startup (works fine):

```
$ php admin/cli/upgrade.php --non-interactive --allow-unstable
No upgrade needed for the installed version 3.10.2 (Build: 20210308) (2020110902). Thanks for coming anyway!
```

**Steps to reproduce the issue:**

1. Install a fresh Moodle+Mariadb instance using default settings (`helm install my-test bitnami/moodle`)
2. From the Moodle container, run the upgrade script: `cd /bitnami/moodle && php admin/cli/mysql_collation.php --collation=utf8mb4_unicode_ci`
3. Update the configuration: `sed -i 's/utf8_general_ci/utf8mb4_unicode_ci/' config.php`
4. Restart the Moodle pod

**Describe the results you received:**

Pod gets into a `CrashloopBackoff` after repeated terminations of the startup script, after `Running database upgrade`.

**Describe the results you expected:**

Full startup process

**Additional information you deem important (e.g. issue happens only occasionally):**

Notes:

* A fresh install using `utf8mb4` works fine.
* Moodle itslef seems to behave fine until the container is restarted (I could even save some emojis from the UI, showing the upgrade worked) so I believe the issue is not with Moodle but with one of the startup scripts.
* I see that the compose file was updated #163 - but not the chart yet..
* This happens both with and without updating the MariaDB system defaults in `my.cnf` to the following:

```
[mysqld]
skip-name-resolve
explicit_defaults_for_timestamp
basedir=/opt/bitnami/mariadb
plugin_dir=/opt/bitnami/mariadb/plugin
port=3306
socket=/opt/bitnami/mariadb/tmp/mysql.sock
tmpdir=/opt/bitnami/mariadb/tmp
max_allowed_packet=16M
bind-address=0.0.0.0
pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
log-error=/opt/bitnami/mariadb/logs/mysqld.log

character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
skip-character-set-client-handshake

[client]
port=3306
socket=/opt/bitnami/mariadb/tmp/mysql.sock
default-character-set = utf8mb4
plugin_dir=/opt/bitnami/mariadb/plugin

[manager]
port=3306
socket=/opt/bitnami/mariadb/tmp/mysql.sock
pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

[mysql]
default-character-set = utf8mb4
```

**Version**

* Container: `docker.io/bitnami/moodle:3.10.4-debian-10-r0`
* Chart: `11.0.6`

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

* AKS

**Comment by rafariossaa** [comment]
Hi @Yann-J ,
  Thank you for the very detailed description of the issue. The link for utf8mb4 is very interesting.
  The mariadb chart is used by several other assets and setting this by default can cause other undesired effects.  As workaround, maybe you can set the env vars of PR#163 using the `extraEnvVars` parameters for mariadb chart.
  Could you give it a try ?.

**Comment by Yann-J** [comment]
Yes, I confirm that this env var works indeed... but unfortunately only for a fresh installation.

My issue happens during the migration process of an existing db that was created using UTF8... I do think Moodle itself works fine after the upgrade, but its startup is held up by one of the bitnami startup scripts... At least that's what I suspect but I'm not able to troubleshoot those script very well...

**Comment by rafariossaa** [comment]
Hi, 
  You can also enable debug mode by using `image.debug=true`, that should bring out more information in the logs.

**Comment by dpmillerau** [comment]
I think I'm seeing a similar issue attempting to restore a database an existing database.

**Comment by dpmillerau** [comment]
Actually I have a DATAROOT config issue, but the image.debug=true helped - thanks

**Comment by rafariossaa** [comment]
You are welcome.
Don't hesitate to comeback.

**Comment by skandix** [comment]
I had this issue upgrading from 3.6 -> 3.11,  with docker and had to as well manually update  the dataroot path in config.php from 
 ```php 
$CFG->dataroot  = '/bitnami/moode/moodledata';
```

to 
 ```php 
$CFG->dataroot  = '/bitnami/moodledata';
```
And after that it worked flawlessly

**Comment by rafariossaa** [comment]
I am closing this issue. 
Please, don't hesitate to reopen it if needed or to create a new one.

**Comment by Yann-J** [comment]
For anyone stumbling across this, I just want to report that after an upgrade (I'm now running `bitnami/moodle:3.11.1-debian-10-r0`) this was somehow fixed.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for coming back and sharing your findings.
