### ISSUE TITLE
CAS issue, possible issue with reverseproxy on gcp

### ISSUE THREAD

**Issue by mgoh** [bitnami/bitnami-docker-moodle#180]
I am having trouble connecting my bitnami/moodle kubernetes stack on GCP with CAS. The instance is identifying itself as the backend url and appends the backend port :8443 which is causing problem with CAS authentication, this should be 443.

I believe that if i add cfg->reverseproxy=true might fix this issue according to this but i’m not sure where to implement this in the helm config if this is even the correct fix.

thanks!

**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi,
  I am sorry but nor the chart neither the container images allow to change easily that parameter, however I think you can use a init-script to do whatever you need.
  The container image allows init-scripts, these scripts are run after the setup [has been done](https://github.com/bitnami/bitnami-docker-moodle/blob/fdd2b3bc552ff96c10edd9fcbf0971b90eb3dfcd/3/debian-10/rootfs/opt/bitnami/scripts/moodle/entrypoint.sh#L26).
  You can write a script that change the parameter, and put it into the directory `/docker-entrypoint-init.d` in the moodle container. This way the script will be run after the setup has been done and before the service is started.

**Comment by mgoh** [comment]
thanks for the info!

i was able to get this working in another way but its good to know about `docker-entrypoint-init.d`
