### ISSUE TITLE
SELinux and /proc/self/fd

### ISSUE THREAD

**Issue by EarlRamirez** [bitnami/bitnami-docker-moodle#185]
**Description**

When running on Fedora 34 host I am getting permission denied for 
- /proc/self/fd/1 and 
- /proc/self/fd/2
**Steps to reproduce the issue:**

1. [First Step]
_sudo podman run -d --pod moodlepod --name moodle-app -e ALLOW_EMPTY_PASSWORD=yes -e MOODLE_DATABASE_USER=bn_moodle -e MOODLE_DATABASE_NAME=moodle \
 -e MOODLE_DATABASE_PASSWORD=moodlepass -e MOODLE_DATABASE_HOST=127.0.0.1 -e MOODLE_DATABASE_TYPE=mariadb \
 -v /var/www/html/moodle:/bitnami/moodle quay.io/bitnami/moodle:latest_

2. [Second Step]
3. [and so on...]

**Describe the results you received:**

The container exit with exit code 1, when I execute _sudo podman logs container_id_ I get the following output
moodle 13:22:13.22 
moodle 13:22:13.22 Welcome to the Bitnami moodle container
moodle 13:22:13.22 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle 13:22:13.22 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle 13:22:13.22 
moodle 13:22:13.23 INFO  ==> ** Starting Moodle setup **
chmod: changing permissions of '/proc/self/fd/1': Permission denied
chmod: changing permissions of '/proc/self/fd/2': Permission denied

**Describe the results you expected:**

The container starts as expected after SELinux mode is toggle from Enforcing to Permissive
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:
I am using podman version 3.2.3

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Fedora 34 CoreOS and Fedora 34 server

**Comment by juan131** [comment]
Hi @EarlRamirez 

Please note this is a non-root container by default, therefore privileged actions are restricted. Find more information in the link below:

- https://github.com/bitnami/bitnami-docker-moodle#why-use-a-non-root-container

You can simply overwrite the default user and run it as "root" if, for whatever reason, you need to run privileged actions.

**Comment by EarlRamirez** [comment]
@juan131 Thanks, I use many of Bitnami images and this is the only image that tries to write to the host /proc filesystem I only see this behaviour in the 3.10.0+ tag; however, I do not see this behaviour in 3.9.x.

**Comment by EarlRamirez** [comment]
@juan131, I clone the repository and replaced 'USER root` with `USER 1001` and I am able to run the container with SELinux enabled and no longer get any permission errors. If this is a root-less container why is root declared as the user before the entrypoint and cmd?

**Comment by beltran-rubo** [comment]
Hi @EarlRamirez sorry for the confusion, the moodle image is not a non-root image for now, we plan to move the pending ones to be non-root in the next months.

This is due to the stdout/stderr redirection. Please check this approach at https://github.com/bitnami/bitnami-docker-moodle/issues/153#issuecomment-822901006 and let us know if that works for you.

**Comment by EarlRamirez** [comment]
Thanks, @beltran-rubo I tried the approach from #153 and unfortunately, it did not work for me. However, I will continue using the image that was created after modifying the Dockerfile.

**Comment by juan131** [comment]
I was also confused by the README.md @EarlRamirez .. There's something we're going to fix by removing these references to non-root containers.

I've been checking with the team, and the reason to have it as "root" by default at this moment is that we can't configure the cron jobs properly when running as an unprivileged user, see:

- https://github.com/bitnami/bitnami-docker-moodle/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh#L207

**Comment by EarlRamirez** [comment]
@juan131 thanks for the details
