### ISSUE TITLE
Moodle not working with https domain

### ISSUE THREAD

**Issue by duongsieu** [bitnami/bitnami-docker-moodle#186]
I install moodle in server ubuntu 20.4 with file docker-composer.yml.
After installation i access to ip:port then website works normally.
But when i grant to the site https domain then website errors.
![image](https://user-images.githubusercontent.com/33409331/131293605-85e315c6-b6a0-43f6-b562-c222208e4eb3.png)
please help me!!!

**Comment by yilmi** [comment]
Hi @duongsieu,

I tried to reproduce your issue locally without any luck so far. 

However, this seems to be more a moodle problem than a container issue, could you try to purge all moodle caches (which include references to static content used for the theme such as css,....)

If you still have the issue, could you provide a step-by-step repro guidance?

Thanks,
Yass
