### ISSUE TITLE
Persistent storage on Azure 

### ISSUE THREAD

**Issue by lewid07** [bitnami/bitnami-docker-moodle#191]
**Description**

We're trying to deploy this image in an Azure Container Instance. The installation with an Azure Database for MySQL works perfectly fine and quick. We're in the need of some plugins (oidc and oauth2), that need to be stored persistently somewhere. The Idea was to use a File-Share from Azure, but this caused some problems as it was really slow and took about 30s to 2mins to load the website. This is caused by all the transactions on the storage account, which was at max 180k in 5 minutes, so Azure slows it down. 
Since we need at least some authentication plugins, we thought of just mounting that path persistently, which our guess is at `/bitnami/moodle/auth`. But this caused issues that moodle will not be initialized anymore as the `/bitnami/moodle` folder is not empty.

Is there a way to achieve this on Azure with persistence (maybe with another storage type, ...)?
Or does anybody have some other experiences/tips they can share with us, as we are kind of stuck here :)

**Steps to reproduce the issue:**

1. Deploy MySQL flexible Server on Azure and create an empty database for moodle
2. Create a storage account and fileshare on Azure
2. Deploy Image from DockerHub on Azure (https://hub.docker.com/r/bitnami/moodle)
with following json file: [template.txt](https://github.com/bitnami/bitnami-docker-moodle/files/7579371/template.txt)
3. Open page and wait :)
4. Look at the transactions on the storage account, which should be a lot

**Describe the results you received:**

Website is really slow (30s up to max. 5min)

**Describe the results you expected:**

Website is loading quickly

**Additional information you deem important (e.g. issue happens only occasionally):**

Container standalone is fast, the file-share slows it down a lot

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

- Azure Container Instance
- File Share on storage Account (Standard or SSD, ist both equally slow)
- Azure Database for MySQL flexible server

**Comment by marcosbc** [comment]
Hi @lewid07! Have you considered modifying the container image to include the files for the theme as a symlink? Then at runtime, you could mount the files at a different location (e.g. `/var/moodleplugin`, as long as the symlinks point to that folder).

If not, you could always play with the [`MOODLE_DATA_TO_PERSIST` environment variable](https://github.com/bitnami/bitnami-docker-moodle/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/moodle-env.sh#L75), although we would recommend to make sure to persist mostly everything in order to avoid issues with persisted data being lost after a restart. To specify multiple paths to persist, separate them with a space, but be aware that this will override any previous value (i.e. `$MOODLE_BASE_DIR` would not be persisted by anymore unless it is included in the list).

**Comment by lewid07** [comment]
@marcosbc Thank you for the quick answer. I have some further questions, as for the first option, so i would create a symlink for the `/bitnami/moodle/auth` folder to another location and mount a drive there, but then the folder still isn't empty so it would not install the rest of the moodle files, or am I misunderstanding this?

As for the second option, could you elaborate that a bit further? So would the value of the environment variable just have to be the path I want permanently stored, so eg. `MOODLE_DATA_TO_PERSIST=/bitnami/moodle/auth` ? But where does it store this, do I still need to mount a drive for permanent storage and/or link those together somehow?

**Comment by lewid07** [comment]
**UPDATE**:  We're trying to deploy the moodle container instance in an app service, as this would have persistent storage there as well so we'll see if that is faster than a file share once it works. 

I tried to set `$BITNAMI_VOLUME_DIR` to `/home/bitnami`, as the app service's default persistent storage path is `/home`.
After changing that and accessing the container via the provided bash option, there's only the default log-files in /home and nothing to be found from moodle, even in the whole container there's nothing showing except a regular empty container.

The weird thing is: I can still access moodle on that app service and it works just fine, but it's not stored anywhere on the container, that's pretty confusing. 
Nevertheless, nothing is persistent that way, the plugins don't exist anymore upon app restart.
Am I using the right variable?
Anybody got an idea where the whole moodle files are stored now?

The variables used this time:
<img src="https://user-images.githubusercontent.com/94437217/143402429-f5853e5a-aa62-4ef4-9d3e-5052839b43a1.png" width="350">

Content of `/home` after installation:
![image](https://user-images.githubusercontent.com/94437217/143403252-f0b42a9c-d275-48f9-9109-95a4a5443df7.png)

**Comment by marcosbc** [comment]
Unfortunately `BITNAMI_VOLUME_DIR` is not customizable. In order to change it, you will need to extend the container and modify it. You may also need to execute `/opt/bitnami/scripts/moodle/postunpack.sh` afterwards.
