### ISSUE TITLE
Base image question

### ISSUE THREAD

**Issue by avineer** [bitnami/bitnami-docker-moodle#193]
The docker.io/bitnami/minideb:buster base image has High-security vulnerabilities.
Can we switch the base image to Alpine instead? Would your codebase function seamlessly with this change?

Thank you for your prompt response.
Avi

**Comment by javsalgar** [comment]
Hi,

Could you check if the vulnerabilities shown have a fix from the upstream OS maintainers? We update the images every day so all the fixable CVEs are solved. About Alpine, we don't support this OS (there are several reasons for this, such as licensing for example), and the scripts would not work with the Alpine package manager.
