### ISSUE TITLE
$CFG->reverseproxy is not configurable

### ISSUE THREAD

**Issue by fatiiates** [bitnami/bitnami-docker-moodle#198]
**Description**

Although there is a `MOODLE_HOST` variable, we have to manually change the `$CFG->reverseproxy` variable to get it behind the load balancer.

**Steps to reproduce the issue:**

1. Set `MOODLE_HOST` variable
2. Create and configure Nginx container
3. You cannot access moodle container over nginx because it throws redirect loop error.
4. You manually add the `$CFG->reverseproxy = true` piece of code in `config.php`
5. Now you can access it over nginx. But this is useless and requires you to change data in volume.

**Describe the results you expected:**

There should be a variable called `MOODLE_REVERSE_PROXY` and we should be able to set it.

**Comment by carrodher** [comment]
Thanks for the PR, the team will take a look and provide feedback!
