### ISSUE TITLE
Consider upgrading configuration files and documentation for PostgresSQL

### ISSUE THREAD

**Issue by chris282** [bitnami/bitnami-docker-moodle#201]
### Name and Version

 bitnami / bitnami-docker-moodle / 3.11.5-debian-10-r25 

### What is the problem this feature will solve?

Hello
Thank you for making a first step to support PostgresSQL that is great.
However, at the moment the docker compose file is given with mariadb instructions and we don't know how to get the PostgresSQL ready to go.

### What is the feature you are proposing to solve the problem?

Implementing a docker compose with values corresponding to the PostgresSQL is possible, if not suggest another solution and/or document the limitations if applicable

### What alternatives have you considered?

Tweaking & tuning in the user side, but can be tricky and time consuming : Are we sure that this will work?

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
