### ISSUE TITLE
Container always return error code 1 in "Running database upgrade" stage

### ISSUE THREAD

**Issue by geosmina** [bitnami/bitnami-docker-moodle#202]
### Name and Version

bitnami/moodle:3

### What steps will reproduce the bug?

1. Clear the moodle cache with Moosh tool with the command `moosh cache-clear`

### What do you see instead?

After clearing the cache, moodle does not pass the "Running database upgrade" step and ends with error code 1.

### Additional information

I checked the settings in `config.php` in moodle volume and everything seems correct. When running `docker-compose up`, the MariaDB container runs normally but moodle always throws the same error

**Comment by javsalgar** [comment]
Hi,

Thank you using Bitnami! Please, note this Helm chart is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.
