### ISSUE TITLE
Languages can't install 

### ISSUE THREAD

**Issue by umer60** [bitnami/bitnami-docker-moodle#204]
### Name and Version

bitnami/moodle

### What steps will reproduce the bug?

Installing languages show this error
Your server does not seem to fully support the following languages:

Español - Colombia ‎(es_co)‎
Español - Internacional ‎(es)‎
العربية ‎(ar)‎
Instead, the global locale (en_AU.UTF-8) will be used to format certain strings such as dates or numbers.

### What do you see instead?

Your server does not seem to fully support the following languages:

Español - Colombia ‎(es_co)‎
Español - Internacional ‎(es)‎
العربية ‎(ar)‎
Instead, the global locale (en_AU.UTF-8) will be used to format certain strings such as dates or numbers.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by ssllqq** [comment]
I build own container of original adding locales and ghost script for assign pdf annotation.
Locale fixed problem of language support in moodle.
DockerFile:
```
FROM bitnami/moodle:3

RUN echo "lt_LT.UTF-8 UTF-8" >> /etc/locale.gen
RUN /usr/sbin/locale-gen -a
RUN install_packages ghostscript

COPY libmoodle.sh /opt/bitnami/scripts/libmoodle.sh
```

**Comment by umer60** [comment]
Thank you very much for your reply let me try with this dockerfile

**Comment by umer60** [comment]
I follow the same steps to install language but after installing Language fro GUI it show me the same error although it install language
error  Instead, the global locale (en_AU.UTF-8) will be used to format certain strings such as dates or numbers.

**Comment by ssllqq** [comment]
`RUN echo "es_ES.UTF-8 UTF-8\nes_CO.UTF-8 UTF-8\nar_SA.UTF-8 UTF-8" >> /etc/locale.gen`
I just build with this, and all locales installed. Arabic (ar) in moodle langconfig.php is ar_SA set, so i installed it.

**Comment by umer60** [comment]
still facing same after doing this

**Comment by ssllqq** [comment]
maybe you can provide how you build dockerfile and docker-compose.yml content.
i using visual studio code do edit files, build, and start containers on localhost.
`docker build --pull --rm -f "DockerFile" -t moodle_locales:latest "." <`
from default docker-compose.yml i change image to moodle_locales:latest which i build on local machine
```
moodle:
    image: moodle_locales:latest
    ports:
      - '80:8080'
      - '443:8443'
```
did you tryed connect to container and check `locale -a` or read content of `/etc/locale.gen`
