### ISSUE TITLE
/opt/bitnami/php/tmp is not write-able

### ISSUE THREAD

**Issue by rsafcz** [bitnami/bitnami-docker-moodle#206]
### Name and Version

bitnami/moodle;3.11.6-debian-10-r10

### What steps will reproduce the bug?

When edditing long pages or uploading some big files, there is PHP notice
Unknown: file created in the system's temporary directory in Unknown on line 0

### What do you see instead?

temporarily solved by chmod go+w /opt/bitnami/php/tmp

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
