### ISSUE TITLE
Moodle - AWS - Technical issue with ports

### ISSUE THREAD

**Issue by ssllqq** [bitnami/bitnami-docker-moodle#207]
### Name and Version

bitnami/moodle:3

### What steps will reproduce the bug?

Run default compose 
ports:
- 80:8080
- 443:8443

Loading moodle with localhost and when change address without login to localhost/my and it redirect to localhost:8080/my/ same result with HTTPS
Found same problem in dashboard too, when press "Customize this page" and if you press "Reset page to default" it will redirect to 8443 port. Reset worked but after, it redirect to wrong port.
 
Tryed change ports by https://github.com/bitnami/bitnami-docker-moodle/issues/171 but no result.

### What do you see instead?

Redirect to 8080 and 8443 ports instead of 80 and 443

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
