### ISSUE TITLE
Upgrade to Moodle 4

### ISSUE THREAD

**Issue by vlk-charles** [bitnami/bitnami-docker-moodle#208]
### Name and Version

bitnami/moodle

### What is the problem this feature will solve?

Upgrading to the latest stable release of Moodle, which is version 4 released on 2022-04-19.

### What is the feature you are proposing to solve the problem?

Release an image based on Moodle 4.

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was already detected by our system but since it's a major version it requires some manual changes in the build, test & release pipeline.
We'll update this thread once released

**Comment by carrodher** [comment]
Moodle 4.x was released a couple of days ago (https://github.com/bitnami/bitnami-docker-moodle/commit/4cca6a7235264d40a527605c862d7ef593b2fd0a); you should be able to use the new major version from the typical registries such as DockerHub.

In the same way, the Helm chart was updated to use this new version.
