### ISSUE TITLE
Order of scripts in Dockerfile keeps swapping between revision commits

### ISSUE THREAD

**Issue by vlk-charles** [bitnami/bitnami-docker-moodle#209]
### Name and Version

bitnami/moodle

### What steps will reproduce the bug?

This isn't really a bug but I noticed that in `3/debian-10/Dockerfile`, the order of these two lines keeps swapping back and forth over time:
```
RUN /opt/bitnami/scripts/apache/postunpack.sh
RUN /opt/bitnami/scripts/php/postunpack.sh
```

### What is the expected behavior?

For the order to not change if there is no functional difference.

### What do you see instead?

For example the commit 9d39d53bd24f169dc0775d8958fd7fe5fc14b31c changes the order from:
```
RUN /opt/bitnami/scripts/apache/postunpack.sh
RUN /opt/bitnami/scripts/php/postunpack.sh
```
to:
```
RUN /opt/bitnami/scripts/php/postunpack.sh
RUN /opt/bitnami/scripts/apache/postunpack.sh
```

The next commit (23dcc3d355a23abdb2faddbda92c8e04fcf86a6e) changes it back and the commit after that (4f4c5f98d356a8ddd707260eaade50856b68b23b) changes it to the second variant again. There are many more examples of this in the commit history.

**Comment by carrodher** [comment]
Thanks for letting us know, _Dockerfiles_ are automatically generated using a templating system. I just escalated this issue to the proper team in order to check what's going on with that automation.
