### ISSUE TITLE
Update mismatch

### ISSUE THREAD

**Issue by GustelDE** [bitnami/bitnami-docker-moodle#211]
### Name and Version

moodle/4.0.1 or 3.11.6

### What steps will reproduce the bug?

Hi,

we run a Moodle-Docker-Installation and wanted to Update to V4.0.1 (from 3.11.6).
We followed this (Upgrade this image): https://hub.docker.com/r/bitnami/moodle

Theses steps:
sudo docker pull bitnami/moodle:latest
sudo docker-compose stop moodle
sudo docker-compose rm -v moodle
sudo docker-compose up -d

Now we have in Docker the V4.0.1:
![Screenshot 2022-05-17 195741](https://user-images.githubusercontent.com/26502186/168879299-d95ae79e-d792-4289-80d3-440f2e9a8158.jpg)

And in Moodle itself 3.11.6:
![Screenshot 2022-05-17 195800](https://user-images.githubusercontent.com/26502186/168879338-ed9c421f-22da-486a-803a-4f8756d7dd06.jpg)

What do we wrong?

Thanks

### What is the expected behavior?

Upgrade to V4.0.1

### What do you see instead?

Update mismatch between 4.0.1 (Docker/Portainer) and 3.11.6 (Moodle)

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by GustelDE** [comment]
NO, its not closed! 😄
The Devs are only to lazy to look here... 😏
