### ISSUE TITLE
Successful upgrade but restart fail

### ISSUE THREAD

**Issue by BaptisteLalanne** [bitnami/bitnami-docker-moodle#212]
### Name and Version

bitnami/moodle@sha256:256cf9bd6e5d75b04b56f38d77d228061259339bc4e12f4a7251b3dff4855be3

### What steps will reproduce the bug?

I'm on a Moodle 3.5
1. Put server in maintenance
2. Insert 3.6 moodle folder 
3. Copy old folders into the new version (theme,mod,moodledata)
4. Upgrade the website to 3.6
(So far so good, I have a fonctionnal new version of Moodle)
5. Restart the container

### What is the expected behavior?

Restart without fail

### What do you see instead?

Error executing 'postInstallation' : Database tables already present; CLI installation cannot continue.

### Additional information

I did try to delete tables, let it creates them, and put back my tables in but I get an empty Moodle

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
