### ISSUE TITLE
failed to run moodle app with External database configuration of  AWS RDS from kubernetes

### ISSUE THREAD

**Issue by bima-saiprasad** [bitnami/bitnami-docker-moodle#214]
### Name and Version

bitnami/bitnami-docker-moodle

### What steps will reproduce the bug?

1.Tried to configure external database RDS from kubernetes. used the external database configuratioin parameters and updated the RDS details.
2.In the Kubernetes logs it is connecting RDS and creating  tables and values in the database as well. 
3.But it Struct in Running Moodle Scrip
![Capture](https://user-images.githubusercontent.com/106529791/171267029-55a273ce-b106-4970-8028-ad4631ccf6f6.PNG)
t

### What do you see instead?

1. When configured external database with RDS its stops in Running Moodle Install script
![Capture](https://user-images.githubusercontent.com/106529791/171267287-4ade6048-bfaf-4962-81da-5a5a2736fcfc.PNG)
.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
