### ISSUE TITLE
CFG->wwwroot

### ISSUE THREAD

**Issue by PierrotLaLune** [bitnami/bitnami-docker-moodle#215]
### Name and Version

bitnami/moodle 3.11.4-debian-10-r25

### What steps will reproduce the bug?

This is a configuration issue which creates problems loading pages at random times (I suspect when there is a timeout from the DNS server)

Currently, in the file config.php, the wwwroot will be dynamically created using the PHP $_SERVER global as follow :
```
if (empty($_SERVER['HTTP_HOST'])) {
$_SERVER['HTTP_HOST'] = '127.0.0.1:8080';
}
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
$CFG->wwwroot = 'https://' . $_SERVER['HTTP_HOST'];
} else {
$CFG->wwwroot = 'http://' . $_SERVER['HTTP_HOST'];
```
This creates problems which I've experienced and is a way to set wwwroot explicitely discouraged in the moodle wiki. 
See:
https://docs.moodle.org/400/en/Configuration_file#Setting_.24CFG-.3Ewwwroot_correctly

The fix is to get the install script to create a static $CFG->wwwroot string, not dependant on the $_SERVER variable

### What is the expected behavior?

No more problems loading pages

### What do you see instead?

Problems loading pages. Happened for me maybe once a day with courses including labels with an embedded video

### Additional information

If you want the full discussion with more details, see the post on Moodle forum:
https://moodle.org/mod/forum/discuss.php?d=435122

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by PierrotLaLune** [comment]
Thanks Carlos,

What's a PR ? (yes, I am new to this)

KR
PH

**Comment by carrodher** [comment]
> Thanks Carlos, What's a PR ? (yes, I am new to this) KR PH

[PR = Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests), it is the way to collaborate by creating a code contribution.
