### ISSUE TITLE
Language not suported although locale exists

### ISSUE THREAD

**Issue by kpi6288** [bitnami/bitnami-docker-moodle#216]
### Name and Version

bitnami/moodle 4.0.1 (Build: 20220509)

### What steps will reproduce the bug?

Base installation: 

- Debian 11 fresh install as VM on VirtualBox (test environment)
- Portainer installed
- bitnami moodle created as portainer stack with docker-compose from [here](https://github.com/bitnami/bitnami-docker-moodle/blob/master/docker-compose.yml)

Added locale manually: 

- Opened bash in the comtainer moodle_moodle_1
- dpkg-reconfigure locales  => select 111 (de_DE.UTF8)
- checked: 
>    locale -a:
>    locale: Cannot set LC_CTYPE to default locale: No such file or directory
>    locale: Cannot set LC_MESSAGES to default locale: No such file or directory
>    locale: Cannot set LC_COLLATE to default locale: No such file or directory
>    C
>    C.UTF-8
>    POSIX
>    de_DE.utf8
- Logged into moodle => Site administration => Language packs
- Added 'German / Deutsch (de)'

### What is the expected behavior?

- Installed language packs: English and German 
- No error message

### What do you see instead?

- Installed language packs: English and German 
- Error message 'Your server does not seem to fully support the following languages:
    Deutsch ‎(de)‎
Instead, the global locale (en_AU.UTF-8) will be used to format certain strings such as dates or numbers.'

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
