### ISSUE TITLE
Scale out activity causes users to be logged out

### ISSUE THREAD

**Issue by hendryanw** [bitnami/bitnami-docker-moodle#218]
### Name and Version

bitnami/moodle:3.11.7

### What steps will reproduce the bug?

1. Run the 1 replica of the container as per installation guide:
1.a. Behind a load balancer with sticky sessions enabled (It's also the same behavior with sticky sessions disabled)
1.b. with /bitnami directory attached to NFS volume on different server
1.c. with Application Cache set to use Redis on different server
1.d. with database using MySQL on different server.
2. Login and use Moodle as usual
3. Trigger scale-out by adding another replica mounted to the same data stores as the original replica, behind the same load balancer.
4. Once the other replicas is spawned, refresh the browser or navigate to other modules inside Moodle

### What is the expected behavior?

Expected behavior: users continued to use Moodle without being logged out and the application can cater more users with the new replicas.

### What do you see instead?

Actual results: Users are logged out with message: Your session has timed out. Please log in again.

### Additional information

If the scenario is the other way where other replicas is being deleted instead, then users is not being logged out. So I suspect that there is a script or process that delete or refresh all the sessions on the centralized volume / cache when a new container is launched.

**Comment by ssllqq** [comment]
https://github.com/bitnami/bitnami-docker-moodle/blob/5108268cc4a0e13ef3b616152258b918cb0d3b8b/3/debian-11/rootfs/opt/bitnami/scripts/libmoodle.sh#L215
Here is problem, when starting new container it deletes session directory, i build own container with removed session delete function.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by hendryanw** [comment]
> https://github.com/bitnami/bitnami-docker-moodle/blob/5108268cc4a0e13ef3b616152258b918cb0d3b8b/3/debian-11/rootfs/opt/bitnami/scripts/libmoodle.sh#L215
> 
> 
> Here is problem, when starting new container it deletes session directory, i build own container with removed session delete function.

@ssllqq Thanks Tomas! Have you considered to submit a PR for this so that Bitnami team can review it?
