### ISSUE TITLE
moodle not showing icons in Admin panel 

### ISSUE THREAD

**Issue by umer60** [bitnami/bitnami-docker-moodle#220]
### Name and Version

bitnami/moodle 3.11

### What steps will reproduce the bug?

icons not showing in admin panel like site administration and other 

### What is the expected behavior?

it show blank or missing icon

### What do you see instead?

not showing proper icon

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
