### ISSUE TITLE
File upload failed

### ISSUE THREAD

**Issue by ssllqq** [bitnami/bitnami-docker-moodle#222]
### Name and Version

bitnami/moodle:4

### What steps will reproduce the bug?

run any newest version of 4.0.1-debian-11-r2 with apache 2.4.54
enviroment:
      - PHP_POST_MAX_SIZE=5G
      - PHP_UPLOAD_MAX_FILESIZE=5G
Upload 1,8GB file to course restore.
Upload video 1.4GB file in course content.
Any uploads bigger 1.1GB will fail, files smaller than 1GB upload successful.

### What do you see instead?

Error connecting to the server

### Additional information

4.0.1-debian-11-r1 with apache 2.4.53-2 file upload works fine

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
