### ISSUE TITLE
Cannot add volume linked to /opt/bitnami/moodle

### ISSUE THREAD

**Issue by rayhand** [bitnami/bitnami-docker-moodle#55]
**Description**

Hello, I have a running container created from your great bitnami-docker-moodle image (using Docker for Windows). My goal is to develop a new moodle plugin inside the container for portability, but I can't  add a volume linked to /opt/bitnami/moodle where the moodle core files are. Is this possible? I am a newbie with docker containers, please help me.

I tried these steps from stackoverflow [http://stackoverflow.com/questions/28302178/how-can-i-add-a-volume-to-an-existing-docker-container](http://stackoverflow.com/questions/28302178/how-can-i-add-a-volume-to-an-existing-docker-container)

**Steps to reproduce the issue:**

1. [First Step]
docker commit moodle moodle2develop

2. [Second Step]
docker run -d -p 80:80 -p 443:443 --network moodle-tier 
-v "D:\pathto\persistance\apache":/bitnami/apache 
-v "D:\pathto\persistance\php":/bitnami/php 
-v "D:\pathto\persistance\moodle":/bitnami/moodle 
-v "D:\pathto\moodlesite":/opt/bitnami/moodle moodle2develop

**Describe the results you received:**

Accesing to localhost returns  "Forbidden. You don't have permission to access / on this server."
and the folder "D:\pathto\moodlesite" is empty 

**Describe the results you expected:**
I expected Moodle to be running normally as it did before I added the 
"/opt/bitnami/moodle" volume and also I expected that folder "D:\pathto\moodlesite" shows moodle root files and folders.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

- Output of `docker info`:

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: OD7Y:6SQM:6CBP:COHY:KYOL:UKHO:OSPT:TEVQ:IV47:KOXE:UMJN:QEXO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 400
 Goroutines: 392
 System Time: 2017-04-26T18:53:39.2671133Z
 EventsListeners: 11
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker for Windows, Windows 10

**Comment by sameersbn** [comment]
@rayhand The moodle application is installed at `/opt/bitnami/moodle`. Mounting a volume at this location will essentially break the entire container.

This image was not designed for development purposes, however if you wish to continue developing your plugin with this image then I would suggest you try the following:

```bash
# launch moodle
$ docker run -d -p 80:80 -p 443:443 --name moodle --network moodle-tier \
-v /path/to/persistence/apache:/bitnami/apache \
-v /path/to/persistence/php:/bitnami/php \
-v /path/to/persistence/moodle:/bitnami/moodle \
bitnami/moodle:latest

# create the plugin directory in the `/path/to/persistence/moodle`
$ mkdir -p /path/to/persistence/moodle/my-plugin

# fix ownership of the `/bitnami/moodle/my-plugin` directory
$ docker exec -it moodle chown -R daemon:daemon /bitnami/moodle/my-plugin

# create a symlink in the container 
$ docker exec -it moodle ln -sf /bitnami/moodle/my-plugin /opt/bitnami/moodle/mod/my-plugin
```

_P.S. You will need to execute the last two commands each time the container is re-created_

You should be able to make changes to your plugin present on the host at path `/path/to/persistence/moodle/my-plugin`. 

Please note that I have not tried these instructions myself due to my lack of experience with moodle plugin development. I hope you find these suggestions useful.

Thanks for choosing the Bitnami moodle image.

**Comment by rayhand** [comment]
It works!

Thanks for the quick and effective response. Any plans for an image for development purposes?

I will close this as solved 👍
