### ISSUE TITLE
Moodle fails to start with "Error executing 'postInstallation'"

### ISSUE THREAD

**Issue by mkalish** [bitnami/bitnami-docker-moodle#56]
**Description**
Unable to start using docker-compose.  MariaDB starts successfully, but moodle exists with Error executing 'postInstallation'.

**Steps to reproduce the issue:**

1. run `docker-compose up -d`

**Describe the results you received:**

Moodle is unavailable in the browser and inspecting the logs reveals that moodle exited.

**Describe the results you expected:**

Moodle to start and become available.

**Additional information you deem important (e.g. issue happens only occasionally):**

Relevant logs
```
moodle_1   | Welcome to the Bitnami moodle container
moodle_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle_1   | Send us your feedback at containers@bitnami.com
moodle_1   | 
moodle_1   | nami    INFO  Initializing moodle
moodle_1   | mysql-c INFO  Trying to connect to MySQL server
moodle_1   | mysql-c INFO  Found MySQL server listening at mariadb:3306
moodle_1   | mysql-c INFO  MySQL server listening and working at mariadb:3306
moodle_1   | Error executing 'postInstallation': Program exited with exit code 1
```

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

- Output of `docker info`:

```
Containers: 15
 Running: 1
 Paused: 0
 Stopped: 14
Images: 109
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 242
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: ZITF:NLOM:FKR4:PDXT:D4ES:IFIK:6AN4:3XEK:GMRL:MM3K:5QRY:XT5L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 36
 System Time: 2017-05-11T17:45:54.335034283Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Username: mkalish
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running on OSX El Capitan

**Comment by juan131** [comment]
I just run `docker-compose up -d` in OS-X using the latest version of Moodle and MariaDB Docker Image and both containers started successfully:

```
moodle_1   | nami    INFO  Initializing moodle
moodle_1   | mysql-c INFO  Trying to connect to MySQL server
moodle_1   | mysql-c INFO  Found MySQL server listening at mariadb:3306
moodle_1   | mysql-c INFO  MySQL server listening and working at mariadb:3306
moodle_1   | moodle  INFO  Configuring Cron Jobs...
moodle_1   | moodle  INFO
moodle_1   | moodle  INFO  ########################################################################
moodle_1   | moodle  INFO   Installation parameters for moodle:
moodle_1   | moodle  INFO     Username: user
moodle_1   | moodle  INFO     Password: **********
moodle_1   | moodle  INFO     Email: user@example.com
moodle_1   | moodle  INFO   (Passwords are not shown for security reasons)
moodle_1   | moodle  INFO  ########################################################################
moodle_1   | moodle  INFO
moodle_1   | nami    INFO  moodle successfully initialized
moodle_1   | INFO  ==> Starting moodle...
moodle_1   |
```

Could you please confirm that you don't have any volume with persisted data from previous Moodle containers? Please run the commands:

```
docker-compose down -v
docker-compose up
```

**Comment by mkalish** [comment]
After removing the volumes, I was able to get moodle started up.  Sorry for the opening the issue, but thanks for the quick response!

**Comment by totogo** [comment]
I got similar error:
```
Error executing 'postInstallation': Database tables already present, cli installation can not continue.
```

The tables were created when I previously launch the container, my question is, how can I reuse the tables and data in previous Moodle container?

**Comment by juan131** [comment]
Hi @totogo 

You can start Moodle using a existing database, please find out the section below in the **README.md** file:

https://github.com/bitnami/bitnami-docker-moodle#use-an-existing-database

When you start Moodle using that configuration it will try to use the database you indicate instead of trying to populate it with data from scratch.

**Comment by totogo** [comment]
@juan131 Thanks for your feedback.
But I did use the configuration setup described in the README file:
```
ALLOW_EMPTY_PASSWORD=no
MARIADB_HOST=xxxx
MARIADB_PORT_NUMBER=xxxx
MOODLE_DATABASE_NAME=moodle_test
MOODLE_DATABASE_USER=moodle
MOODLE_DATABASE_PASSWORD=xxx
```

But I still got this error:
```
Error executing 'postInstallation': Database tables already present, cli installation can not continue.
```
It can connect to the MySQL server and find the existing DB, but it does not reuse the data there. 

Do you know which configuration specifically controls this?

**Comment by juan131** [comment]
Hi @elreydetoda 

The only way to scale horizontally is to use a NFS server which allows you to have RWX (Read Write Many) volumes. 

This way, the data (and the configuration) available on the volumes attached on each Moodle container will be sync. The behaviour is sth like:

 - 1st container. Populates the database and creates configuration files
 - Scale horizontally to N containers.
 - Each of new containers, will reuse the configuration and the database created by the 1st container when they detect data on the volume.

For instance, you can do it on a K8s cluster using a NFS provider (which can be installed using Helm)

**Comment by Isotop7** [comment]
Hi,

is there any way to skip the installation? I've never came across this behaviour.
Every other docker container checks for existing data and just uses it. Right now, if I rescale in K8s, our guys in frontend have to redeploy everything.

This can not be your best idea.

**Comment by andresbono** [comment]
Hi @lsotop7, are you using a RWX (Read Write Many) volume in your k8s Moodle setup?

**Comment by Isotop7** [comment]
> Hi @lsotop7, are you using a RWX (Read Write Many) volume in your k8s Moodle setup?

Partly correct. I'm using a nfs-provisioner service and attached a pvc to the pod.
The pvc is configured as "Single Node Read-Write".

**Comment by juan131** [comment]
Hi @fcortijo-waldo

I was unable to reproduce the issue. These are the steps I followed:

- Ensure my cluster has NFS packages installed: `sudo apt-get install nfs-common`
- Install NFS provider:

```
$ helm install --name nfs-server-provisioner stable/nfs-server-provisioner --set persistence.enabled=true,persistence.size=5Gi
```

- Once the NFS provide is running, install Moodle chart:

```
$ helm install --name moodle stable/moodle --set persistence.storageClass=nfs --set persistence.accessMode=ReadWriteMany --set persistence.size=2Gi
```

-  Wait for Moodle to be initialised on first pod:

```
$ kubectl logs -f $(kubectl get pods -l app=moodle-moodle -o jsonpath='{.items[0].metadata.name}')
...
nami    INFO  moodle successfully initialized
INFO  ==> Starting moodle...
INFO  ==> Starting httpd...
...
```

-  Scale WP deployment:

```
$ kubectl scale deploy moodle-moodle --replicas 2
deployment.extensions/moodle-moodle scaled
```

- Get logs from second pod:

```
$ kubectl logs -f $(kubectl get pods -l app=moodle-moodle -o jsonpath='{.items[1].metadata.name}')

Welcome to the Bitnami moodle container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing moodle
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at moodle-mariadb:3306
mysql-c INFO  MySQL server listening and working at moodle-mariadb:3306
moodle  INFO  Configuring Cron Jobs...
moodle  INFO
moodle  INFO  ########################################################################
moodle  INFO   Installation parameters for moodle:
moodle  INFO     Persisted data and properties have been restored.
moodle  INFO     Any input specified will not take effect.
moodle  INFO   This installation requires no credentials.
moodle  INFO  ########################################################################
moodle  INFO
nami    INFO  moodle successfully initialized
INFO  ==> Starting moodle...
INFO  ==> Starting httpd...
```

As you can see everything is working as expected. More info:

```
$ kubectl get pvc
NAME                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-moodle-mariadb-0           Bound    pvc-5bc2aaba-7dfe-11e9-95b7-08002734b26d   8Gi        RWO            standard       12m
data-nfs-server-provisioner-0   Bound    pvc-2df9ac66-7dfe-11e9-95b7-08002734b26d   8Gi        RWO            standard       13m
moodle-moodle                   Bound    pvc-5b879466-7dfe-11e9-95b7-08002734b26d   2Gi        RWX            nfs            12m
```

**Comment by universam1** [comment]
I can reproduce the issue @juan131 
If I use the NFS mount at /bitnami the application does not run correctly:

`error/An error occurred whilst communicating with the server`

However, if I do NOT use NFS but start container a second time I get 
`Database tables already present`

**Comment by juan131** [comment]
Hi @universam1 

Are you installing the chart with only 1 replica in the deployment and scaling it once the 1st container has finished the initialization (just as I described in the instructions above)? Please note it won't work otherwise.

**Comment by universam1** [comment]
Thanks I understand that. That’s though a production grade stopper!

However the bigger issue is that the application crashes if run on NFS! See the error posted above. 
Can you ensure that the application actually does work on your setup? Using your setup it does not for me

**Comment by juan131** [comment]
Hi @universam1 

> Thanks I understand that. That’s though a production grade stopper!

It's related to the way this Moodle works. As I mentioned some comments above:

> Here you have a summary of the behaviour:
> 
>  - Do I have persisted data/configuration from previous deployments?
>      - Yes. Then reuse that data and connect to the database indicated on the config file.
>      - No. Do I need to create a new database?
>          - Yes. Create it using a MySQL client. Then populate it.
>          - No. Populate the external database using the credentials provided.

Other Bitnami solutions such as WordPress support this behaviour (setting the env. variable **WORDPRESS_SKIP_INSTALL**) More info in the link below:

https://github.com/bitnami/bitnami-docker-wordpress#connect-wordpress-docker-container-to-an-existing-database

We could try to extend this behaviour to other apps.

> However the bigger issue is that the application crashes if run on NFS! See the error posted above.
Can you ensure that the application actually does work on your setup?

Yes, I can confirm the application actually works. Did the message below appeared on your 1st pod log before you scaled the solution? 

```
nami    INFO  moodle successfully initialized
INFO  ==> Starting moodle...
INFO  ==> Starting httpd...
```

Did you install the chart on a clean environment? Sometimes some PVCs are not delete when removing the chart so the database is started with old data. Ensure the associated MariaDB database does not reuse PVCs. You can check whether there are existing PVCs by running the command below before installing the cart:

```
$ kubectl get pvc
```

What kind of K8s cluster are you using?
