### ISSUE TITLE
Adding WWWROOT ENV variable

### ISSUE THREAD

**Issue by ObjectiveTruth** [bitnami/bitnami-docker-moodle#58]
The official `config-dist.php` contains a section for providing the website location for moodle. This is important when serving moodle from behind a firewall or reverse proxy(for example `/moodle/`.

It would be useful to have it as an environmental variable that inserts the constant show below when the `config.php` is being created in `docker-entrypoint.sh`

```
//=========================================================================
// 2. WEB SITE LOCATION
//=========================================================================
// Now you need to tell Moodle where it is located. Specify the full
// web address to where moodle has been installed.  If your web site
// is accessible via multiple URLs then choose the most natural one
// that your students would use.  Do not include a trailing slash
//
// If you need both intranet and Internet access please read
// http://docs.moodle.org/en/masquerading
$CFG->wwwroot   = 'http://example.com/moodle';
```
https://github.com/moodle/moodle/blob/master/config-dist.php#L76-L87

`WWW_ROOT` would be my recommendation

I tried to look through the source code and couldn't find how you guys are inserting the env variables into the `config.php`. If you can point me in the right direction I'll submit a PR

**Comment by ObjectiveTruth** [comment]
I managed to do this using moodle's `defaults.php` file which is much more idiomatic and succinct

https://docs.moodle.org/32/en/Administration_via_command_line

Closing the ticket

**Comment by ObjectiveTruth** [comment]
Reopening because `defaults.php` doesn't work with `CFG->wwwroot`

**Comment by prydonius** [comment]
Thanks @ObjectiveTruth. I think we should add a `MOODLE_WWW_ROOT` env var. It's not clear to me whether this should be a path (e.g. `/moodle`, which in the config could expand to `http://127.0.0.1/moodle`) or if you should be able to specify a full host. Any thoughts on that @ObjectiveTruth?

**Comment by ObjectiveTruth** [comment]
Hey, very late response, but I managed to just make my own Docker in the meantime.

However I do agree that it should probably be 2 variables that get expanded to the `/moodle` like you said.

`MOODLE_WWW_HOST`
`MOODLE_WWW_PATH`

Then in the `config.php`, concatenate them together

Also, Apache has to be made aware of the change, I did it using an alias

**Comment by jtmorris245** [comment]
Hi,
I've also been having this issue, and I think that adding the proposed variables would be a good solution to this, as making modifications to the configuration inside the container somewhat goes against the idea of containers.
I'll give adding this feature a go, however, I'm not particularly skilled with PHP, so no guarantees!

**Comment by juan131** [comment]
Hi @jtmorris245 

There's an env. variable (**MOODLE_SITENAME**) that allows you to set the Moodle's Site Name. More info:

https://github.com/bitnami/bitnami-docker-moodle/blob/master/3/debian-9/rootfs/moodle-inputs.json#L9

However, that doesn't allows you to configure the Hostname/path. I agree with you and we should include these env. variables in the image. I'll open an internal task to include this feature on future versions of the container.

**Comment by marcosbc** [comment]
Hi, we recently refactored and improved the initialization logic for the Bitnami Moodle container, and it is now based on Bash scripts available in the `rootfs` directory. For more info see: https://github.com/bitnami/bitnami-docker-moodle#390-debian-10-r17

Note that currently Moodle modifies wwwroot to base on the server's HTTP_HOST environment, so it is valid for any host. You can find the related logic here: https://github.com/bitnami/bitnami-docker-moodle/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh#L296

I'm going to close this, but if you consider this still needs fixing, let us know and we can re-open this.
