### ISSUE TITLE
moodle on NFS volume

### ISSUE THREAD

**Issue by ReSearchITEng** [bitnami/bitnami-docker-moodle#60]
BUG REPORT
I have logged all the details here: https://github.com/kubernetes/charts/issues/1439

All products are up to date, docker is 1.12.6

It is working fine in any other version of volumes, but not on NFS.
I see volumes are properly mounted and populated with moodle files.

Did anyone use it on NFS? Is it working ?

**Comment by chipironcin** [comment]
Hi @ReSearchITEng 
The issue you are experiencing may be due to a timeout in the server trying to serve your request.
Can you check how much time does the `curl` command takes to return the error?
