### ISSUE TITLE
Backup Theme nad Plugins

### ISSUE THREAD

**Issue by kahidna** [bitnami/bitnami-docker-moodle#63]
I try to deploy and custom moodle's appearance by install theme to the moodle.   
and I try to test persistence the moodle by backup and restore using **similar step** just like tutorial on <a href="https://github.com/bitnami/bitnami-docker-moodle#persisting-your-application">this repo</a>

1. So first I stop the container using command: `docker-compose stop`
2. Archiving using command: `zip -r moodle-backup.zip moodle_persistence_folder/`
3. Extract moodle-backup.zip to another server with the same path
4. change moodle's folder owner to user which the same group with Docker 
5. run command: `docker-compose up`

Indeed the data is persistence, but the Theme seems not backed up also, which leads the appearance looks ugly and show some errors on the homepage :
```
line 677 of /lib/pagelib.php: call to moodle_page->initialise_theme_and_output()
line 864 of /lib/pagelib.php: call to moodle_page->magic_get_theme()
line 113 of /index.php: call to moodle_page->get_renderer()
```
Is there any other way to completely backup including with the themes or maybe also the plugin when running dockerized moodle instead commit the container and then load it to another server?  because  I realize that Moodle folder installation reside at `/opt`, and `/opt` is not a part volume on the docker compose. 

I run ubuntu server 14.04.5, with moodle 3.3.1 version, and docker 17.03.0-ce version

thank you

**Comment by juan131** [comment]
> I realize that Moodle folder installation reside at /opt, and /opt is not a part volume on the docker compose.

The directory that is persisted and where the data is recovered is `/bitnami/moodle/`. As you can check by running:

```
$ ls  /bitnami/moodle/
config.php  moodledata
```

The configuration file and the Moodle data directory are the only ones persisted. 

If you take a look to the `file /opt/bitnami/moodle/config.php`:

```
...
$CFG->dataroot  = '/bitnami/moodle/moodledata';
...
```

You can check that it's taken the data from the persisted directory. On the other hand, the file `/opt/bitnami/moodle/config.php` is just a symbolic link to `/bitnami/moodle/config.php`.

At this moment, the plugins and themes are not automatically recovered from the persistence directory (when deploying `docker-compose up`). If you want to persist them, you can extract the content at `/bitnami/moodle/` and then substitute the `/themes` folder at `/opt/bitnami/moodle/...` with a symbolic link as the `config.php` is.

**Comment by kahidna** [comment]
ok, I already try your suggestion to extract `/themes` folder for backup the theme and add that folder as a volume when re-init moodle in other instance. and so far it's work. thanks for the help.

and about the plugin, can I do something also to backup the plugin including the configuration? so my moodle will have completely persistent. :)

**Comment by dbarranco** [comment]
Hi @kahidna 

As the same applies with the plugins directory (commonly `/opt/bitnami/moodle/local/`). I've opened an internal task to solve this to avoid future workarounds with the directories and plugins.

Note that if you follow this workaround and you backup the themes and plugins, if you launch a new container which uses the persisted data, you will only have to make the symbolic links to those folders while we include them in the container.

I'm sorry for all the inconveniences that this may cause.

**Comment by burkeallen** [comment]
any updates to the docker image/configuration to address this, not being able to persist the themes and plugins makes this docker implementation on valid for the mostbasic of uses or for simple demo purposes.

**Comment by juan131** [comment]
I am afraid this issue hasn't been addressed yet @burkeallen ! I will update the associated task to see if we can its priority up. Thanks for your consideration.

**Comment by tompizmor** [comment]
Hello @burkeallen, @kahidna 

Since Bitnami Moodle Docker Image 3.4.0-r1 the whole installation directory is persisted so themes and plugins will remain after container restarts. 
Please pull the latest version of the moodle container or use the specific tag:

```
$ docker pull bitnami/moodle:latest
$ docker pull bitnami/moodle:3.4.0-r1
```
Tomas

**Comment by kahidna** [comment]
hi @tompizmor, I'm glad bitnami docker moodle's team release a new update.
I see there is update on Readme.md, especially on <a href="https://github.com/bitnami/bitnami-docker-moodle#upgrade-this-application">upgrade section</a>

which said :
> As an alternative, you can try upgrading using an updated docker image but any data from the Moodle container will be lost and you will have to reinstall all the plugins and themes you manually added.

so for upgrading moodle and keep the plugin and themes persistent, the only way is upgrading the application inside the container? and say I will migrate to the new server, I should backup the container (because if I pull a new image, mean __I have to reinstall all the plugins and themes I manually added__) also?

**Comment by tompizmor** [comment]
Hello @kahidna,

> so for upgrading moodle and keep the plugin and themes persistent, the only way is upgrading the application inside the container? 

Yes. The reason behind is that the Moodle application does not have a unique folder to store plugins and themes as you can see [here](https://docs.moodle.org/dev/Plugin_types). Therefore, there is no way to persist all those plugins directories and ensure that after upgrading Moodle using a new version of the docker image it actually contains all the new source code. 

> and say I will migrate to the new server, I should backup the container (because if I pull a new image, mean I have to reinstall all the plugins and themes I manually added) also?

Yes. If you want to migrate to a new server you should backup at least the volumes that contain the Moodle and MariaDB data and mounting in the same location that they were originally (`/bitnami`). Also, it is important that you use the same Moodle version when restoring these volumes.

**Comment by kahidna** [comment]
> Since Bitnami Moodle Docker Image 3.4.0-r1 the whole installation directory is persisted so themes and plugins will remain after container restarts.

@tompizmor  so the completely persistent moodle only work if I start the moodle service from the very beginning? its not working if I migrate from existing dockerized moodle?

**Comment by tompizmor** [comment]
@kahidna yes, I am afraid that you would need to start from a fresh Moodle 3.4.0-r1 and install your themes and plugins on top of it.

**Comment by kahidna** [comment]
hi @tompizmor, I just testing backup my second moodle service and restore it on a different server. and it's working, plugin and theme completely backed up. Awesome!! 

So for the upgrade just need to stop service, and then pull new image right?

**Comment by tompizmor** [comment]
Hi @kahidna,

> So for the upgrade just need to stop service, and then pull new image right?

No. As you pointed out [in this comment](https://github.com/bitnami/bitnami-docker-moodle/issues/63#issuecomment-361593782), the only way to upgrade the application and preserve themes and plugins is upgrading the application manually inside the container.
