### ISSUE TITLE
first run default compose: Unable to start com.bitnami.mariadb: Cannot find pid file

### ISSUE THREAD

**Issue by combrs** [bitnami/bitnami-docker-moodle#66]
I installed debian 9 server and docker and try to run first container.
I try to start docker-compose default compose file from https://hub.docker.com/r/bitnami/moodle/
with command
`docker-compose --project-name moodle1 -f docker-compose.yml` up or
`docker-compose up`
Console output is:
```
<downloading, unpacking...>
....
moodle_1   | nami    INFO  Initializing php
moodle_1   | nami    INFO  php successfully initialized
moodle_1   | nami    INFO  Initializing moodle
moodle_1   | mysql-c INFO  Trying to connect to MySQL server
mariadb_1  | Error executing 'postInstallation': Unable to start com.bitnami.mariadb: Cannot find pid file '/opt/bitnami/mariadb/tmp/mysqld.pid'.: Cannot find pid file '/opt/bitnami/mariadb/tmp/mysqld.pid'.
root_mariadb_1 exited with code 1
```

Wait some minutes

```
moodle_1   | Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries
root_moodle_1 exited with code 1
```

Should I configure some parameters in default compose before any start?
While it wait and try to "connect to MySQL" docker ps show this:
```
root@moodle:~# docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
45f103bf9804        bitnami/moodle:latest    "/app-entrypoint.s..."   2 minutes ago       Up 2 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   root_moodle_1
2d19b620c854        bitnami/mariadb:latest   "/app-entrypoint.s..."   2 minutes ago       Up 2 minutes        3306/tcp                                   root_mariadb_1
```
**Steps to reproduce the issue:**
1.  `apt-get install docker-compose`
2. `curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-moodle/master/docker-compose.yml > docker-compose.yml`
3. `docker-compose up`

Nothing more, all by default.

All containers stopped with error after some minutes.

Container must run with some default parameters without errors and listen on network.

**Additional information you deem important (e.g. issue happens only occasionally):**

- Output of `docker version`:
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:48 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
- Output of `docker info`:
```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 3
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
...
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-4-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 492.6MiB
Name: moodle
ID: D4EZ:OJIM:AKZ3:CYN3:RJYB:CS7C:CEDL:FMQX:YCE7:LDLN:VTIN:537U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
```
- Output of `docker-compose version`:
```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```
**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

KVM virtual machine in cloud provider service.

**Comment by combrs** [comment]
seems to lack of RAM problem and OOM killer killing something accidentally. VM Configuration is a 512Mb RAM, But when I change it to 2Gb RAM started compose (mariadb+moodle) occupied 1200 Mb RAM.. :))) 
Started Normally, But you need to mention it in readme ....

**Comment by carrodher** [comment]
The `nami initialize` command for Moodle is probably loading webkit to work its way through the setup wizard. I've noticed that this can take a allocate a lot of the available RAM. Take into account that this high memory allocation only occurs at the first launch, subsequent application launches will probably be fine on 512MB systems.

But I agree, it's probably a good idea to have the minimum requirements listed. We'll discuss it internally trying to figure out the best option.

**Comment by combrs** [comment]
But my cloud provider has a different hosting plans and support upgrades, but only to higher plans.  
1: 512Mb RAM - $4/month 2: 2Gb RAM - $16/month
Then I must go to plan/VM  2 for first run, but I cannot degrade to plan 1 for subsequent runs and forced to pay $16/month, although this is no longer necessary.

**Comment by sameersbn** [comment]
@combrs Ideally a 1GB instance should be a good choice to run moodle and you should also not see this issue. Does your hosting provider not offer an instance type with 1Gb of system memory?

Also could you try starting the mariadb instance first and once its fully started start the moodle container. The README should have instructions to run these containers using the `docker` cli.

Do let us know

**Comment by combrs** [comment]
@sameersbn Yes, on 1Gb machine that default installation start OK without errors.

**Comment by sameersbn** [comment]
Thats great! I believe you should use the 1GB instance.
