### ISSUE TITLE
Permission deny at trying to provide persistence 

### ISSUE THREAD

**Issue by BaxLi** [bitnami/bitnami-docker-moodle#67]
Description

I just create a new CentOs 7 VM on VMWare Workstation 
When I make all by default all is going ok ... 
But, after I change the docker-compose.yml file -> volume section, from default value to a new directory created within my CentOS home directory  
_volumes:
      - '/home/baxli/moodle/mariadb_data:/bitnami'_
I receive 
**- The "Error executing 'postInstallation': EACCES: permission denied, mkdir 'bitnami/mariadb'"**
i compare the permissions on mariadb_data and moodle_data created by default and change it at the directories within my home
$ ls -ld *
-rw-rwxrwx. 1 baxli baxli 494 Jan  7 15:31 docker-compose.yml
drwxr-xr-x. 2 root  root    6 Jan  7 15:32 mariadb_data
drwxr-xr-x. 5 root  root   45 Jan  7 15:32 moodle_data

I'm tried to add user 1001 and add it to root group.
No changes.

Steps to reproduce the issue:
1. install as per non-persistence.
2. Create a directory moodle within your home directory 
3. Change volume section to point to this just-created dir.
4. run docker-compose up
5. enjoy :(

- Output of `docker version`:
```
$ docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:10:14 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:46 2017
  OS/Arch:      linux/amd64
  Experimental: false

```

- Output of `docker info`:

```
$ docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.916GiB
Name: localhost.localdomain
ID: 5ENV:6RXU:6RJR:2HVN:B6VD:5KUI:IBJK:P7BS:6WXG:VQXZ:NU6D:CHER
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
$ docker-compose version
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.7.0
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
VMWare workstation. 
 hostnamectl
   Static hostname: localhost.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: e947d15562ac42248c5313e9a0a7d48e
           Boot ID: bea28b01cdc44b18857923cb6042b716
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-693.11.6.el7.x86_64
      Architecture: x86-64

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. This is related with this issue: https://github.com/bitnami/bitnami-docker-mariadb/issues/136. In this thread you can find a possible workaround for it. For example: https://github.com/bitnami/bitnami-docker-mariadb/issues/136#issuecomment-354644226

**Comment by javsalgar** [comment]
I think this issue can be considered closed. The use of host path folders in non-root containers normally causes issues, and should not be used. Instead, using volumes is recommended. Please, do not hesitate to re-open the issue if you consider it necessary.
