### ISSUE TITLE
How to setup this configuration behind Nginx?

### ISSUE THREAD

**Issue by tmdoit** [bitnami/bitnami-docker-moodle#68]
It's working with some simple configuration but I'm facing often 504 status code when browsing.

**Comment by juan131** [comment]
Bitnami Moodle images includes Apache as web server and we do not support using other web server such as NGINX at this moment. 

You could create a second container with NGINX redirecting the traffic to the Moodle container but it will be acting as a Proxy to the Apache web server instead of serving the Moodle site. I do not see any advantage on this approach.

You can configure NGINX to server a PHP application as it's described on these docs:
https://github.com/bitnami/bitnami-docker-php-fpm/#connecting-to-other-containers

However, you'll need to install/configure Moodle on top of the **php-fpm** container by your own.

**Comment by tmdoit** [comment]
Nginx is running on another container as reverse proxy. In my case the advantage is that, that I can host multiple services on http/https port on one machine (traffic control via subdomains).
As still working on this problem, I've made few steps forward and I'm sure that problem is not related to Nginx but Moodle.
After login as admin and click on "Site Administration" link, I'm waiting about ~ 4 minutes for page to open, on next try page opens normally. Problem exist in function admin_externalpage_setup() from lib/adminlib.php. 
I will give more info later.

**Comment by juan131** [comment]
You might need to update the hostname of your Moodle site since you're accessing to it using a different IP/domain (the NGINX one). You can do it modifying the database:


```
docker-compose exec mariadb mysql -uroot
use bitnami_moodle;
SELECT * from mdl_config WHERE name='chat_serverhost';
UPDATE mdl_config SET value='X.X.X.X' WHERE name='chat_serverhost';
```

You just need to replace X.X.X.X with the proper hostname

**Comment by tmdoit** [comment]
Thanks for the tip, didn't work but it reminds me similar problem with Gitlab behind Nginx with SSL.
Starting Moodle container with hostname flag "--hostname moodle.mycompany.com" where value is the publicly available domain address for the service did the trick.
It took me two days to find out where the cause is, please add short info to README.md about the solution for "Moodle behind reverse proxy (Nginx)".
For longer description I can create working configuration: "Moodle + MariaDB + Nginx with SSL (ie. Let's Encrypt)".

**Comment by juan131** [comment]
Great!! We are glad that you were able to fix the issue using the hostname flag.

Regarding the **README.md**, PRs are very welcome! Could you please add you suggestions?

**Comment by juan131** [comment]
Hi @trainingcity 

Did you try with the env. variable `MOODLE_SITENAME`? As you can check that's the env. variable used to setup the site name on Moodle:

https://github.com/bitnami/bitnami-docker-moodle/blob/master/3/debian-9/rootfs/moodle-inputs.json#L9

**Comment by trainingcity** [comment]
Thanks, Added MOODLE_SITENAME=https://myfqdn. I'm not sure that was the issue. I think I just didn't wait long enough for the install process to complete in the container. I checked the logs using portainer as the moodle container was starting up. It took a few more minutes than I was expecting.

Bottom line is I have the bitnami Moodle image running successfully behind an outstanding Nginx-Proxy with Letsencrypt. Very sweet combo! FYI: https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion

I ran the following command after bringing up the bitnami moodle containers, but also, may not have been needed: 
docker exec nginx-proxy-le /app/force_renew

**Comment by juan131** [comment]
Great @trainingcity 

I'm glad you were able to configure the site name of your Moodle site without issues. 

Thanks for sharing the NGINX-Proxy+Let'sEncrypt solution, I've seen several people using it and it looks pretty cool!

I'll proceed to close this issue as closed, please feel free to reopen if you face issues configuring Moodle again!

**Comment by javsalgar** [comment]
Thanks for sharing! :)

**Comment by xros** [comment]
Oh. For those people who use docker-compose to fire up apps.

Add one line in you app.yml :
```
- VIRTUAL_HOST=your.domain.com
```
Or use `docker` command with `-e VIRTUAL_HOST=your.domain.com`

My moodle is running on a docker container which consists of Apache2, PHP7. And the Nginx is on a host machine (not running in docker).

This saves my day.

**Comment by juan131** [comment]
Thanks so much for sharing this solution @xros !! I'm sure it'll be extremely helpful for other users struggling with the Moodle hostname configuration.
