### ISSUE TITLE
docker & moodle --> Upgade?

### ISSUE THREAD

**Issue by white-rabbit07** [bitnami/bitnami-docker-moodle#69]
Hi. I downloaded the bitnami/docker-image to use moodle via docker. The
idea is great but I don't understand the upgrade strategy.
On
https://github.com/bitnami/bitnami-docker-moodle#upgrade-this-application

you write that the upgrade should be done *inside* the container?! I
don't see the advantage of an always-up-to-date-docker container if I
have to upgrade the files inside of it manually again!? Can you explain
it once more?

The next problem:
When I use "docker pull bitnami/moodle:latest" I can download an
up-to-date-image but when I login to moodle there is no system option to
start the upgrade inside the WebGUI?! Is it the wrong container? There's
just a system message like "Newer moodle-version available" but noting else.

Thanks for information.
Michael

**Comment by juan131** [comment]
> Can you explain it once more?

As you mentioned, since 4th January, Moodle can only be upgraded inside the container. 

There were several users asking for a way to persist plugins, themes, etc. on this image. In order to do so, we had to persist the whole Moodle directory (since Moodle doesn't store all this data on a single directory) and, as a consequence, the upgrade process was affected.

You can find more information on the issue below:
https://github.com/bitnami/bitnami-docker-moodle/issues/63

> I can download an up-to-date-image but when I login to moodle there is no system option to
start the upgrade inside the WebGUI?

This docker image passes the wizard during the initialisation so it's not possible to access it when you pull the latest version.

**Comment by white-rabbit07** [comment]
Hi Juan. Thanks for information.
So all in all: the "installation" via docker is no way to keep moodle up to date on a server. Right?

**Comment by juan131** [comment]
Hi @white-rabbit07 

A good solution for you will be migrating your Moodle data. You can find more information on the link below:

https://docs.moodle.org/32/en/Moodle_migration

This way, you can use the latest image and migrate the data from your old container.

**Comment by white-rabbit07** [comment]
Hi. Ok -- this would be possible. Has anyone tested it with the bitnami-docker-container?
Something like:

```
docker exec -it “container-ID” bash
php admin/cli/maintenance.php --enable
php admin/cli/upgrade.php  
or: mysqldump ...
php admin/cli/maintenance.php --disable
```
Will it work like this?

**Comment by javsalgar** [comment]
Hi,

In principle, it is something doable. This guide is for cloud images (and the paths do not apply), but the process would be similar: 

   - Have the new version on top
   - Put the new data
   - Execute the corresponding upgrade tasks 
 
https://docs.bitnami.com/aws/apps/moodle/#how-to-upgrade-moodle

**Comment by white-rabbit07** [comment]
Ok, but these steps would be: many singel steps to go. My hope was to get an "always-up-to-date-moodle" via docker. 
Another thought: what if docker just provides an "always-up-to-date" LAMP-System? Then it would be possible to install moodle **via git** on a persistant volume in this container. Via "git pull" it would be possible to be up to date (at least actual branch). 
I'm just searching for steps to have moodle up-to-date -- on whatever server it runs. I'm afraid the bitnami-way won't work this way?
Greetings.

**Comment by juan131** [comment]
Hi @white-rabbit07 

You can use the [PHP-FPM Image](https://github.com/bitnami/bitnami-docker-php-fpm) to build Moodle on top of it. You can create a `docker-compose.yml` file using this Docker Image, plus [MariaDB Docker Image](https://github.com/bitnami/bitnami-docker-mariadb) to hold the database and [NGINX](https://github.com/bitnami/bitnami-docker-nginx) as web server.

In the link below you have a small guide to create a php based app on top of php-fpm container using NGINX as web server:

https://github.com/bitnami/bitnami-docker-php-fpm#serving-your-php-app-through-an-nginx-frontend

**Comment by trainingcity** [comment]
I still learning docker, would it be possible to upgrade moodle in the container, then commit a new image which could then be available to use with with a new container and the same persistent volumes should you need to remove the container / move, etc?

**Comment by juan131** [comment]
> I don't want to upgrade inside the containers, as it seems like over time this would lead to issues with php, apache, etc, which I believe are part of the moodle container/image?

Exactly, those containers contain Php, Apache and Moodle. However, its' recommend that you upgrade the container to avoid possible CVEs affecting the old components. We have a guide that explains the whole process:

https://github.com/bitnami/bitnami-docker-moodle#upgrade-this-application

**Comment by trainingcity** [comment]
MIght want to reopen this issue. I'm struggling with the moodle upgrade process. I started with the bitnami image for moodle 3.5.2 and I am trying to upgrade a test site to 3.6. I don't want to simply use the new bitnami image as I want to be able to keep my site configuration and data.

I was eventually able to complete the upgrade of the site, but I keep getting errors that the "plugins files not writable". I've gone through the permissions on my persistent volumes and I "think" everything is the same. The install process requires you to delete the moodle directory, then copy back in to the newly unzipped version of the moodle directory the "config.php" file, and it seems, the "moodledata" directory.

It is a bit of a nightmare as the new moodle directory seems to be set to 1001:1001 for uid / gid. I tired to get these set to exactly the same user/group I had in my original versions, namely user 1001 and "daemon". This seems to map to "bitnami:daemon" in the running container.

Any ideas welcome, I hate Linux permissions and have never been good at it, the docker container plus any unique bitnami configs are proving to be more than I can handle!

Thoughts?

PS: The containers are sitting behind the outstanding jwilder/docker-gen with nginx-proxy and jrcs/letsencrypt-nginx-proxy-companion. If anyone needs help with that setup, let me know.

docker-compose.yml

version: '3.1'

services:

  moodle.mariadb.training:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: XXXXXX
      MYSQL_DATABASE: bitnami_moodle
      MYSQL_USER: bn_moodle
      MYSQL_PASSWORD: XXXXXX
    expose:
      - 3306
    volumes:
      - /project/docker/volumes/moodle.mariadb.training/bitnami:/bitnami
      - /project/docker/volumes/moodle.mariadb.training/var/lib/mysql:/var/lib/mysql

  moodle.training:
    image: 'private:my_moodle'
    environment:
      - MARIADB_HOST=moodle.mariadb.training
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=XXXXXX
      - MOODLE_DATABASE_NAME=bitnami_moodle
    env_file:
      - moodle_variables.env
    expose:
      - 80
    volumes:
      - /project/docker/volumes/moodle.training:/bitnami
networks:
  default:
    external:
      name: nginx-proxy

**Comment by javsalgar** [comment]
Could you share a file with the permissions of your folders? Something like

```
ls -lar /opt/bitnami > /tmp/output
```

**Comment by trainingcity** [comment]
Thanks for the assistance, much appreciated. 

Below is the output. I was surprised to see everything as "root:root" so I also spun up a new container from the latest bitnami moodle image and double checked, it is also showing "root:root"...

ls -lar /opt/bitnami > /tmp/output

total 32
-rw-r--r-- 1 root root 2017 Nov 28 21:52 updates-ca-cert.pem
drwxr-xr-x 1 root root 4096 Jan 29 20:46 php
drwxr-xr-x 7 root root 4096 Nov 28 21:53 nami
drwxr-xr-x 4 root root 4096 Nov 29 04:16 mysql
lrwxrwxrwx 1 root root   15 Jan 29 20:46 moodle -> /bitnami/moodle
drwxr-xr-x 2 root root 4096 Nov 28 21:52 base
drwxr-xr-x 1 root root 4096 Jan 29 20:46 apache
drwxr-xr-x 1 root root 4096 Nov 29 04:17 ..
drwxr-xr-x 1 root root 4096 Jan 29 20:46 .

**Comment by trainingcity** [comment]
Also noted that this script is missing:

sudo /opt/bitnami/ctlscript.sh stop

**Comment by juan131** [comment]
> I am including the links to the two bitnami moodle upgrade docss:
>
> https://docs.bitnami.com/virtual-machine/how-to/migrate-moodle/
> ....
> Also, the directory structure in the container is not the same as outlined in the above "upgrade" link. In particular, there is no " /opt/bitnami/apps" directory in the current bitnami moodle image/container.

Bitnami VMs and containers do not have the same file structure. They use different tools to unpack/configure the different assets packaged on them. 

The original idea on containers structure was to split the app's data from the rest of the app's files. For instance, if you use the WordPress image, the data is at `/bitnami/wordpress` while the rest of files are at `/opt/bitnami/wordpress`. By mounting a volume at `/bitnami/wordpress`, we exclusively persist the data so you can replace the image with a new one and the app can be upgraded just running `docker-compose restart`.

We found a lot of issues with Moodle since the app's not designed to support this kind of structure, and we decide to persist the whole directory (that implied losing upgradability by replacing the image).

The documents you shared have instructions to upgrade Moodle when using VMs. They're not intended for containers.

> Also noted that this script is missing:
> 
> sudo /opt/bitnami/ctlscript.sh stop

This script is only available on VMS. When using containers, there's an equivalent tool called **"nami"**, for instance, to restart Apache, you can run:

```
sudo nami restart apache
```

**Comment by trainingcity** [comment]
Thanks for the clarification, that definitely helps. I guess the key question I have after completing the moodle upgrade of my container is the error message "plugins files not writable".  If I can fix this, I can simply save the container as a private image and I'm go to go.

Any thoughts on what is causing this problem?

**Comment by juan131** [comment]
I guess it's a problem with the ownership of some of the directories. Could you please run the command below to see if that solves the issue?

```
docker-compose exec moodle chown -R bitnami:daemon /bitnami/moodle
```
