### ISSUE TITLE
Cant upload files of more than 1M (error 413)

### ISSUE THREAD

**Issue by GCBenlloch** [bitnami/bitnami-docker-moodle#72]
**Description**

I've tried to upload a 1M file but filepicker keeps loading for ever and then gives server error.
I've changed `upload_max_filesize = 40M` and `post_max_size = 40M` in `php/conf/php.ini` and reset the apache. I can see in /admin/phpinfo.php the new max size but still cant upload files of more than 1M

Im running moodle moodle:3.4.2 in docker.

When uploading a 1,5M file chrome throws error 413 but I don't know how to solve it

**Comment by juan131** [comment]
Hi @GCBenlloch 

As you mentioned those are the parameter you need to edit (see https://docs.bitnami.com/aws/apps/moodle/#how-to-modify-the-allowed-limit-for-uploaded-files). Could you share the Apache log file (available at **/opt/bitnami/apache/logs/error_log**)? We might get more info from there

**Comment by GCBenlloch** [comment]
I find the error! Moodle was perfectly configured, my error was in my nginx reverse proxy container limiting request to 1M...

Sorry for the inconvinience and thanks for the help!

**Comment by carrodher** [comment]
We are glad that you were able to fix the issue. We are marking this topic as “Closed". If you have any other questions, please do not hesitate to let us know. Feel free to create a new topic referencing to this one if necessary.
