### ISSUE TITLE
Error executing 'postInstallation': Database tables already present, cli installation can not continue

### ISSUE THREAD

**Issue by tomitrescak** [bitnami/bitnami-docker-moodle#77]
**Description**

Moodle does not start,
I am getting following error when running "docker logs moodle_moodle_1"

```
Error executing 'postInstallation': Database tables already present, cli installation can not continue
```

Full log

```
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing moodle
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
Error executing 'postInstallation': Database tables already present, cli installation can not continue.
```

**Steps to reproduce the issue:**

1. docker-compose up -d (with the default file from the documentation)
2. docker logs moodle_moodle_1

**Describe the results you received:**

```
Error executing 'postInstallation': Database tables already present, cli installation can not continue
```

**Describe the results you expected:**

Moodle starts

**Version**

- Output of `docker version`:

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm
```

- Output of `docker info`:

```
Containers: 9
 Running: 5
 Paused: 0
 Stopped: 4
Images: 20
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: PQJL:32XB:Q7RG:BSRE:U46V:AZW7:DAEA:ZRZ4:PSBG:QT5W:NAYV:DAC5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 59
 Goroutines: 71
 System Time: 2018-07-04T00:43:50.9584486Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Comment by tomitrescak** [comment]
OK, I had to delete existing database files so everything then started from scratch.

**Comment by rvallo** [comment]
Hi,
I have the same issue.
If you want to keep the database, copy all files (no directories) from the old moodle folder to a new one and do not overwrite any files.
Then moodle starts.

**Comment by javsalgar** [comment]
Hi @lboclboc, could you show the docker-compose file you are using? It seems to me that the volumes are not fully deleted, otherwise I wouldn't expect this error.

**Comment by lboclboc** [comment]
Hi, I might have caused confusion here. Its the bitnami kubernetes helm chart I am using and that uses this image as I understand. I am very sure the volumes are empty when starting and the database seems to be populated but then I get this error.

**Comment by javsalgar** [comment]
If you are using the Kubernetes helm chart, make sure that there are no PVCs for MariaDB. When you do helm delete the MariaDB volumes do not get deleted, so it seems to me that you may be redeploying the MariaDB with the already existing data. The best way to check it is to look at the MariaDB logs, if it is empty, it should show 'Deploying from scratch'

**Comment by lboclboc** [comment]
No, I have manually removed all files on the volumes and then restarted. But come to think of it. It might actually fail initially for some other problem and then I restart it and get this error. Ill add this intial error I get soon.

**Comment by lboclboc** [comment]
OK, so the mariadb pod seems to start fine with log:
mariadb 15:04:20.52 INFO  ==> ** Starting MariaDB **
2020-06-15 15:04:20 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.22-MariaDB) starting as process 1 ...
2020-06-15 15:04:20 0 [Note] InnoDB: Using Linux native AIO
2020-06-15 15:04:20 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-06-15 15:04:20 0 [Note] InnoDB: Uses event mutexes
2020-06-15 15:04:20 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-06-15 15:04:20 0 [Note] InnoDB: Number of pools: 1
2020-06-15 15:04:20 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-06-15 15:04:20 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2020-06-15 15:04:20 0 [Note] InnoDB: Completed initialization of buffer pool
2020-06-15 15:04:20 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-06-15 15:04:21 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-06-15 15:04:21 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-06-15 15:04:21 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-06-15 15:04:21 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-06-15 15:04:21 0 [Note] InnoDB: Waiting for purge to start
2020-06-15 15:04:21 0 [Note] InnoDB: 10.3.22 started; log sequence number 1625466; transaction id 21
2020-06-15 15:04:21 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
2020-06-15 15:04:21 0 [Note] InnoDB: Buffer pool(s) load completed at 200615 15:04:21
2020-06-15 15:04:21 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-06-15 15:04:21 0 [Note] Server socket created on IP: '0.0.0.0'.
2020-06-15 15:04:21 0 [Warning] 'proxies_priv' entry '@% root@px2moodle-mariadb-0' ignored in --skip-name-resolve mode.
2020-06-15 15:04:21 0 [Note] Reading of all Master_info entries succeeded
2020-06-15 15:04:21 0 [Note] Added new Master_info '' to hash table
2020-06-15 15:04:21 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
Version: '10.3.22-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution

But the moodlepod fails after a while:

Welcome to the Bitnami moodle container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing moodle
moodle  INFO  Preparing PHP environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at px2moodle-mariadb:3306
mysql-c INFO  MySQL server listening and working at px2moodle-mariadb:3306
moodle  INFO  Running Moodle install. Please be patient...
Error executing 'postInstallation': Value to set is empty

**Comment by javsalgar** [comment]
Hi,

This is strange. We cannot reproduce the issue and we test the chart with all major Kubernetes distributions. Could you provide more details about your platform, the storage provisioner you are using, the Kubernetes version, and so on?

**Comment by lboclboc** [comment]
Sure, we are running kubernetes 1.14.2 on Ubuntu-18.04. We use glusterfs for storage

**Comment by javsalgar** [comment]
In order to discard that there is an issue with the persistence, could you try deploying the chart with the persistence disabled? If there are no issues, then we can conclude that the issue lies in the glusterfs storage.

**Comment by lboclboc** [comment]
Sorry, with persistence set to false for both moodle and mariadb its the same error:
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing moodle
moodle  INFO  Preparing PHP environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at px2moodle-mariadb:3306
mysql-c INFO  MySQL server listening and working at px2moodle-mariadb:3306
moodle  INFO  Running Moodle install. Please be patient...
Error executing 'postInstallation': Value to set is empty

**Comment by lboclboc** [comment]
These are my values:
image:
  registry: docker.io
  repository: bitnami/moodle
  tag: 3.8.3-debian-10-r0

moodleEmail: xxxxxx

smtpHost: smtp.xxxxxxxx
smtpPort: 25

mariadb:
  enabled: true
  db:
    user: bn_moodle
    password: bn_moodle

  master:
    persistence:
      enabled: false
      existingClaim: px2moodle.mariadb

service:
  type: ClusterIP

ingress:
  enabled: true

persistence:
  enabled: false
  existingClaim: px2moodle

moodleSkipInstall: "no"

externalDatabase:
  user: bn_moodle
  password: bn_moodle


+ these overriding values:
ingress:
  hosts:
  - name: px2moodle-dev.scs.domain


Regards, Lars

**Comment by javsalgar** [comment]
Hi,

I see that you are setting values in the externalDatabase section, could you confirm if you want to use an already existing database or the bundled mariadb? Also, could you try first deploying with the default values, this way we can understand more details of the issue.

**Comment by lboclboc** [comment]
Im trying to use the bundled mariadb. Ill do a clean install with only default values.

**Comment by kacperpabian** [comment]
I seem to be getting the same issue. Did you find the solution @lboclboc ?

**Comment by kacperpabian** [comment]
> I seem to be getting the same issue. Did you find the solution @lboclboc ?

Great, I was using stable image instead of bitnami. Changing to bitnami resolved it.

**Comment by javsalgar** [comment]
Are you also using an external database @kacperpabian ?

**Comment by kacperpabian** [comment]
Yes I'm using external database. I switched service to ClusterIP and extended livenessProbe and it works.

**Comment by javsalgar** [comment]
Could you share the values you changed so another person can benefit from that?
