### ISSUE TITLE
Caching modules not enabled in PHP

### ISSUE THREAD

**Issue by jmayermsi** [bitnami/bitnami-docker-moodle#78]
It doesn't look like any of the caching modules have been installed in PHP. In the cache configuration section of moodle you are not able to add any instances for Memcached or Redis or any other caching modules. Is there something I am missing? I have installed Moodle locally and these are available but not using the container version of Moodle or the helm package.

**Comment by tompizmor** [comment]
You can enable the APCu cache easily by adding/uncommenting the following code into the `/opt/bitnami/php/conf/php.ini` file:

```
extension = apcu.so
```

After that, restart apache and you should be able to use this cache:

```
nami restart apache
```

**Comment by jmayermsi** [comment]
Thanks for the info Tom. I am interested in using redis or memcached since APCu doesn't seem to be ideal for my use case. 

AS noted here

Another important thing to understand about the APC store is that it provides no garbage cleaning, or storage reclamation facilities. As such cache data will persist there until APC is restarted or the store is purged. On top of that once the store is full requests to store information within the cache fail until there is once more sufficient space. Because of this it is recommended that you regularly purge or restart APC. Also recommended is to map a secondary application cache instance to any definition with the APC mapped. This ensures that if it does indeed full up that an alternative cache is available.


https://docs.moodle.org/34/en/APC_user_cache_(APCu)

**Comment by tompizmor** [comment]
Thanks for the information. We have included it in our backlog and it will be considered for future application versions.

We will update this thread as soon as we have more news.

**Comment by jmayermsi** [comment]
Fantastic. I tried to manually add support for redis using PECL  by SSHing into the  container but upon reboot of the container the library seems to disappear. Any suggestions? Is it possible that that portion of the container is not persistent?

**Comment by tompizmor** [comment]
Hi @jmayermsi,

There is something you can do. You can build your custom docker image so the changes are persistent. 
For example, you can use this Dockerfile as an example of a custom Moodle image that is just like the bitnami one but also install the vim editor:

```
FROM bitnami/moodle:latest
RUN install_packages vim
```

Then just build the docker image:

```
docker build -t jmayermsi/moodle /path/to/Dockerfile
```

In your case, instead of install the `vim` package you can use PECL to install the library or do any customization.

**Comment by ceefour** [comment]
Hi @tompizmor , is it possible to include caching modules and igbinary into bitnami docker?

While it's _possible_ to build a custom docker image, it requires a steep learning curve and knowing about bitnami container internals. It'd be great if this can be supported from the container.

Is there a good reason why these are intentionally left out? I think if some users don't use them, it has no negative effect on runtime performance/memory usage. But even if that's the case, bitnami can provide another variant with docker tags, e.g. `bitnami/moodle:latest` contain everything and `bitnami/moodle:lite` excludes these modules.

**Comment by carrodher** [comment]
Hi, we have at task included in our backlog. As the impact of the issue is limited and not critical, there are no immediate plans to work on it. Nevertheless, it will be considered for future application versions.

In the meantime, you can use the provided workaround. We will update this thread as soon as we have more news.
