### ISSUE TITLE
Persistence of Moodle data incomplete

### ISSUE THREAD

**Issue by zimcke** [bitnami/bitnami-docker-moodle#80]
**Description**
I have the Moodle application running with persistence on a server, and it works fine. However, I am trying to set up an additional (local) Moodle application on the same machine for testing purposes. My problem is that I cannot get the Moodle data to be persisted in a similar way. More specifically the `moodle` folder doesn't persist the Moodlee core code and plugins in my volume `moodle_data`, only the `moodledata` folder is there. Hence I cannot add my plugins, theme, etc. to the local file tree. Could this be related to the fact that I already have a Moodle application running on the same machine?

Another issue is that I cannot seem to remove the volumes after deletion of the containers. Even the `docker volume prune` doesn't detect the created folders and files. I don't have sudo access to delete these folders myself.

**Steps to reproduce the issue:**

1. I used the following commands to create the `mariadb` and `moodle` container:

``` 
docker run -d --name test-mariadb --net test-environment-moodle-tier \
-e MARIADB_PORT_NUMBER=3307 \
-e MARIADB_DATABASE=test-mariadb \
-e ALLOW_EMPTY_PASSWORD=yes \
-e MARIADB_USER=bn_moodle \
-v /home/code/testenvironment/mariadb_data:/bitnami \
bitnami/mariadb 

docker run -d -p 18889:80 -p 18890:443 --name test-moodle --net test-environment-moodle-tier \
-e MARIADB_PORT_NUMBER=3307 \
-e ALLOW_EMPTY_PASSWORD=yes \
 -e MOODLE_DATABASE_USER=bn_moodle \
 -e MOODLE_DATABASE_NAME=test-mariadb \
-v /home/code/testenvironment/moodle_data:/bitnami bitnami/moodle
```
2. Inspect the persisted folder when Moodle is accessible from the browser `~/testenvironment/test/moodle_data/moodle$`
3. Only the folder `moodledata` is visible from that path. I would expect the Moodle core to be here as well (and that's how it is with my other application)

**Describe the results you received:**

I cannot see the Moodle code, plugins, themes, etc. in my persisted folder. I can also not delete persisted folder after deletion of the containers with `docker volume prune`.

**Describe the results you expected:**

I expect to see the Moodle code, plugins, themes, etc. in my persisted folder, to be able to modify the code and add my own plugins directly to the file tree.

**Additional information you deem important (e.g. issue happens only occasionally):**

My other Moodle application is being run with the following commands:

``` 
docker run -d --name mariadb-master --net moodle-tier \
-e MARIADB_ROOT_PASSWORD=*** \
-e MARIADB_REPLICATION_MODE=master \
-e MARIADB_REPLICATION_USER=*** \
-e MARIADB_REPLICATION_PASSWORD=*** \
-e MARIADB_USER=code \
-e MARIADB_PASSWORD=*** \
-e MARIADB_DATABASE=mariadb-master -v /export/home1/code/persistence/mariadb_data:/bitnami bitnami/mariadb

docker run -d --name mariadb-slave --link mariadb-master:master --net moodle-tier\
 -e MARIADB_REPLICATION_MODE=slave \
-e MARIADB_REPLICATION_USER=*** \
-e MARIADB_REPLICATION_PASSWORD=*** \
-e MARIADB_MASTER_HOST=master \
-e MARIADB_MASTER_ROOT_PASSWORD=**** \
-v /export/home1/code/persistence/mariadb_slave_data:/bitnami bitnami/mariadb

docker run -d -p 80:80 -p 443:443 --name moodle --net moodle-tier \
-e MARIADB_PASSWORD=*** \
-e MARIADB_HOST=mariadb-master \
-v /export/home1/code/persistence/moodle_data:/bitnami bitnami/moodle
```
**Version**

- Output of `docker version`:

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:07:48 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:07:48 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Docker info output:
Containers: 9
 Running: 5
 Paused: 0
 Stopped: 4
Images: 7
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /export/home1/docker/aufs
 Backing Filesystem: extfs
 Dirs: 60
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-133-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.682 GiB
Name: code
ID: K3KJ:6WLL:MSKD:RJEU:VZMG:WPO4:GHKV:AX47:I7XE:W4AF:BJ54:DB7I
Docker Root Dir: /export/home1/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
> I have the Moodle application running with persistence on a server, and it works fine

Is that Moodle app also based on a Bitnami Moodle container image?

> Only the folder moodledata is visible from that path

What version of Moodle image are you using? The whole application is persisted on that directory since the version **3.4.0**. Therefore, it won't be persisted if you're using a previous version.

What do you obtain when running the commands below?

```
docker logs moodle
docker exec moodle ls -la /bitnami/moodle
```

**Comment by zimcke** [comment]
My other Moodle app is also based on a Bitnami Moodle container image, for version 3.4.1 (but the container has recently been updated to Moodle version 3.5).

I've tried with both Moodle 3.4.1 and a Moodle 3.5 version. Both gave the same issue. I also tried different paths for the volume, with the same result. 

`docker logs moodle` gives me the output of my Moodle container(s) as expected. Since thy other Moodle application is being used a lot, I see all the output from that application.

`docker exec moodle ls -la /bitnami/moodle` indeed shows me the complete file tree from the whole Moodle directory. But again this is the file tree from my Moodle application that is used for production (with my custom plugins etc.), not the one I try to set up for testing purposes.

How can I make sure the two Moodle applications can be persisted correctly simultaneously?

**Comment by juan131** [comment]
Hi @zimcke 

> docker exec moodle ls -la /bitnami/moodle indeed shows me the complete file tree from the whole Moodle directory. But again this is the file tree from my Moodle application that is used for production (with my custom plugins etc.), not the one I try to set up for testing purposes.

Do you have two containers using the same name??? It's unclear to me how you could access the file tree from your production container when running the command on your "dev" container.
Are you attaching the same volume to both containers?

**Comment by zimcke** [comment]
No, of course not, they don't use the same volumes. They also have different names ('moodle' and 'test-moodle'). For 'test-moodle' I can only see the 'moodledata' in my file tree when I use the command you suggested. `docker logs` gives me for both containers the right output of the Moodle containers.

Now when I try to replicate my actions from before and set up a new dev container to check if the same happens, I have trouble getting the Moodle application to connect to a new database (using a different mariadb port, docker network, name and volume). Maybe it is not a good approach to run two applications on the same server?

**Comment by zimcke** [comment]
Hi Juan,

Thank you for the suggestion of the host parameter. I had tried that before, but probably not in the right combination with the other environment parameters. My dev container works fine now and no issues with persisting the data with a bind mount. 
Hopefully your example code will make it easier for other inexperienced users like me to set up multiple applications! Thanks a lot!

**Comment by juan131** [comment]
Hi @zimcke 

I'm glad that you were able to fix the issue with that little example. 

If you have any other questions/issues, please do not hesitate to open a new issue.
