### ISSUE TITLE
Persistent docker-compose failing without `sudo`

### ISSUE THREAD

**Issue by mmnaseri** [bitnami/bitnami-docker-moodle#81]
**Description**

The script hangs after I run `docker-compose up` on ` MySQL server listening and working at mariadb:3306.

This issue occurs when I try to use the suggested configuration for a persistent docker image, and after I fix the permission error for the MariaDB folder.

**Steps to reproduce the issue:**

1. Create the `docker-compose.yml` file based on the example in the README file.
2. Change `/path/to/...` variables to my local directories (`/home/myuser/moodle/db` and `/home/myuser/moodle/data`)
3. Change the owner of the `db` directory to `1001` to avoid the permission issue.
4. Run `docker-compose up`

**Describe the results you received:**

The script executes successfully up until the line indicated above and hangs:

    moodle_1   | mysql-c INFO  MySQL server listening and working at mariadb:3306

**Describe the results you expected:**

I expected it to continue to the next few lines:

```
moodle_1   | moodle  INFO  Configuring Cron Jobs...
moodle_1   | moodle  INFO
moodle_1   | moodle  INFO  ########################################################################
moodle_1   | moodle  INFO   Installation parameters for moodle:
moodle_1   | moodle  INFO     Persisted data and properties have been restored.
moodle_1   | moodle  INFO     Any input specified will not take effect.
moodle_1   | moodle  INFO   This installation requires no credentials.
moodle_1   | moodle  INFO  ########################################################################
moodle_1   | moodle  INFO
moodle_1   | nami    INFO  moodle successfully initialized
moodle_1   | INFO  ==> Starting moodle...
moodle_1   |
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue happens every time.

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false```

- Output of `docker info`:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-7-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 15.61GiB
Name: ultimatehome
ID: VBDM:2HCG:AGG3:UJJ2:O6IB:AVI4:DCHC:AGGU:R7U7:3RPU:WTIY:L55H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.5.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.1.0f  25 May 2017```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
I am using `docker` with `sudo` and `docker-compose` without.

I can only proceed if I prefix `docker-compose` with `sudo`, which is something I have read you shouldn't do.

**Comment by mmnaseri** [comment]
So, I think I have fixed this by doing two configuration changes:

1. I have added my running user to `docker` group (effectively the same as running as `root`, so not the safest option).
2. I added `user: root` to the `mariadb` service section which seems to have fixed the permission issue as well.

**Comment by tompizmor** [comment]
Hi @mmnaseri,

Please see my below comments:

> The script hangs after I run docker-compose up on ` MySQL server listening and working at mariadb:3306.

Is not really hanged. Is just installing Moodle that can take a couple of minutes. We will improve the initialization output to give better feedback to the user.

>1. I have added my running user to docker group (effectively the same as running as root, so not the safest option).

Yes, normally you do that step as part of docker installation.

>2. I added user: root to the mariadb service section which seems to have fixed the permission issue as well.

That should not be needed as you have already configured the permissions of your local volume. So you should decide what do you prefer. Either run the Mariadb container as root user or as non-root user and configure the permissions of the local volume first manually.

**Comment by mmnaseri** [comment]
Thanks for the response. I opted to add `user: root` instead of doing `chown` since I want to be able to deploy this out-of-the-box with a docker-compose command instead of having a local shell script. The installation step takes a few minutes and then passes as you suggested. It would be great if you could add some sort of progress output to indicate that the startup phase hasn't simply hung up.

**Comment by tompizmor** [comment]
>  It would be great if you could add some sort of progress output to indicate that the startup phase hasn't simply hung up

Yes, we have noted the issue and we will improve the output in the next releases. I will make sure to update this issue once that happens.

**Comment by tompizmor** [comment]
Just a quick note to let you know that now the Moodle container logs this line before executing the long-running installation command.

```
moodle_1   | moodle  INFO  Running Moodle install. Please be patient...
```

**Comment by armenic** [comment]
Thank you developers for a very handy note and as a note to users that this can take ~15 minutes, so really be patient and don't think that you did something wrong :)
