### ISSUE TITLE
Q : how to add smtp environment variables after containers are running ?

### ISSUE THREAD

**Issue by gmolveau** [bitnami/bitnami-docker-moodle#85]
Hi, I launched moodle via docker-compose and tried to set-up the smtp via the moodle interface but it seems that the container can't reach the smtp server (google).
Would it work if I set up the environement variables ? If so, how do I set up those environment variables after I have launched those containers ?

Thank's for your help :)

**Comment by GaelC92** [comment]
Have a look at the security features of gmail – it will block unauthorized smtp.

**Comment by andresbono** [comment]
Hi @gmolveau,

The setup of SMTP  in an automated way is done during the first run of the application only. So using the environment variables is not going to work. Did you make sure that the SMTP options were correctly set? As @GaelC92 is mentioning you need to enable auth in your SMTP configuration.

Have a look at https://docs.bitnami.com/aws/apps/moodle/configuration/configure-smtp/ in case it helps you to configure SMTP in Moodle.

**Comment by gmolveau** [comment]
@GaelC92 yep I enabled "unsecured apps" but it still does not work.

**Comment by GaelC92** [comment]
You need to declare the up address of your Moodle server as well.  Google is very picky on what it accepts. 

-- 
Gaël Canal
LGPSE

**Comment by gmolveau** [comment]
What do you mean by "up address" @GaelC92  ? Thank's for your answer :-)

**Comment by GaelC92** [comment]
IP :) 


-- 
Gaël Canal
LGPSE

**Comment by gmolveau** [comment]
Do you have a direct link to this declaration page ? I can't find it. I installed "email test" plugin to see what's going on and got : 

```
2018-10-28 15:09:26	SMTP ERROR: Failed to connect to server: Connection timed out (110)
2018-10-28 15:09:26	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```

**Comment by gmolveau** [comment]
Ok nevermind. The problem was from my server provider (scaleway) where you have to specifically check out "block smtp".

https://community.online.net/t/solved-smtp-connection-blocked/2262

Thank's anyway for your help guys !

**Comment by andresbono** [comment]
@gmolveau, that's great to hear! 🎉
