### ISSUE TITLE
Will Not Install for Azure Database for MySQL PaaS

### ISSUE THREAD

**Issue by enhendrickson** [bitnami/bitnami-docker-moodle#86]
The installer starts but ends abruptly with an obtuse error.  It appears that it provisions the database but none of the tables.  I wonder if this has anything to do with Azure's strange convention that requires a user to have @server_name appended to the connection?  Because the error is so vague, I can't troubleshoot it further.

**Steps to reproduce the issue:**

1. Create docker container as normal (per this documentation); example:

```
docker run -d --name moodle -p 80:80 -p 443:443 \
  -e MYSQL_CLIENT_CREATE_DATABASE_NAME=moodle \
  -e MYSQL_CLIENT_CREATE_DATABASE_USER=moodle \
  -e MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=password1234 \
  -e MARIADB_HOST=shareddevdb.mysql.database.azure.com \
  -e MOODLE_DATABASE_USER=mysql-admin@shareddevdb \
  -e MOODLE_DATABASE_PASSWORD=*************** \
  -e MARIADB_ROOT_PASSWORD=*************** \
  -e MARIADB_ROOT_USER=mysql-admin@shareddevdb \
  -e MOODLE_DATABASE_NAME=moodle \
  --net moodle-tier \
  --volume moodle_data:/bitnami \
  bitnami/moodle:latest
```

2. Include environment variables that point at Azure Database for MySQL host
3. Log the docker container and watch it fail.

**Describe the results you received:**

> nami    INFO  Initializing apache
> apache  INFO  ==> Reconfiguring PID file location...
> apache  INFO  ==> Configuring dummy certificates...
> nami    INFO  apache successfully initialized
> nami    INFO  Initializing php
> nami    INFO  php successfully initialized
> nami    INFO  Initializing mysql-client
> mysql-c INFO  Trying to connect to MySQL server
> mysql-c INFO  Found MySQL server listening at shareddevdb.mysql.database.azure.com:3306
> mysql-c INFO  MySQL server listening and working at shareddevdb.mysql.database.azure.com:3306
> mysql-c INFO  ==> Creating database moodle...
> mysql-c INFO  ==> Granting access to moodle to the database moodle...
> mysql-c INFO 
> mysql-c INFO  ########################################################################
> mysql-c INFO   Installation parameters for mysql-client:
> mysql-c INFO     Database User created: moodle
> mysql-c INFO     Database Name created: moodle
> mysql-c INFO     Database Password created: **********
> mysql-c INFO     Database Host: shareddevdb.mysql.database.azure.com
> mysql-c INFO     Database Port: 3306
> mysql-c INFO     Database Root User: mysql-dev-admin@shareddevdb
> mysql-c INFO     Database Root Password: **********
> mysql-c INFO   (Passwords are not shown for security reasons)
> mysql-c INFO  
> ########################################################################
> mysql-c INFO 
> nami    INFO  mysql-client successfully initialized
> nami    INFO  Initializing libphp
> nami    INFO  libphp successfully initialized
> nami    INFO  Initializing moodle
> mysql-c INFO  Trying to connect to MySQL server
> mysql-c INFO  Found MySQL server listening at shareddevdb.mysql.database.azure.com:3306
> mysql-c INFO  MySQL server listening and working at shareddevdb.mysql.database.azure.com:3306
> moodle  INFO  Running Moodle install. Please be patient...
> **_Error executing 'postInstallation': Program exited with exit code 1_**

**Describe the results you expected:**

When I run this against a server that isn't Azure Database for MySQL (such as at docker.for.mac.localhost against a running MAMP Pro MySQL instance), the install completes as desired, the container remains operational, and Moodle will load

**Additional information you deem important (e.g. issue happens only occasionally):**

This is the same error I receive when I use the Helm Chart.  Likely for the same root cause.  

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
Containers: 22
 Running: 21
 Paused: 0
 Stopped: 1
Images: 54
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: NTFM:3O4T:I7RG:25PC:CTSJ:6I6X:KRCB:3GXF:CKRS:4FFY:OEHL:67JU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 140
 Goroutines: 141
 System Time: 2018-12-10T15:16:56.2447274Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by rafariossaa** [comment]
Hi @enhendrickson ,
  In order to connect to Azure Database for MySQL, you have to check if you are using SSL or not, and also you need to add the IP where you are connecting from into the "connection security" settings of the Azure Database for MySQL that you have created.

Best regards,
Rafael Rios

**Comment by enhendrickson** [comment]
I have disabled the requirement for SSL and the IP is allowed.  When the IP isn’t there is a connection error that says that.  The same could be said for SSL this error is happening after the connection is made.  See logs above.

**Comment by enhendrickson** [comment]
@rafariossaa are you saying that the container should work against azure mysql? It still does not and I believe I have turned off SSL.

**Comment by rafariossaa** [comment]
Hi @enhendrickson ,
  It should work. In general these are the things to into account:
   - That the username have '@' in the name
   - Disable SSL, or configure SSL properly in the application. This depends on how the application handle the connection. Some times you will need a plugin, or a patch, or just configuration.
   - Enable the IP(s) from where you are going to connect to the database.

  Could you use a mysql client and try to connect to Azure Mysql ? Just to verify that you are using the right crendentials, and test if you can connect from the IP set .

Thanks forehand
Rafael Rios

**Comment by enhendrickson** [comment]
@rafariossaa

I have already connected via MySQL Workbench successfully-from the same source  IP as when I am locally trying to run the container.  

I am encouraged to know that it should work following my above steps and that I think you’re suggesting that you’ve gotten it to work before when creating a new install of Moodle like me (where the DB has nothing in it).  That said, here are a few other points of confusion,

- if I remove all whitelisting of IPs from Azure MySQL, then I get a different error in the container startup than the one that I getting now
- if I take off the @ username then I get a different error than I am getting now 
- if I enable SSL-only in Azure MySQL then I get a different error than I am getting now

All three of the above circumstances where I receive errors these errors appear to be further up in the process than the error that this issue reflects.  Also, don’t forget that if I don’t pre-create the MySQL Moodle DB, the container startup successfully creates the empty database - wouldn’t that suggest it’s successfully connecting to the MySQL server??  Again, while it successfully creates the database, because of this error, no tables ever get created.

**Comment by enhendrickson** [comment]
@rafariossaa I tried working on this a bit more today it's definitely not working as designed.  
<img width="587" alt="shareddevdb_-_microsoft_azure" src="https://user-images.githubusercontent.com/2226780/49977367-bc14c100-ff0b-11e8-8ee9-2f8cd16cd2d8.png">

**Comment by enhendrickson** [comment]
<img width="1277" alt="ehendrickson_ _-bash_ _159x24" src="https://user-images.githubusercontent.com/2226780/49977418-e23a6100-ff0b-11e8-89d7-4ea493491e84.png">

**Comment by enhendrickson** [comment]
<img width="860" alt="connection_security_-_microsoft_azure" src="https://user-images.githubusercontent.com/2226780/49977916-d2238100-ff0d-11e8-9388-b6a947b518a3.png">

**Comment by enhendrickson** [comment]
This works, 

<img width="1136" alt="manage_server_connections" src="https://user-images.githubusercontent.com/2226780/49978067-61c92f80-ff0e-11e8-8bfa-fae9f9b5e101.png">

**Comment by enhendrickson** [comment]
<img width="431" alt="manage_server_connections" src="https://user-images.githubusercontent.com/2226780/49978090-7c9ba400-ff0e-11e8-9ecf-46855fe75094.png">

**Comment by enhendrickson** [comment]
@rafariossaa FYI

**Comment by enhendrickson** [comment]
@rafariossaa I have fixed my issue.  Turns out that I was using the Basic SKU from Azure Database from MySQL and that doesn't allow you to set innodb_file_per_table to YES.  I switched to the General Purpose SKU and now I have set it to YES and the install completes no problem.  I also confirmed that this was 100% my issue by turning this setting off in localhost and the non-Azure setup that is referenced as working above, suddenly experienced the same issue.  The actual root cause for why this worked is that Moodle requires ROW_FORMAT=​COMPRESSED on some of their tables.  This won't work if innodb_file_per_table is NO.  See: https://dev.mysql.com/doc/refman/5.7/en/innodb-compression-syntax-warnings.html

Azure does in fact set this innodb_file_per_table to NO by default.  So, that's worth a bit of help to anyone who gets stuck on this in the future.

**Comment by rafariossaa** [comment]
Hi @enhendrickson ,
  Sorry for the long delay. I'm happy to see that you managed to get it working. 
  I haven't tried this configuration, my suggestions were based in what we need to do to connect other applications.
  Thank you very much for sharing the solution. It makes sense that you can not set innodb_file_per_table, or any other setting like this one, because it is a managed DB so you should not have to take care of this kind of parametrization. After all it seems that moodle is not ready for this kind of configuration.

Best regards,
Rafael Rios Saavedra

**Comment by rafariossaa** [comment]
Hi @enhendrickson ,
  Sorry for the long delay. I'm happy to see you managed to solve the issue.
  Thanks for sharing your solution. For me, it makes sense that you can no change parameters of that kind. In managed db you delegate that responsibility to the managers of the database.
  After all, It seems that moodle is not ready for this kind of configuration.

Thanks you very much,
Rafael Rios.

**Comment by karl18** [comment]
Hi, I'm expiring the same issue when deploying the latest image on AKS using a (mysql_client_create/pre-exisiting) db on Azure MySQL db for Moodle 3.9.0. I believe I followed solution provided by @enhendrickson but all database settings are set correctly! I'm always getting this error:

`
apache  TRACE Skipping reload: com.bitnami.apache not running
moodle-5456dfdd87-tnr66 moodle moodle  INFO  Preparing PHP environment...
moodle-5456dfdd87-tnr66 moodle php     TRACE [normalize] File normalization: conf -> /opt/bitnami/php/conf
moodle-5456dfdd87-tnr66 moodle php     TRACE [read] File normalization: /opt/bitnami/php/conf/php.ini -> /opt/bitnami/php/conf/php.ini
moodle-5456dfdd87-tnr66 moodle php     TRACE [normalize] File normalization: conf -> /opt/bitnami/php/conf
moodle-5456dfdd87-tnr66 moodle php     TRACE [puts] File normalization: /opt/bitnami/php/conf/php.ini -> /opt/bitnami/php/conf/php.ini
moodle-5456dfdd87-tnr66 moodle moodle  TRACE [exists] File normalization: /bitnami/moodle/.initialized -> /bitnami/moodle/.initialized
moodle-5456dfdd87-tnr66 moodle moodle  TRACE [mkdir] File normalization: /bitnami/moodle/moodledata -> /bitnami/moodle/moodledata
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [normalize] File normalization: data -> /opt/bitnami/mysql/data
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [normalize] File normalization: data -> /opt/bitnami/mysql/data
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [normalize] File normalization: logs -> /opt/bitnami/mysql/logs
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [normalize] File normalization: logs -> /opt/bitnami/mysql/logs
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [normalize] File normalization: lib -> /opt/bitnami/mysql/lib
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [normalize] File normalization: lib -> /opt/bitnami/mysql/lib
moodle-5456dfdd87-tnr66 moodle mysql-c INFO  Trying to connect to MySQL server
moodle-5456dfdd87-tnr66 moodle mysql-c INFO  Found MySQL server listening at dex-infrastructure-we.mysql.database.azure.com:3306
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [canConnect] Testing connection with 'moodle@dex-infrastructure-we' user
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [showDatabases] Getting databases for 'moodle@dex-infrastructure-we' user
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hdex-infrastructure-we.mysql.database.azure.com -umoodle@dex-infrastructure-we -pM4aUysgDAGaRaPxtkD7w1tfMZ3V7oY -e SHOW DATABASES;
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [execute] Result: {"code":0,"stdout":"information_schema\nmoodle\n","stderr":""}
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [showDatabases] Databases: information_schema
moodle-5456dfdd87-tnr66 moodle moodle
moodle-5456dfdd87-tnr66 moodle
moodle-5456dfdd87-tnr66 moodle mysql-c TRACE [canConnect] Connection with 'moodle@dex-infrastructure-we' user is successful
moodle-5456dfdd87-tnr66 moodle mysql-c INFO  MySQL server listening and working at dex-infrastructure-we.mysql.database.azure.com:3306
moodle-5456dfdd87-tnr66 moodle moodle  INFO  Running Moodle install. Please be patient...
moodle-5456dfdd87-tnr66 moodle php     TRACE [normalize] File normalization: bin -> /opt/bitnami/php/bin
moodle-5456dfdd87-tnr66 moodle php     TRACE [normalize] File normalization: bin -> /opt/bitnami/php/bin
moodle-5456dfdd87-tnr66 moodle php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php admin/cli/install.php,--lang=en,--chmod=2775,--wwwroot=http://localhost:80,--dataroot=/bitnami/moodle/moodledata,--dbtype=mariadb,--dbhost=dex-infrastructure-we.mysql.database.azure.com,--dbport=3306,--dbname=moodle,--dbuser=moodle@dex-infrastructure-we,--dbpass=M4aUysgDAGaRaPxtkD7w1tfMZ3V7oY,--adminuser=user,--adminpass=bitnami,--adminemail=sre_team@durstexpress.eu,--fullname="New Site",--shortname="New Site",--non-interactive,--allow-unstable,--agree-license,--skip-database
moodle-5456dfdd87-tnr66 moodle php     TRACE [runProgram] Executing internal command: /opt/bitnami/php/bin/php ["admin/cli/install.php","--lang=en","--chmod=2775","--wwwroot=http://localhost:80","--dataroot=/bitnami/moodle/moodledata","--dbtype=mariadb","--dbhost=dex-infrastructure-we.mysql.database.azure.com","--dbport=3306","--dbname=moodle","--dbuser=moodle@dex-infrastructure-we","--dbpass=M4aUysgDAGaRaPxtkD7w1tfMZ3V7oY","--adminuser=user","--adminpass=bitnami","--adminemail=sre_team@durstexpress.eu","--fullname=\"New Site\"","--shortname=\"New Site\"","--non-interactive","--allow-unstable","--agree-license","--skip-database"]
moodle-5456dfdd87-tnr66 moodle php     TRACE [runProgram] RESULT: {"code":1,"stderr":"","stdout":"                                 .-..-.       \n   _____                         | || |       \n  /____/-.---_  .---.  .---.  .-.| || | .---. \n  | |  _   _  |/  _  \\/  _  \\/  _  || |/  __ \\\n  * | | | | | || |_| || |_| || |_| || || |___/\n    |_| |_| |_|\\_____/\\_____/\\_____||_|\\_____)\n\nMoodle 3.9 (Build: 20200615) command line installation program\n== Environment ==\n!! database mariadb (5.6.42.0) !!\n[System] version 10.2.29 is required and you are running 5.6.42.0 - \n\n"}
moodle-5456dfdd87-tnr66 moodle Error executing 'postInstallation': Program exited with exit code 1` 

my configuration looks like this:

`
  MARIADB_HOST: "dex-infrastructure-we.mysql.database.azure.com"
  MOODLE_DATABASE_NAME: "moodle"
  MOODLE_DATABASE_USER: "moodle@dex-infrastructure-we"
  #MYSQL_CLIENT_CREATE_DATABASE_NAME: "moodle"
  #MYSQL_CLIENT_CREATE_DATABASE_USER: "moodle"
  #MYSQL_CLIENT_CREATE_DATABASE_PASSWORD: "Password1234"
  MARIADB_ROOT_USER: "X63C1VrB9C@dex-infrastructure-we"
  NAMI_LOG_LEVEL: trace8
  MOODLE_USERNAME: "user"
  MOODLE_PASSWORD: "bitnami"
  MOODLE_EMAIL: "sre_team@durstexpress.eu"
  MARIADB_PORT_NUMBER: "3306"
  ALLOW_EMPTY_PASSWORD: "no"
  MOODLE_SKIP_INSTALL: "yes"

  #PHP Environment Variables
  PHP_MEMORY_LIMIT: "256M"

  #SMTP Configuration
  SMTP_HOST: "smtp.sendgrid.net"
  SMTP_PORT: "587"
  SMTP_USER: "apikey"
  SMTP_PROTOCOL: "tls"`

So the question, If what I'm doing is right or not? And according to this issue, It's already possible to connect to Azure MySQL DB v5.7 without issues. I can connect to the db

**Comment by enhendrickson** [comment]
@karl18 are you using Azure MySQL or MariaDB?  It looks like the version reported back is a MySQL version (5.6.42.0), but since you're using the MariaDB environment variables it's expecting to see something in the 10.2.x line.

**Comment by karl18** [comment]
@enhendrickson I'm using Azure MySQL, same envs that you used above: "MARIADB_HOST=shareddevdb.**mysql.database.azure.com**" but according to this post and the test you tried with Azure MySQL, it worked with you, or ? I know it was from some time ago, but I'm trying to find a solution :)

**Comment by enhendrickson** [comment]
@karl18 right; it matches mine from two years ago.  My point is that the versions they're complaining about appear to be because they think you're using MariaDB when in fact you are not.  You should see if they've changed the environment variable names or some other way to indicate MySQL vs MariaDB.

**Comment by karl18** [comment]
@enhendrickson Ahh got it, I appreciate your help. Will try to check the env names again.
