### ISSUE TITLE
The container from a MariaDB does not rise

### ISSUE THREAD

**Issue by btow** [bitnami/bitnami-docker-moodle#88]
The container from the database does not rise either manually or in composition

    root@pnevmoslon:/home/lea32/moodle# docker network create moodle-tierError response from daemon: network with name moodle-tier already exists
    root@pnevmoslon:/home/lea32/moodle# docker run -d --name mariadb \
    >  -e ALLOW_EMPTY_PASSWORD=yes \
    >  -e MARIADB_USER=bn_moodle \
    >  -e MARIADB_DATABASE=bitnami_moodle \
    >  -v /path/to/mariadb-persistence:/bitnami \
    >  --net moodle-tier \
    >  bitnami/mariadb:latest
    Unable to find image 'bitnami/mariadb:latest' locally
    latest: Pulling from bitnami/mariadb
    656ca9fc9486: Pull complete 
... - " -

    Digest: sha256:33c939f4950f8d4b094d411e9ae2b74152bab6c162ff88f0ce59b17f7bb9e73b
    Status: Downloaded newer image for bitnami/mariadb:latest
    a928f912c9e39064c7319768184d550ffca05dfec05d763dc9211d3a68f80508
    root@pnevmoslon:/home/lea32/moodle# docker run -d -p 80:80 -p 443:443 --name moodle \
    >  -e ALLOW_EMPTY_PASSWORD=yes \
    >  -e MOODLE_DATABASE_USER=bn_moodle \
    >  -e MOODLE_DATABASE_NAME=bitnami_moodle \
    >  --net moodle-tier \
    >  --volume /path/to/moodle-persistence:/bitnami \
    >  bitnami/moodle:latest
    Unable to find image 'bitnami/moodle:latest' locally
    latest: Pulling from bitnami/moodle
    656ca9fc9486: Already exists 
    3f72622ff128: Pull complete 
... - ' - ...

    Digest: sha256:6e410e007ca8bf8bfc2e1dbc3d02445928469d7bd59d0ba8666f83a8f76b0496
    Status: Downloaded newer image for bitnami/moodle:latest
    1cdee497e0e0925ffab6f0291aeb1535156967682bf201151e445df80eaadd10
    root@pnevmoslon:/home/lea32/moodle# docker ps
    CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS               PORTS                                                                  NAMES
    1cdee497e0e0        bitnami/moodle:latest               "/app-entrypoint.s..."   10 seconds ago      Up 8 seconds            0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                               moodle

**Comment by tompizmor** [comment]
If you execute the command without the daemon option (`-d`), you will see an error.

With the following line, you are mounting a local volume (`/path/to/moodle-persistence`) that must exist and have proper permissions configured. Permissions of mounted volumes are very important as the MariaDB image is non-root by default.

`>  --volume /path/to/moodle-persistence:/bitnami \`

Are you interested in using local volumes? Or you can also use docker-volumes? The easiest way to get started with Moodle container is the second one. You only need to clone the repository and run `docker-compose up` in the same directory containing the `docker-compose.yml` file.

**Comment by btow** [comment]
Hello! My network has a dedicated sql server and I want to connect the moodle server to it. I have created a database named "moodle" and the user without the password. I run the container with the command:docker run-d-p 8081:80-p 8443:443 --name moodle -e MOODLE_SITENAME=e-class-e ALLOW_EMPTY_PASSWORD=yes-e MOODLE_DATABASE_USER=moodle -e MOODLE_DATABASE_NAME=moodle -v /home/lea32/moodle/moodledata:/bitnami bitnami/moodle:latest The container contains the following environment variables:MOODLE_SITENAME=e-classHOSTNAME=bb0c4350aea7MARIADB_ROOT_PASSWORD=MYSQL_CLIENT_CREATE_DATABASE_NAME=MARIADB_PORT_NUMBER=3306MOODLE_DATABASE_PASSWORD=ALLOW_EMPTY_PASSWORD=yesMYSQL_CLIENT_CREATE_DATABASE_USER=SMTP_PASSWORD=TINI_VERSION=v0.13.2PWD=/MOODLE_USERNAME=userHOME=/rootGOSU_VERSION=1.10APACHE_HTTP_PORT_NUMBER=80APACHE_HTTPS_PORT_NUMBER=443MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=SMTP_HOST=MARIADB_ROOT_USER=rootMARIADB_HOST=mariadbGOSU_GPG_KEY=B42F6819007F00F88E364FD4036A9C25BF357DD4SMTP_PROTOCOL=BITNAMI_APP_NAME=moodleSMTP_USER=TINI_GPG_KEY=595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7TERM=xtermGPG_KEY_SERVERS_LIST=ha.pool.sks-keyservers.net hkp://p80.pool.sks-keyservers.net:80 keyserver.ubuntu.com hkp://keyserver.ubuntu.com:80 pgp.mit.eduBITNAMI_IMAGE_VERSION=3.6.3-debian-9-r40MOODLE_EMAIL=user@example.comMOODLE_PASSWORD=bitnamiSHLVL=1IMAGE_OS=debian-9MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=ALLMOODLE_DATABASE_NAME=moodleSMTP_PORT=MOODLE_LANGUAGE=enMOODLE_DATABASE_USER=moodlePATH=/opt/bitnami/apache/bin:/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/opt/bitnami/mysql/bin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/binNAMI_VERSION=1.0.0-1_=/usr/bin/envDocker's log shows me the following:root@pnevmoslon:/home/lea32/moodle# docker logs -f bb0c4350aea7 Welcome to the Bitnami moodle containerSubscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodleSubmit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues WARN ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.nami INFO Initializing apacheapache INFO ==> Reconfiguring PID file location...apache INFO ==> Configuring dummy certificates...nami INFO apache successfully initializednami INFO Initializing phpnami INFO php successfully initializednami INFO Initializing mysql-clientnami INFO mysql-client successfully initializednami INFO Initializing libphpnami INFO libphp successfully initializednami INFO Initializing moodlemysql-c INFO Trying to connect to MySQL serverError executing 'postInstallation': Failed to connect to mariadb:3306 after 36 trialsIn what variable should I write the ip address of my sql server? Or do you need to change any other values of environment variables? -- My best regards,K. PED.B.Java developerOOO "UITK»Vladimir V. Bobkov+7(922)202-08-84   22.04.2009, 12:33, "Tomas Pizarro" <notifications@github.com>:If you execute the command without the daemon option (-d), you will see an error.With the following line, you are mounting a local volume (/path/to/moodle-persistence) that must exist and have proper permissions configured. Permissions of mounted volumes are very important as the MariaDB image is non-root by default.> --volume /path/to/moodle-persistence:/bitnami \Are you interested in using local volumes? Or you can also use docker-volumes? The easiest way to get started with Moodle container is the second one. You only need to clone the repository and run docker-compose up in the same directory containing the docker-compose.yml file.—You are receiving this because you authorized the thread.Reply to this email directly, view it on GitHub, or mute the thread.
