### ISSUE TITLE
Cron script not running

### ISSUE THREAD

**Issue by breyvilas** [bitnami/bitnami-docker-moodle#89]
**Description**

On a default installation with docker-compose, the cron.php script seems to not be running.

**Steps to reproduce the issue:**
1. Deploy the container as per https://github.com/bitnami/bitnami-docker-moodle#run-the-application-using-docker-compose
2. Wait a day or two
3. Go to the Admin notification page (`/admin/index.php`)

**Describe the results you received:**

A notice is printed that `The cli/cron.php maintenance script has not been run for at least 24 hours`.

**Describe the results you expected:**

That notice not to be printed ¯\\_(ツ)_/¯

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 20
 Running: 18
 Paused: 0
 Stopped: 2
Images: 46
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 342
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-141-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.32GiB
Name:  redacted
ID: redacted
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad0
docker-py version: 3.7.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Physical box with ubuntu 16.04.

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. We will try to reproduce the issue to see if the warning appears to us as well.

**Comment by javsalgar** [comment]
Hi,

In the first test I did, I just did this small operation inside the container.

```
sed -i 's|/dev/null|/tmp/test|g' /etc/cron.d/moodle
```

Then:

```
cat /tmp/test

Scheduled task complete: Incoming email pickup (tool_messageinbound\task\pickup_task)
Execute scheduled task: Cleanup event monitor events (tool_monitor\task\clean_events)
... started 10:26:02. Current memory use 25.3MB.
... used 0 dbqueries
... used 0.00020694732666016 seconds
Scheduled task complete: Cleanup event monitor events (tool_monitor\task\clean_events)
Cron script completed correctly
Cron completed at 10:26:02. Memory used 25.3MB.
Execution took 0.470763 seconds

```

Could you check if this is ocurring in your container as well? If so, then the problem is that the Moodle web-app is not detecting that the cron job is being executed.

**Comment by breyvilas** [comment]
Hi,

It would seem that the cron script is simply not running in my deployment. `/tmp/test` is never created after doing what you suggest.

**Comment by breyvilas** [comment]
I've changed `/etc/cron.d/moodle` contents to:

```cron
*/1 * * * * echo "run" > /tmp/test2; bitnami sudo su daemon -s /bin/sh -c "/opt/bitnami/php/bin/php /opt/bitnami/moodle/admin/cli/cron.php > /tmp/test"
```

And even `/tmp/test2` isn't created either. However, `service cron status` returns `cron is running`. I'm dumbfounded.

**Comment by breyvilas** [comment]
Is there a way to see the cron execution logs on this image? The usual places  (`/var/log/syslog`, `/var/log/cron`) don't seem to exist in minideb.

**Comment by breyvilas** [comment]
Seems to be working properly after restarting the container. I have no clue

**Comment by breyvilas** [comment]
After some more tests, I am inclined to believe it was a permission issue due to the persistence volumes being bind-mounted rather than named volumes.

To anyone that may find this issue in the future: don't try to bind-mount these volumes, and be very careful with owners if you do.

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. Bind mounting folders is always problematic when working with docker. This is even worse in the case of non-root containers. If you find any other issues, do not hesitate to open a new ticket
