### ISSUE TITLE
How to migrate Moodle and MariaDB containers to a new host

### ISSUE THREAD

**Issue by zimcke** [bitnami/bitnami-docker-moodle#91]
**Description**

Has anyone tried to migrate a Moodle and MariaDB container to a different host? Which steps should I take to migrate the user and application data successfully? I haven't done this before and am a bit anxious that this will not go as planned. I used the standard recommended method for persisting my data in volumes. Any help or guidance is much appreciated!

**Comment by miguelaeh** [comment]
Hi @zimcke ,
To migrate the volumes
> you can stop containers using the volume, then back up the volume’s directory (such as /var/lib/docker/volumes/<volume-name>).

Actually, if you have changed anything into the container you don't have to migrate it, you could just start a new one with the migrated volume.
In case you change something,  
>You can commit the changes in your container to an image with `docker commit`, move the image onto a new host, and then start a new container with `docker run`. This will preserve any data that your application has created inside the container.
It does not preserve data that is stored inside volumes; you need to move data volumes manually to new host.
