### ISSUE TITLE
Feature Request: Install Moodle at build time

### ISSUE THREAD

**Issue by TobiasUhmann** [bitnami/bitnami-docker-moodle#92]
Would it be possible to run the Moodle installation during the Docker build (and not during container startup) so that the container can be started in seconds instead of minutes?

I found an approach how to run the DBMS at build time (2nd answer in the SO post), however, I have no idea how to achieve it with the installation script being in another container than the database:

https://serverfault.com/questions/796762/creating-a-docker-mysql-container-with-a-prepared-database-scheme

During testing I often have to prune the volumes to make sure that changes work from a clean installation. Therefore, I have to be *very* patient during the recurring Moodle installations.

**Comment by andresbono** [comment]
Hi @TobiasUhmann,

One of the issues to move the installation to the Docker build stage is that you don't know what the database hostname and credentials are at that time.

Maybe what you can do is creating a container for testing that includes both the database and the application. However, even if you get to achieve that, it will be against all the good practices of containers.

Let us know if we can help you with that.
