### ISSUE TITLE
Problem for install on qnap container station

### ISSUE THREAD

**Issue by weeling77** [bitnami/bitnami-docker-moodle#99]
**This my  configuration**

ALLOW_EMPTY_PASSWORD | no |  
-- | -- | --
APACHE_HTTP_PORT_NUMBER | 81 |  
APACHE_HTTPS_PORT_NUMBER | 91 |  
APACHE_SET_HTTP_PORT | no |  
APACHE_SET_HTTPS_PORT | no |  
BITNAMI_APP_NAME | moodle |  
BITNAMI_IMAGE_VERSION | 3.7.1-debian-9-r48 |  
GOSU_GPG_KEY | B42F6819007F00F88E364FD4036A9C25BF357DD4 |  
GOSU_VERSION | 1.10 |  
GPG_KEY_SERVERS_LIST | ha.pool.sks-keyservers.net hkp://p80.pool.sks-keyservers.net:80 keyserver.ubuntu.com hkp://keyserver.ubuntu.com:80 pgp.mit.edu |  
IMAGE_OS | debian-9 |  
MARIADB_HOST | mariadb |  
MARIADB_PORT_NUMBER | 3306 |  
MARIADB_ROOT_PASSWORD | **** |  
MARIADB_ROOT_USER | root |  
MOODLE_DATABASE_NAME | bitnami_moodle |  
MOODLE_DATABASE_PASSWORD | **** |  
MOODLE_DATABASE_USER | bn_moodle |  
MOODLE_EMAIL | user@example.com |  
MOODLE_LANGUAGE | en |  
MOODLE_PASSWORD | bitnami |  
MOODLE_SITENAME | New Site |  
MOODLE_SKIP_INSTALL | no |  
MOODLE_USERNAME | user |  
MYSQL_CLIENT_CREATE_DATABASE_NAME | **** |  
MYSQL_CLIENT_CREATE_DATABASE_PASSWORD | ****|  
MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES | ALL |  
MYSQL_CLIENT_CREATE_DATABASE_USER | **** |  
NAMI_VERSION | 1.0.0-1 |  
PATH | /opt/bitnami/apache/bin:/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/opt/bitnami/mysql/bin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin |  
SMTP_HOST |   |  
SMTP_PASSWORD |   |  
SMTP_PORT |   |  
SMTP_PROTOCOL |   |  
SMTP_USER |   |  
TINI_GPG_KEY | 595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7 |  
TINI_VERSION | v0.13.2

**After the launch of the container I get:**

Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle                                                   
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues                                               
                                                                                                                                            
INFO  Initializing apache                                                                                                           
INFO  apache successfully initialized                                                                                                INFO  Initializing php                                                                                                              
INFO  php successfully initialized                                                                                                  
INFO  Initializing mysql-client                                                                                                     
Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries

Thanks for you help

**Comment by carrodher** [comment]
In order to reproduce the issue, can you share with use the `docker-compose.yml` that you're using?
